/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import com.apifreaks.sdk.types.CommodityHistoricalRatesRequestFormat;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CommodityHistoricalRatesRequest.Builder.class
)
public final class CommodityHistoricalRatesRequest {
  private final List<String> symbols;

  private final String apiKey;

  private final Optional<CommodityHistoricalRatesRequestFormat> format;

  private final String date;

  private final Map<String, Object> additionalProperties;

  private CommodityHistoricalRatesRequest(List<String> symbols, String apiKey,
      Optional<CommodityHistoricalRatesRequestFormat> format, String date,
      Map<String, Object> additionalProperties) {
    this.symbols = symbols;
    this.apiKey = apiKey;
    this.format = format;
    this.date = date;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Comma-separated list of commodity symbols
   */
  @JsonProperty("symbols")
  public List<String> getSymbols() {
    return symbols;
  }

  /**
   * @return Your API key
   */
  @JsonProperty("apiKey")
  public String getApiKey() {
    return apiKey;
  }

  /**
   * @return Format of the response.
   */
  @JsonProperty("format")
  public Optional<CommodityHistoricalRatesRequestFormat> getFormat() {
    return format;
  }

  /**
   * @return Historical date (YYYY-MM-DD)
   */
  @JsonProperty("date")
  public String getDate() {
    return date;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CommodityHistoricalRatesRequest && equalTo((CommodityHistoricalRatesRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CommodityHistoricalRatesRequest other) {
    return symbols.equals(other.symbols) && apiKey.equals(other.apiKey) && format.equals(other.format) && date.equals(other.date);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.symbols, this.apiKey, this.format, this.date);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiKeyStage builder() {
    return new Builder();
  }

  public interface ApiKeyStage {
    /**
     * <p>Your API key</p>
     */
    DateStage apiKey(@NotNull String apiKey);

    Builder from(CommodityHistoricalRatesRequest other);
  }

  public interface DateStage {
    /**
     * <p>Historical date (YYYY-MM-DD)</p>
     */
    SymbolsStage date(@NotNull String date);
  }

  public interface SymbolsStage {
    /**
     * <p>Comma-separated list of commodity symbols</p>
     */
    _FinalStage symbols(@NotNull List<String> symbols);
  }

  public interface _FinalStage {
    CommodityHistoricalRatesRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Format of the response.</p>
     */
    _FinalStage format(Optional<CommodityHistoricalRatesRequestFormat> format);

    _FinalStage format(CommodityHistoricalRatesRequestFormat format);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiKeyStage, DateStage, SymbolsStage, _FinalStage {
    private String apiKey;

    private String date;

    private List<String> symbols;

    private Optional<CommodityHistoricalRatesRequestFormat> format = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CommodityHistoricalRatesRequest other) {
      symbols(other.getSymbols());
      apiKey(other.getApiKey());
      format(other.getFormat());
      date(other.getDate());
      return this;
    }

    /**
     * <p>Your API key</p>
     * <p>Your API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public DateStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    /**
     * <p>Historical date (YYYY-MM-DD)</p>
     * <p>Historical date (YYYY-MM-DD)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("date")
    public SymbolsStage date(@NotNull String date) {
      this.date = Objects.requireNonNull(date, "date must not be null");
      return this;
    }

    /**
     * <p>Format of the response.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage format(CommodityHistoricalRatesRequestFormat format) {
      this.format = Optional.ofNullable(format);
      return this;
    }

    /**
     * <p>Format of the response.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "format",
        nulls = Nulls.SKIP
    )
    public _FinalStage format(Optional<CommodityHistoricalRatesRequestFormat> format) {
      this.format = format;
      return this;
    }

    /**
     * <p>Comma-separated list of commodity symbols</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("symbols")
    public _FinalStage symbols(@NotNull List<String> symbols) {
      this.symbols = Objects.requireNonNull(symbols, "symbols must not be null");
      return this;
    }

    @java.lang.Override
    public CommodityHistoricalRatesRequest build() {
      return new CommodityHistoricalRatesRequest(symbols, apiKey, format, date, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
