/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import com.apifreaks.sdk.types.CommodityLatestRatesRequestFormat;
import com.apifreaks.sdk.types.CommodityLatestRatesRequestUpdates;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CommodityLatestRatesRequest.Builder.class
)
public final class CommodityLatestRatesRequest {
  private final List<String> symbols;

  private final String apiKey;

  private final Optional<CommodityLatestRatesRequestFormat> format;

  private final CommodityLatestRatesRequestUpdates updates;

  private final Optional<String> quote;

  private final Map<String, Object> additionalProperties;

  private CommodityLatestRatesRequest(List<String> symbols, String apiKey,
      Optional<CommodityLatestRatesRequestFormat> format,
      CommodityLatestRatesRequestUpdates updates, Optional<String> quote,
      Map<String, Object> additionalProperties) {
    this.symbols = symbols;
    this.apiKey = apiKey;
    this.format = format;
    this.updates = updates;
    this.quote = quote;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Comma separated list of desired commodities symbols <em>(e.g. XAU,XAG,WTI,BRENT)</em> <strong>Required</strong>
   */
  @JsonProperty("symbols")
  public List<String> getSymbols() {
    return symbols;
  }

  /**
   * @return Your API key
   */
  @JsonProperty("apiKey")
  public String getApiKey() {
    return apiKey;
  }

  /**
   * @return Format of the Response
   */
  @JsonProperty("format")
  public Optional<CommodityLatestRatesRequestFormat> getFormat() {
    return format;
  }

  /**
   * @return Exchange rates update period. Possible values are: (1) <code>10m</code> - 10 minute update (2) <code>1m</code> - 1 minute update <strong>Required</strong>
   */
  @JsonProperty("updates")
  public CommodityLatestRatesRequestUpdates getUpdates() {
    return updates;
  }

  /**
   * @return Specifies the target currency for the exchange rate; default quote currency is the market currency of commodity <em>(e.g. USD, EUR, INR)</em>
   */
  @JsonProperty("quote")
  public Optional<String> getQuote() {
    return quote;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CommodityLatestRatesRequest && equalTo((CommodityLatestRatesRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CommodityLatestRatesRequest other) {
    return symbols.equals(other.symbols) && apiKey.equals(other.apiKey) && format.equals(other.format) && updates.equals(other.updates) && quote.equals(other.quote);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.symbols, this.apiKey, this.format, this.updates, this.quote);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiKeyStage builder() {
    return new Builder();
  }

  public interface ApiKeyStage {
    /**
     * <p>Your API key</p>
     */
    UpdatesStage apiKey(@NotNull String apiKey);

    Builder from(CommodityLatestRatesRequest other);
  }

  public interface UpdatesStage {
    /**
     * <p>Exchange rates update period. Possible values are: (1) <code>10m</code> - 10 minute update (2) <code>1m</code> - 1 minute update <strong>Required</strong></p>
     */
    SymbolsStage updates(@NotNull CommodityLatestRatesRequestUpdates updates);
  }

  public interface SymbolsStage {
    /**
     * <p>Comma separated list of desired commodities symbols <em>(e.g. XAU,XAG,WTI,BRENT)</em> <strong>Required</strong></p>
     */
    _FinalStage symbols(@NotNull List<String> symbols);
  }

  public interface _FinalStage {
    CommodityLatestRatesRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Format of the Response</p>
     */
    _FinalStage format(Optional<CommodityLatestRatesRequestFormat> format);

    _FinalStage format(CommodityLatestRatesRequestFormat format);

    /**
     * <p>Specifies the target currency for the exchange rate; default quote currency is the market currency of commodity <em>(e.g. USD, EUR, INR)</em></p>
     */
    _FinalStage quote(Optional<String> quote);

    _FinalStage quote(String quote);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiKeyStage, UpdatesStage, SymbolsStage, _FinalStage {
    private String apiKey;

    private CommodityLatestRatesRequestUpdates updates;

    private List<String> symbols;

    private Optional<String> quote = Optional.empty();

    private Optional<CommodityLatestRatesRequestFormat> format = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CommodityLatestRatesRequest other) {
      symbols(other.getSymbols());
      apiKey(other.getApiKey());
      format(other.getFormat());
      updates(other.getUpdates());
      quote(other.getQuote());
      return this;
    }

    /**
     * <p>Your API key</p>
     * <p>Your API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public UpdatesStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    /**
     * <p>Exchange rates update period. Possible values are: (1) <code>10m</code> - 10 minute update (2) <code>1m</code> - 1 minute update <strong>Required</strong></p>
     * <p>Exchange rates update period. Possible values are: (1) <code>10m</code> - 10 minute update (2) <code>1m</code> - 1 minute update <strong>Required</strong></p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("updates")
    public SymbolsStage updates(@NotNull CommodityLatestRatesRequestUpdates updates) {
      this.updates = Objects.requireNonNull(updates, "updates must not be null");
      return this;
    }

    /**
     * <p>Specifies the target currency for the exchange rate; default quote currency is the market currency of commodity <em>(e.g. USD, EUR, INR)</em></p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage quote(String quote) {
      this.quote = Optional.ofNullable(quote);
      return this;
    }

    /**
     * <p>Specifies the target currency for the exchange rate; default quote currency is the market currency of commodity <em>(e.g. USD, EUR, INR)</em></p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "quote",
        nulls = Nulls.SKIP
    )
    public _FinalStage quote(Optional<String> quote) {
      this.quote = quote;
      return this;
    }

    /**
     * <p>Format of the Response</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage format(CommodityLatestRatesRequestFormat format) {
      this.format = Optional.ofNullable(format);
      return this;
    }

    /**
     * <p>Format of the Response</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "format",
        nulls = Nulls.SKIP
    )
    public _FinalStage format(Optional<CommodityLatestRatesRequestFormat> format) {
      this.format = format;
      return this;
    }

    /**
     * <p>Comma separated list of desired commodities symbols <em>(e.g. XAU,XAG,WTI,BRENT)</em> <strong>Required</strong></p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("symbols")
    public _FinalStage symbols(@NotNull List<String> symbols) {
      this.symbols = Objects.requireNonNull(symbols, "symbols must not be null");
      return this;
    }

    @java.lang.Override
    public CommodityLatestRatesRequest build() {
      return new CommodityLatestRatesRequest(symbols, apiKey, format, updates, quote, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
