/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import com.apifreaks.sdk.types.CurrencySymbolsRequestFormat;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CurrencySymbolsRequest.Builder.class
)
public final class CurrencySymbolsRequest {
  private final String apiKey;

  private final Optional<CurrencySymbolsRequestFormat> format;

  private final Map<String, Object> additionalProperties;

  private CurrencySymbolsRequest(String apiKey, Optional<CurrencySymbolsRequestFormat> format,
      Map<String, Object> additionalProperties) {
    this.apiKey = apiKey;
    this.format = format;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Your API key
   */
  @JsonProperty("apiKey")
  public String getApiKey() {
    return apiKey;
  }

  /**
   * @return Format of the response.
   */
  @JsonProperty("format")
  public Optional<CurrencySymbolsRequestFormat> getFormat() {
    return format;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CurrencySymbolsRequest && equalTo((CurrencySymbolsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CurrencySymbolsRequest other) {
    return apiKey.equals(other.apiKey) && format.equals(other.format);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiKey, this.format);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiKeyStage builder() {
    return new Builder();
  }

  public interface ApiKeyStage {
    /**
     * <p>Your API key</p>
     */
    _FinalStage apiKey(@NotNull String apiKey);

    Builder from(CurrencySymbolsRequest other);
  }

  public interface _FinalStage {
    CurrencySymbolsRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Format of the response.</p>
     */
    _FinalStage format(Optional<CurrencySymbolsRequestFormat> format);

    _FinalStage format(CurrencySymbolsRequestFormat format);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiKeyStage, _FinalStage {
    private String apiKey;

    private Optional<CurrencySymbolsRequestFormat> format = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CurrencySymbolsRequest other) {
      apiKey(other.getApiKey());
      format(other.getFormat());
      return this;
    }

    /**
     * <p>Your API key</p>
     * <p>Your API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public _FinalStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    /**
     * <p>Format of the response.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage format(CurrencySymbolsRequestFormat format) {
      this.format = Optional.ofNullable(format);
      return this;
    }

    /**
     * <p>Format of the response.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "format",
        nulls = Nulls.SKIP
    )
    public _FinalStage format(Optional<CurrencySymbolsRequestFormat> format) {
      this.format = format;
      return this;
    }

    @java.lang.Override
    public CurrencySymbolsRequest build() {
      return new CurrencySymbolsRequest(apiKey, format, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
