/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import com.apifreaks.sdk.types.ReadabilityScoreRequestTarget;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ReadabilityScoreRequest.Builder.class
)
public final class ReadabilityScoreRequest {
  private final String apiKey;

  private final Optional<ReadabilityScoreRequestTarget> target;

  private final Optional<String> exclude;

  private final String text;

  private final Map<String, Object> additionalProperties;

  private ReadabilityScoreRequest(String apiKey, Optional<ReadabilityScoreRequestTarget> target,
      Optional<String> exclude, String text, Map<String, Object> additionalProperties) {
    this.apiKey = apiKey;
    this.target = target;
    this.exclude = exclude;
    this.text = text;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Your API key
   */
  @JsonIgnore
  public String getApiKey() {
    return apiKey;
  }

  /**
   * @return Target audience used to tune sentence difficulty levels
   */
  @JsonIgnore
  public Optional<ReadabilityScoreRequestTarget> getTarget() {
    return target;
  }

  /**
   * @return Comma-separated response sections to omit. Possible values are readability_scores, sentence_readability, readability_grade
   */
  @JsonIgnore
  public Optional<String> getExclude() {
    return exclude;
  }

  /**
   * @return Text to analyze for readability
   */
  @JsonProperty("text")
  public String getText() {
    return text;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ReadabilityScoreRequest && equalTo((ReadabilityScoreRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ReadabilityScoreRequest other) {
    return apiKey.equals(other.apiKey) && target.equals(other.target) && exclude.equals(other.exclude) && text.equals(other.text);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiKey, this.target, this.exclude, this.text);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiKeyStage builder() {
    return new Builder();
  }

  public interface ApiKeyStage {
    /**
     * <p>Your API key</p>
     */
    TextStage apiKey(@NotNull String apiKey);

    Builder from(ReadabilityScoreRequest other);
  }

  public interface TextStage {
    /**
     * <p>Text to analyze for readability</p>
     */
    _FinalStage text(@NotNull String text);
  }

  public interface _FinalStage {
    ReadabilityScoreRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Target audience used to tune sentence difficulty levels</p>
     */
    _FinalStage target(Optional<ReadabilityScoreRequestTarget> target);

    _FinalStage target(ReadabilityScoreRequestTarget target);

    /**
     * <p>Comma-separated response sections to omit. Possible values are readability_scores, sentence_readability, readability_grade</p>
     */
    _FinalStage exclude(Optional<String> exclude);

    _FinalStage exclude(String exclude);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiKeyStage, TextStage, _FinalStage {
    private String apiKey;

    private String text;

    private Optional<String> exclude = Optional.empty();

    private Optional<ReadabilityScoreRequestTarget> target = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ReadabilityScoreRequest other) {
      apiKey(other.getApiKey());
      target(other.getTarget());
      exclude(other.getExclude());
      text(other.getText());
      return this;
    }

    /**
     * <p>Your API key</p>
     * <p>Your API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public TextStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    /**
     * <p>Text to analyze for readability</p>
     * <p>Text to analyze for readability</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("text")
    public _FinalStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    /**
     * <p>Comma-separated response sections to omit. Possible values are readability_scores, sentence_readability, readability_grade</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage exclude(String exclude) {
      this.exclude = Optional.ofNullable(exclude);
      return this;
    }

    /**
     * <p>Comma-separated response sections to omit. Possible values are readability_scores, sentence_readability, readability_grade</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "exclude",
        nulls = Nulls.SKIP
    )
    public _FinalStage exclude(Optional<String> exclude) {
      this.exclude = exclude;
      return this;
    }

    /**
     * <p>Target audience used to tune sentence difficulty levels</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage target(ReadabilityScoreRequestTarget target) {
      this.target = Optional.ofNullable(target);
      return this;
    }

    /**
     * <p>Target audience used to tune sentence difficulty levels</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "target",
        nulls = Nulls.SKIP
    )
    public _FinalStage target(Optional<ReadabilityScoreRequestTarget> target) {
      this.target = target;
      return this;
    }

    @java.lang.Override
    public ReadabilityScoreRequest build() {
      return new ReadabilityScoreRequest(apiKey, target, exclude, text, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
