/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Float;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import com.apifreaks.sdk.types.TimezoneLookupRequestFormat;
import com.apifreaks.sdk.types.TimezoneLookupRequestLang;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TimezoneLookupRequest.Builder.class
)
public final class TimezoneLookupRequest {
  private final String apiKey;

  private final Optional<TimezoneLookupRequestFormat> format;

  private final Optional<String> ip;

  private final Optional<String> tz;

  private final Optional<String> location;

  private final Optional<Float> lat;

  private final Optional<Float> long_;

  private final Optional<TimezoneLookupRequestLang> lang;

  private final Optional<String> iataCode;

  private final Optional<String> icaoCode;

  private final Optional<String> loCode;

  private final Map<String, Object> additionalProperties;

  private TimezoneLookupRequest(String apiKey, Optional<TimezoneLookupRequestFormat> format,
      Optional<String> ip, Optional<String> tz, Optional<String> location, Optional<Float> lat,
      Optional<Float> long_, Optional<TimezoneLookupRequestLang> lang, Optional<String> iataCode,
      Optional<String> icaoCode, Optional<String> loCode,
      Map<String, Object> additionalProperties) {
    this.apiKey = apiKey;
    this.format = format;
    this.ip = ip;
    this.tz = tz;
    this.location = location;
    this.lat = lat;
    this.long_ = long_;
    this.lang = lang;
    this.iataCode = iataCode;
    this.icaoCode = icaoCode;
    this.loCode = loCode;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Your API key
   */
  @JsonProperty("apiKey")
  public String getApiKey() {
    return apiKey;
  }

  /**
   * @return Format of the response
   */
  @JsonProperty("format")
  public Optional<TimezoneLookupRequestFormat> getFormat() {
    return format;
  }

  /**
   * @return IPv4 or IPv6 address to extract timezone information.
   */
  @JsonProperty("ip")
  public Optional<String> getIp() {
    return ip;
  }

  /**
   * @return Timezone name (e.g., &quot;Asia/Kolkata&quot;) to retrieve information directly.
   */
  @JsonProperty("tz")
  public Optional<String> getTz() {
    return tz;
  }

  /**
   * @return Location string (preferably city and country) to extract timezone.
   */
  @JsonProperty("location")
  public Optional<String> getLocation() {
    return location;
  }

  /**
   * @return Latitude for geolocation lookup.
   */
  @JsonProperty("lat")
  public Optional<Float> getLat() {
    return lat;
  }

  /**
   * @return Longitude for geolocation lookup.
   */
  @JsonProperty("long")
  public Optional<Float> getLong() {
    return long_;
  }

  /**
   * @return Language code for response localization (default is &quot;en&quot;).
   */
  @JsonProperty("lang")
  public Optional<TimezoneLookupRequestLang> getLang() {
    return lang;
  }

  /**
   * @return 3-letter IATA airport code (e.g., JFK).
   */
  @JsonProperty("iata_code")
  public Optional<String> getIataCode() {
    return iataCode;
  }

  /**
   * @return 4-letter ICAO airport code (e.g., KJFK).
   */
  @JsonProperty("icao_code")
  public Optional<String> getIcaoCode() {
    return icaoCode;
  }

  /**
   * @return 5-letter UN/LO city code.
   */
  @JsonProperty("lo_code")
  public Optional<String> getLoCode() {
    return loCode;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TimezoneLookupRequest && equalTo((TimezoneLookupRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TimezoneLookupRequest other) {
    return apiKey.equals(other.apiKey) && format.equals(other.format) && ip.equals(other.ip) && tz.equals(other.tz) && location.equals(other.location) && lat.equals(other.lat) && long_.equals(other.long_) && lang.equals(other.lang) && iataCode.equals(other.iataCode) && icaoCode.equals(other.icaoCode) && loCode.equals(other.loCode);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiKey, this.format, this.ip, this.tz, this.location, this.lat, this.long_, this.lang, this.iataCode, this.icaoCode, this.loCode);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiKeyStage builder() {
    return new Builder();
  }

  public interface ApiKeyStage {
    /**
     * <p>Your API key</p>
     */
    _FinalStage apiKey(@NotNull String apiKey);

    Builder from(TimezoneLookupRequest other);
  }

  public interface _FinalStage {
    TimezoneLookupRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Format of the response</p>
     */
    _FinalStage format(Optional<TimezoneLookupRequestFormat> format);

    _FinalStage format(TimezoneLookupRequestFormat format);

    /**
     * <p>IPv4 or IPv6 address to extract timezone information.</p>
     */
    _FinalStage ip(Optional<String> ip);

    _FinalStage ip(String ip);

    /**
     * <p>Timezone name (e.g., &quot;Asia/Kolkata&quot;) to retrieve information directly.</p>
     */
    _FinalStage tz(Optional<String> tz);

    _FinalStage tz(String tz);

    /**
     * <p>Location string (preferably city and country) to extract timezone.</p>
     */
    _FinalStage location(Optional<String> location);

    _FinalStage location(String location);

    /**
     * <p>Latitude for geolocation lookup.</p>
     */
    _FinalStage lat(Optional<Float> lat);

    _FinalStage lat(Float lat);

    /**
     * <p>Longitude for geolocation lookup.</p>
     */
    _FinalStage long_(Optional<Float> long_);

    _FinalStage long_(Float long_);

    /**
     * <p>Language code for response localization (default is &quot;en&quot;).</p>
     */
    _FinalStage lang(Optional<TimezoneLookupRequestLang> lang);

    _FinalStage lang(TimezoneLookupRequestLang lang);

    /**
     * <p>3-letter IATA airport code (e.g., JFK).</p>
     */
    _FinalStage iataCode(Optional<String> iataCode);

    _FinalStage iataCode(String iataCode);

    /**
     * <p>4-letter ICAO airport code (e.g., KJFK).</p>
     */
    _FinalStage icaoCode(Optional<String> icaoCode);

    _FinalStage icaoCode(String icaoCode);

    /**
     * <p>5-letter UN/LO city code.</p>
     */
    _FinalStage loCode(Optional<String> loCode);

    _FinalStage loCode(String loCode);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiKeyStage, _FinalStage {
    private String apiKey;

    private Optional<String> loCode = Optional.empty();

    private Optional<String> icaoCode = Optional.empty();

    private Optional<String> iataCode = Optional.empty();

    private Optional<TimezoneLookupRequestLang> lang = Optional.empty();

    private Optional<Float> long_ = Optional.empty();

    private Optional<Float> lat = Optional.empty();

    private Optional<String> location = Optional.empty();

    private Optional<String> tz = Optional.empty();

    private Optional<String> ip = Optional.empty();

    private Optional<TimezoneLookupRequestFormat> format = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TimezoneLookupRequest other) {
      apiKey(other.getApiKey());
      format(other.getFormat());
      ip(other.getIp());
      tz(other.getTz());
      location(other.getLocation());
      lat(other.getLat());
      long_(other.getLong());
      lang(other.getLang());
      iataCode(other.getIataCode());
      icaoCode(other.getIcaoCode());
      loCode(other.getLoCode());
      return this;
    }

    /**
     * <p>Your API key</p>
     * <p>Your API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public _FinalStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    /**
     * <p>5-letter UN/LO city code.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage loCode(String loCode) {
      this.loCode = Optional.ofNullable(loCode);
      return this;
    }

    /**
     * <p>5-letter UN/LO city code.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "lo_code",
        nulls = Nulls.SKIP
    )
    public _FinalStage loCode(Optional<String> loCode) {
      this.loCode = loCode;
      return this;
    }

    /**
     * <p>4-letter ICAO airport code (e.g., KJFK).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage icaoCode(String icaoCode) {
      this.icaoCode = Optional.ofNullable(icaoCode);
      return this;
    }

    /**
     * <p>4-letter ICAO airport code (e.g., KJFK).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "icao_code",
        nulls = Nulls.SKIP
    )
    public _FinalStage icaoCode(Optional<String> icaoCode) {
      this.icaoCode = icaoCode;
      return this;
    }

    /**
     * <p>3-letter IATA airport code (e.g., JFK).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage iataCode(String iataCode) {
      this.iataCode = Optional.ofNullable(iataCode);
      return this;
    }

    /**
     * <p>3-letter IATA airport code (e.g., JFK).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "iata_code",
        nulls = Nulls.SKIP
    )
    public _FinalStage iataCode(Optional<String> iataCode) {
      this.iataCode = iataCode;
      return this;
    }

    /**
     * <p>Language code for response localization (default is &quot;en&quot;).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage lang(TimezoneLookupRequestLang lang) {
      this.lang = Optional.ofNullable(lang);
      return this;
    }

    /**
     * <p>Language code for response localization (default is &quot;en&quot;).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "lang",
        nulls = Nulls.SKIP
    )
    public _FinalStage lang(Optional<TimezoneLookupRequestLang> lang) {
      this.lang = lang;
      return this;
    }

    /**
     * <p>Longitude for geolocation lookup.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage long_(Float long_) {
      this.long_ = Optional.ofNullable(long_);
      return this;
    }

    /**
     * <p>Longitude for geolocation lookup.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "long",
        nulls = Nulls.SKIP
    )
    public _FinalStage long_(Optional<Float> long_) {
      this.long_ = long_;
      return this;
    }

    /**
     * <p>Latitude for geolocation lookup.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage lat(Float lat) {
      this.lat = Optional.ofNullable(lat);
      return this;
    }

    /**
     * <p>Latitude for geolocation lookup.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "lat",
        nulls = Nulls.SKIP
    )
    public _FinalStage lat(Optional<Float> lat) {
      this.lat = lat;
      return this;
    }

    /**
     * <p>Location string (preferably city and country) to extract timezone.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage location(String location) {
      this.location = Optional.ofNullable(location);
      return this;
    }

    /**
     * <p>Location string (preferably city and country) to extract timezone.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "location",
        nulls = Nulls.SKIP
    )
    public _FinalStage location(Optional<String> location) {
      this.location = location;
      return this;
    }

    /**
     * <p>Timezone name (e.g., &quot;Asia/Kolkata&quot;) to retrieve information directly.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage tz(String tz) {
      this.tz = Optional.ofNullable(tz);
      return this;
    }

    /**
     * <p>Timezone name (e.g., &quot;Asia/Kolkata&quot;) to retrieve information directly.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "tz",
        nulls = Nulls.SKIP
    )
    public _FinalStage tz(Optional<String> tz) {
      this.tz = tz;
      return this;
    }

    /**
     * <p>IPv4 or IPv6 address to extract timezone information.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage ip(String ip) {
      this.ip = Optional.ofNullable(ip);
      return this;
    }

    /**
     * <p>IPv4 or IPv6 address to extract timezone information.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "ip",
        nulls = Nulls.SKIP
    )
    public _FinalStage ip(Optional<String> ip) {
      this.ip = ip;
      return this;
    }

    /**
     * <p>Format of the response</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage format(TimezoneLookupRequestFormat format) {
      this.format = Optional.ofNullable(format);
      return this;
    }

    /**
     * <p>Format of the response</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "format",
        nulls = Nulls.SKIP
    )
    public _FinalStage format(Optional<TimezoneLookupRequestFormat> format) {
      this.format = format;
      return this;
    }

    @java.lang.Override
    public TimezoneLookupRequest build() {
      return new TimezoneLookupRequest(apiKey, format, ip, tz, location, lat, long_, lang, iataCode, icaoCode, loCode, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
