/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WeakWordsDetectRequest.Builder.class
)
public final class WeakWordsDetectRequest {
  private final String apiKey;

  private final String text;

  private final Map<String, Object> additionalProperties;

  private WeakWordsDetectRequest(String apiKey, String text,
      Map<String, Object> additionalProperties) {
    this.apiKey = apiKey;
    this.text = text;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Your API key
   */
  @JsonIgnore
  public String getApiKey() {
    return apiKey;
  }

  /**
   * @return Text to analyze for weak words
   */
  @JsonProperty("text")
  public String getText() {
    return text;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WeakWordsDetectRequest && equalTo((WeakWordsDetectRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WeakWordsDetectRequest other) {
    return apiKey.equals(other.apiKey) && text.equals(other.text);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiKey, this.text);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiKeyStage builder() {
    return new Builder();
  }

  public interface ApiKeyStage {
    /**
     * <p>Your API key</p>
     */
    TextStage apiKey(@NotNull String apiKey);

    Builder from(WeakWordsDetectRequest other);
  }

  public interface TextStage {
    /**
     * <p>Text to analyze for weak words</p>
     */
    _FinalStage text(@NotNull String text);
  }

  public interface _FinalStage {
    WeakWordsDetectRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiKeyStage, TextStage, _FinalStage {
    private String apiKey;

    private String text;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WeakWordsDetectRequest other) {
      apiKey(other.getApiKey());
      text(other.getText());
      return this;
    }

    /**
     * <p>Your API key</p>
     * <p>Your API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public TextStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    /**
     * <p>Text to analyze for weak words</p>
     * <p>Text to analyze for weak words</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("text")
    public _FinalStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    @java.lang.Override
    public WeakWordsDetectRequest build() {
      return new WeakWordsDetectRequest(apiKey, text, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
