/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import com.apifreaks.sdk.types.WeatherForecastRequestFormat;
import com.apifreaks.sdk.types.WeatherForecastRequestPrecision;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WeatherForecastRequest.Builder.class
)
public final class WeatherForecastRequest {
  private final String apiKey;

  private final Optional<WeatherForecastRequestFormat> format;

  private final Optional<String> startDate;

  private final Optional<String> endDate;

  private final Optional<Integer> forecastDays;

  private final Optional<String> location;

  private final Optional<Double> lat;

  private final Optional<Double> long_;

  private final Optional<String> ip;

  private final Optional<WeatherForecastRequestPrecision> precision;

  private final Optional<String> timezone;

  private final Map<String, Object> additionalProperties;

  private WeatherForecastRequest(String apiKey, Optional<WeatherForecastRequestFormat> format,
      Optional<String> startDate, Optional<String> endDate, Optional<Integer> forecastDays,
      Optional<String> location, Optional<Double> lat, Optional<Double> long_, Optional<String> ip,
      Optional<WeatherForecastRequestPrecision> precision, Optional<String> timezone,
      Map<String, Object> additionalProperties) {
    this.apiKey = apiKey;
    this.format = format;
    this.startDate = startDate;
    this.endDate = endDate;
    this.forecastDays = forecastDays;
    this.location = location;
    this.lat = lat;
    this.long_ = long_;
    this.ip = ip;
    this.precision = precision;
    this.timezone = timezone;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Your API key
   */
  @JsonProperty("apiKey")
  public String getApiKey() {
    return apiKey;
  }

  /**
   * @return Response format returned by the API.
   */
  @JsonProperty("format")
  public Optional<WeatherForecastRequestFormat> getFormat() {
    return format;
  }

  /**
   * @return Start date for the forecast in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between startDate and endDate must not exceed 16 days.
   */
  @JsonProperty("startDate")
  public Optional<String> getStartDate() {
    return startDate;
  }

  /**
   * @return End date for the forecast in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between startDate and endDate must not exceed 16 days.
   */
  @JsonProperty("endDate")
  public Optional<String> getEndDate() {
    return endDate;
  }

  /**
   * @return Number of days for the forecast, from 1 to 16. Default is 7. Maximum value is 16.
   */
  @JsonProperty("forecastDays")
  public Optional<Integer> getForecastDays() {
    return forecastDays;
  }

  /**
   * @return City name, place name, or full address.
   */
  @JsonProperty("location")
  public Optional<String> getLocation() {
    return location;
  }

  /**
   * @return Latitude of the location.
   */
  @JsonProperty("lat")
  public Optional<Double> getLat() {
    return lat;
  }

  /**
   * @return Longitude of the location.
   */
  @JsonProperty("long")
  public Optional<Double> getLong() {
    return long_;
  }

  /**
   * @return IP(v4 or v6) address for location inference.
   */
  @JsonProperty("ip")
  public Optional<String> getIp() {
    return ip;
  }

  /**
   * @return Precision of the forecast data.
   */
  @JsonProperty("precision")
  public Optional<WeatherForecastRequestPrecision> getPrecision() {
    return precision;
  }

  /**
   * @return Timezone for the results.
   */
  @JsonProperty("timezone")
  public Optional<String> getTimezone() {
    return timezone;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WeatherForecastRequest && equalTo((WeatherForecastRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WeatherForecastRequest other) {
    return apiKey.equals(other.apiKey) && format.equals(other.format) && startDate.equals(other.startDate) && endDate.equals(other.endDate) && forecastDays.equals(other.forecastDays) && location.equals(other.location) && lat.equals(other.lat) && long_.equals(other.long_) && ip.equals(other.ip) && precision.equals(other.precision) && timezone.equals(other.timezone);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiKey, this.format, this.startDate, this.endDate, this.forecastDays, this.location, this.lat, this.long_, this.ip, this.precision, this.timezone);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiKeyStage builder() {
    return new Builder();
  }

  public interface ApiKeyStage {
    /**
     * <p>Your API key</p>
     */
    _FinalStage apiKey(@NotNull String apiKey);

    Builder from(WeatherForecastRequest other);
  }

  public interface _FinalStage {
    WeatherForecastRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Response format returned by the API.</p>
     */
    _FinalStage format(Optional<WeatherForecastRequestFormat> format);

    _FinalStage format(WeatherForecastRequestFormat format);

    /**
     * <p>Start date for the forecast in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between startDate and endDate must not exceed 16 days.</p>
     */
    _FinalStage startDate(Optional<String> startDate);

    _FinalStage startDate(String startDate);

    /**
     * <p>End date for the forecast in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between startDate and endDate must not exceed 16 days.</p>
     */
    _FinalStage endDate(Optional<String> endDate);

    _FinalStage endDate(String endDate);

    /**
     * <p>Number of days for the forecast, from 1 to 16. Default is 7. Maximum value is 16.</p>
     */
    _FinalStage forecastDays(Optional<Integer> forecastDays);

    _FinalStage forecastDays(Integer forecastDays);

    /**
     * <p>City name, place name, or full address.</p>
     */
    _FinalStage location(Optional<String> location);

    _FinalStage location(String location);

    /**
     * <p>Latitude of the location.</p>
     */
    _FinalStage lat(Optional<Double> lat);

    _FinalStage lat(Double lat);

    /**
     * <p>Longitude of the location.</p>
     */
    _FinalStage long_(Optional<Double> long_);

    _FinalStage long_(Double long_);

    /**
     * <p>IP(v4 or v6) address for location inference.</p>
     */
    _FinalStage ip(Optional<String> ip);

    _FinalStage ip(String ip);

    /**
     * <p>Precision of the forecast data.</p>
     */
    _FinalStage precision(Optional<WeatherForecastRequestPrecision> precision);

    _FinalStage precision(WeatherForecastRequestPrecision precision);

    /**
     * <p>Timezone for the results.</p>
     */
    _FinalStage timezone(Optional<String> timezone);

    _FinalStage timezone(String timezone);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiKeyStage, _FinalStage {
    private String apiKey;

    private Optional<String> timezone = Optional.empty();

    private Optional<WeatherForecastRequestPrecision> precision = Optional.empty();

    private Optional<String> ip = Optional.empty();

    private Optional<Double> long_ = Optional.empty();

    private Optional<Double> lat = Optional.empty();

    private Optional<String> location = Optional.empty();

    private Optional<Integer> forecastDays = Optional.empty();

    private Optional<String> endDate = Optional.empty();

    private Optional<String> startDate = Optional.empty();

    private Optional<WeatherForecastRequestFormat> format = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WeatherForecastRequest other) {
      apiKey(other.getApiKey());
      format(other.getFormat());
      startDate(other.getStartDate());
      endDate(other.getEndDate());
      forecastDays(other.getForecastDays());
      location(other.getLocation());
      lat(other.getLat());
      long_(other.getLong());
      ip(other.getIp());
      precision(other.getPrecision());
      timezone(other.getTimezone());
      return this;
    }

    /**
     * <p>Your API key</p>
     * <p>Your API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public _FinalStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    /**
     * <p>Timezone for the results.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timezone(String timezone) {
      this.timezone = Optional.ofNullable(timezone);
      return this;
    }

    /**
     * <p>Timezone for the results.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "timezone",
        nulls = Nulls.SKIP
    )
    public _FinalStage timezone(Optional<String> timezone) {
      this.timezone = timezone;
      return this;
    }

    /**
     * <p>Precision of the forecast data.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage precision(WeatherForecastRequestPrecision precision) {
      this.precision = Optional.ofNullable(precision);
      return this;
    }

    /**
     * <p>Precision of the forecast data.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "precision",
        nulls = Nulls.SKIP
    )
    public _FinalStage precision(Optional<WeatherForecastRequestPrecision> precision) {
      this.precision = precision;
      return this;
    }

    /**
     * <p>IP(v4 or v6) address for location inference.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage ip(String ip) {
      this.ip = Optional.ofNullable(ip);
      return this;
    }

    /**
     * <p>IP(v4 or v6) address for location inference.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "ip",
        nulls = Nulls.SKIP
    )
    public _FinalStage ip(Optional<String> ip) {
      this.ip = ip;
      return this;
    }

    /**
     * <p>Longitude of the location.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage long_(Double long_) {
      this.long_ = Optional.ofNullable(long_);
      return this;
    }

    /**
     * <p>Longitude of the location.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "long",
        nulls = Nulls.SKIP
    )
    public _FinalStage long_(Optional<Double> long_) {
      this.long_ = long_;
      return this;
    }

    /**
     * <p>Latitude of the location.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage lat(Double lat) {
      this.lat = Optional.ofNullable(lat);
      return this;
    }

    /**
     * <p>Latitude of the location.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "lat",
        nulls = Nulls.SKIP
    )
    public _FinalStage lat(Optional<Double> lat) {
      this.lat = lat;
      return this;
    }

    /**
     * <p>City name, place name, or full address.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage location(String location) {
      this.location = Optional.ofNullable(location);
      return this;
    }

    /**
     * <p>City name, place name, or full address.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "location",
        nulls = Nulls.SKIP
    )
    public _FinalStage location(Optional<String> location) {
      this.location = location;
      return this;
    }

    /**
     * <p>Number of days for the forecast, from 1 to 16. Default is 7. Maximum value is 16.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage forecastDays(Integer forecastDays) {
      this.forecastDays = Optional.ofNullable(forecastDays);
      return this;
    }

    /**
     * <p>Number of days for the forecast, from 1 to 16. Default is 7. Maximum value is 16.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "forecastDays",
        nulls = Nulls.SKIP
    )
    public _FinalStage forecastDays(Optional<Integer> forecastDays) {
      this.forecastDays = forecastDays;
      return this;
    }

    /**
     * <p>End date for the forecast in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between startDate and endDate must not exceed 16 days.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage endDate(String endDate) {
      this.endDate = Optional.ofNullable(endDate);
      return this;
    }

    /**
     * <p>End date for the forecast in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between startDate and endDate must not exceed 16 days.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "endDate",
        nulls = Nulls.SKIP
    )
    public _FinalStage endDate(Optional<String> endDate) {
      this.endDate = endDate;
      return this;
    }

    /**
     * <p>Start date for the forecast in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between startDate and endDate must not exceed 16 days.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage startDate(String startDate) {
      this.startDate = Optional.ofNullable(startDate);
      return this;
    }

    /**
     * <p>Start date for the forecast in YYYY-MM-DD format. Forecast dates must be current or future dates only. Past dates are not allowed for forecast data. The difference between startDate and endDate must not exceed 16 days.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "startDate",
        nulls = Nulls.SKIP
    )
    public _FinalStage startDate(Optional<String> startDate) {
      this.startDate = startDate;
      return this;
    }

    /**
     * <p>Response format returned by the API.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage format(WeatherForecastRequestFormat format) {
      this.format = Optional.ofNullable(format);
      return this;
    }

    /**
     * <p>Response format returned by the API.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "format",
        nulls = Nulls.SKIP
    )
    public _FinalStage format(Optional<WeatherForecastRequestFormat> format) {
      this.format = format;
      return this;
    }

    @java.lang.Override
    public WeatherForecastRequest build() {
      return new WeatherForecastRequest(apiKey, format, startDate, endDate, forecastDays, location, lat, long_, ip, precision, timezone, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
