/**
 * This file was auto-generated by Fern from our API Definition.
 */

package errors;

import core.ApifreaksApiApiException;
import java.lang.Object;
import okhttp3.Response;

public final class LockedError extends ApifreaksApiApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final Object body;

  public LockedError(Object body) {
    super("LockedError", 423, body);
    this.body = body;
  }

  public LockedError(Object body, Response rawResponse) {
    super("LockedError", 423, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public Object body() {
    return this.body;
  }
}
