/**
 * This file was auto-generated by Fern from our API Definition.
 */

package requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import types.BulkEmailValidateRequestEmailDataItem;
import types.BulkEmailValidateRequestFormat;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BulkEmailValidateRequest.Builder.class
)
public final class BulkEmailValidateRequest {
  private final String apiKey;

  private final Optional<BulkEmailValidateRequestFormat> format;

  private final List<BulkEmailValidateRequestEmailDataItem> emailData;

  private final Map<String, Object> additionalProperties;

  private BulkEmailValidateRequest(String apiKey, Optional<BulkEmailValidateRequestFormat> format,
      List<BulkEmailValidateRequestEmailDataItem> emailData,
      Map<String, Object> additionalProperties) {
    this.apiKey = apiKey;
    this.format = format;
    this.emailData = emailData;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Your API key
   */
  @JsonIgnore
  public String getApiKey() {
    return apiKey;
  }

  /**
   * @return Format of the response
   */
  @JsonIgnore
  public Optional<BulkEmailValidateRequestFormat> getFormat() {
    return format;
  }

  /**
   * @return Array of email objects for bulk validation
   */
  @JsonProperty("emailData")
  public List<BulkEmailValidateRequestEmailDataItem> getEmailData() {
    return emailData;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BulkEmailValidateRequest && equalTo((BulkEmailValidateRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BulkEmailValidateRequest other) {
    return apiKey.equals(other.apiKey) && format.equals(other.format) && emailData.equals(other.emailData);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiKey, this.format, this.emailData);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiKeyStage builder() {
    return new Builder();
  }

  public interface ApiKeyStage {
    /**
     * <p>Your API key</p>
     */
    _FinalStage apiKey(@NotNull String apiKey);

    Builder from(BulkEmailValidateRequest other);
  }

  public interface _FinalStage {
    BulkEmailValidateRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Format of the response</p>
     */
    _FinalStage format(Optional<BulkEmailValidateRequestFormat> format);

    _FinalStage format(BulkEmailValidateRequestFormat format);

    /**
     * <p>Array of email objects for bulk validation</p>
     */
    _FinalStage emailData(List<BulkEmailValidateRequestEmailDataItem> emailData);

    _FinalStage addEmailData(BulkEmailValidateRequestEmailDataItem emailData);

    _FinalStage addAllEmailData(List<BulkEmailValidateRequestEmailDataItem> emailData);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiKeyStage, _FinalStage {
    private String apiKey;

    private List<BulkEmailValidateRequestEmailDataItem> emailData = new ArrayList<>();

    private Optional<BulkEmailValidateRequestFormat> format = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BulkEmailValidateRequest other) {
      apiKey(other.getApiKey());
      format(other.getFormat());
      emailData(other.getEmailData());
      return this;
    }

    /**
     * <p>Your API key</p>
     * <p>Your API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public _FinalStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    /**
     * <p>Array of email objects for bulk validation</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllEmailData(List<BulkEmailValidateRequestEmailDataItem> emailData) {
      if (emailData != null) {
        this.emailData.addAll(emailData);
      }
      return this;
    }

    /**
     * <p>Array of email objects for bulk validation</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addEmailData(BulkEmailValidateRequestEmailDataItem emailData) {
      this.emailData.add(emailData);
      return this;
    }

    /**
     * <p>Array of email objects for bulk validation</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "emailData",
        nulls = Nulls.SKIP
    )
    public _FinalStage emailData(List<BulkEmailValidateRequestEmailDataItem> emailData) {
      this.emailData.clear();
      if (emailData != null) {
        this.emailData.addAll(emailData);
      }
      return this;
    }

    /**
     * <p>Format of the response</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage format(BulkEmailValidateRequestFormat format) {
      this.format = Optional.ofNullable(format);
      return this;
    }

    /**
     * <p>Format of the response</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "format",
        nulls = Nulls.SKIP
    )
    public _FinalStage format(Optional<BulkEmailValidateRequestFormat> format) {
      this.format = format;
      return this;
    }

    @java.lang.Override
    public BulkEmailValidateRequest build() {
      return new BulkEmailValidateRequest(apiKey, format, emailData, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
