/**
 * This file was auto-generated by Fern from our API Definition.
 */

package requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import types.TimezoneConvertRequestFormat;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TimezoneConvertRequest.Builder.class
)
public final class TimezoneConvertRequest {
  private final String apiKey;

  private final Optional<TimezoneConvertRequestFormat> format;

  private final Optional<String> time;

  private final Optional<String> tzFrom;

  private final Optional<String> tzTo;

  private final Optional<Double> latFrom;

  private final Optional<Double> longFrom;

  private final Optional<Double> latTo;

  private final Optional<Double> longTo;

  private final Optional<String> locationFrom;

  private final Optional<String> locationTo;

  private final Optional<String> iataFrom;

  private final Optional<String> iataTo;

  private final Optional<String> icaoFrom;

  private final Optional<String> icaoTo;

  private final Optional<String> locodeFrom;

  private final Optional<String> locodeTo;

  private final Map<String, Object> additionalProperties;

  private TimezoneConvertRequest(String apiKey, Optional<TimezoneConvertRequestFormat> format,
      Optional<String> time, Optional<String> tzFrom, Optional<String> tzTo,
      Optional<Double> latFrom, Optional<Double> longFrom, Optional<Double> latTo,
      Optional<Double> longTo, Optional<String> locationFrom, Optional<String> locationTo,
      Optional<String> iataFrom, Optional<String> iataTo, Optional<String> icaoFrom,
      Optional<String> icaoTo, Optional<String> locodeFrom, Optional<String> locodeTo,
      Map<String, Object> additionalProperties) {
    this.apiKey = apiKey;
    this.format = format;
    this.time = time;
    this.tzFrom = tzFrom;
    this.tzTo = tzTo;
    this.latFrom = latFrom;
    this.longFrom = longFrom;
    this.latTo = latTo;
    this.longTo = longTo;
    this.locationFrom = locationFrom;
    this.locationTo = locationTo;
    this.iataFrom = iataFrom;
    this.iataTo = iataTo;
    this.icaoFrom = icaoFrom;
    this.icaoTo = icaoTo;
    this.locodeFrom = locodeFrom;
    this.locodeTo = locodeTo;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Your API key
   */
  @JsonProperty("apiKey")
  public String getApiKey() {
    return apiKey;
  }

  /**
   * @return Format of the response .
   */
  @JsonProperty("format")
  public Optional<TimezoneConvertRequestFormat> getFormat() {
    return format;
  }

  /**
   * @return Time to convert in <code>yyyy-MM-dd HH:mm</code> or <code>yyyy-MM-dd HH:mm:ss</code> format.
   */
  @JsonProperty("time")
  public Optional<String> getTime() {
    return time;
  }

  /**
   * @return Source timezone name (e.g., <code>Asia/Kolkata</code>).
   */
  @JsonProperty("tz_from")
  public Optional<String> getTzFrom() {
    return tzFrom;
  }

  /**
   * @return Target timezone name (e.g., <code>America/New_York</code>).
   */
  @JsonProperty("tz_to")
  public Optional<String> getTzTo() {
    return tzTo;
  }

  /**
   * @return Latitude of source location.
   */
  @JsonProperty("lat_from")
  public Optional<Double> getLatFrom() {
    return latFrom;
  }

  /**
   * @return Longitude of source location.
   */
  @JsonProperty("long_from")
  public Optional<Double> getLongFrom() {
    return longFrom;
  }

  /**
   * @return Latitude of target location.
   */
  @JsonProperty("lat_to")
  public Optional<Double> getLatTo() {
    return latTo;
  }

  /**
   * @return Longitude of target location.
   */
  @JsonProperty("long_to")
  public Optional<Double> getLongTo() {
    return longTo;
  }

  /**
   * @return From location (city/country).
   */
  @JsonProperty("location_from")
  public Optional<String> getLocationFrom() {
    return locationFrom;
  }

  /**
   * @return To location (city/country).
   */
  @JsonProperty("location_to")
  public Optional<String> getLocationTo() {
    return locationTo;
  }

  /**
   * @return From IATA airport code (e.g., JFK).
   */
  @JsonProperty("iata_from")
  public Optional<String> getIataFrom() {
    return iataFrom;
  }

  /**
   * @return To IATA airport code.
   */
  @JsonProperty("iata_to")
  public Optional<String> getIataTo() {
    return iataTo;
  }

  /**
   * @return From ICAO airport code (e.g., KJFK).
   */
  @JsonProperty("icao_from")
  public Optional<String> getIcaoFrom() {
    return icaoFrom;
  }

  /**
   * @return To ICAO airport code.
   */
  @JsonProperty("icao_to")
  public Optional<String> getIcaoTo() {
    return icaoTo;
  }

  /**
   * @return From UN/LO CODE.
   */
  @JsonProperty("locode_from")
  public Optional<String> getLocodeFrom() {
    return locodeFrom;
  }

  /**
   * @return To UN/LO CODE.
   */
  @JsonProperty("locode_to")
  public Optional<String> getLocodeTo() {
    return locodeTo;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TimezoneConvertRequest && equalTo((TimezoneConvertRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TimezoneConvertRequest other) {
    return apiKey.equals(other.apiKey) && format.equals(other.format) && time.equals(other.time) && tzFrom.equals(other.tzFrom) && tzTo.equals(other.tzTo) && latFrom.equals(other.latFrom) && longFrom.equals(other.longFrom) && latTo.equals(other.latTo) && longTo.equals(other.longTo) && locationFrom.equals(other.locationFrom) && locationTo.equals(other.locationTo) && iataFrom.equals(other.iataFrom) && iataTo.equals(other.iataTo) && icaoFrom.equals(other.icaoFrom) && icaoTo.equals(other.icaoTo) && locodeFrom.equals(other.locodeFrom) && locodeTo.equals(other.locodeTo);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.apiKey, this.format, this.time, this.tzFrom, this.tzTo, this.latFrom, this.longFrom, this.latTo, this.longTo, this.locationFrom, this.locationTo, this.iataFrom, this.iataTo, this.icaoFrom, this.icaoTo, this.locodeFrom, this.locodeTo);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ApiKeyStage builder() {
    return new Builder();
  }

  public interface ApiKeyStage {
    /**
     * <p>Your API key</p>
     */
    _FinalStage apiKey(@NotNull String apiKey);

    Builder from(TimezoneConvertRequest other);
  }

  public interface _FinalStage {
    TimezoneConvertRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Format of the response .</p>
     */
    _FinalStage format(Optional<TimezoneConvertRequestFormat> format);

    _FinalStage format(TimezoneConvertRequestFormat format);

    /**
     * <p>Time to convert in <code>yyyy-MM-dd HH:mm</code> or <code>yyyy-MM-dd HH:mm:ss</code> format.</p>
     */
    _FinalStage time(Optional<String> time);

    _FinalStage time(String time);

    /**
     * <p>Source timezone name (e.g., <code>Asia/Kolkata</code>).</p>
     */
    _FinalStage tzFrom(Optional<String> tzFrom);

    _FinalStage tzFrom(String tzFrom);

    /**
     * <p>Target timezone name (e.g., <code>America/New_York</code>).</p>
     */
    _FinalStage tzTo(Optional<String> tzTo);

    _FinalStage tzTo(String tzTo);

    /**
     * <p>Latitude of source location.</p>
     */
    _FinalStage latFrom(Optional<Double> latFrom);

    _FinalStage latFrom(Double latFrom);

    /**
     * <p>Longitude of source location.</p>
     */
    _FinalStage longFrom(Optional<Double> longFrom);

    _FinalStage longFrom(Double longFrom);

    /**
     * <p>Latitude of target location.</p>
     */
    _FinalStage latTo(Optional<Double> latTo);

    _FinalStage latTo(Double latTo);

    /**
     * <p>Longitude of target location.</p>
     */
    _FinalStage longTo(Optional<Double> longTo);

    _FinalStage longTo(Double longTo);

    /**
     * <p>From location (city/country).</p>
     */
    _FinalStage locationFrom(Optional<String> locationFrom);

    _FinalStage locationFrom(String locationFrom);

    /**
     * <p>To location (city/country).</p>
     */
    _FinalStage locationTo(Optional<String> locationTo);

    _FinalStage locationTo(String locationTo);

    /**
     * <p>From IATA airport code (e.g., JFK).</p>
     */
    _FinalStage iataFrom(Optional<String> iataFrom);

    _FinalStage iataFrom(String iataFrom);

    /**
     * <p>To IATA airport code.</p>
     */
    _FinalStage iataTo(Optional<String> iataTo);

    _FinalStage iataTo(String iataTo);

    /**
     * <p>From ICAO airport code (e.g., KJFK).</p>
     */
    _FinalStage icaoFrom(Optional<String> icaoFrom);

    _FinalStage icaoFrom(String icaoFrom);

    /**
     * <p>To ICAO airport code.</p>
     */
    _FinalStage icaoTo(Optional<String> icaoTo);

    _FinalStage icaoTo(String icaoTo);

    /**
     * <p>From UN/LO CODE.</p>
     */
    _FinalStage locodeFrom(Optional<String> locodeFrom);

    _FinalStage locodeFrom(String locodeFrom);

    /**
     * <p>To UN/LO CODE.</p>
     */
    _FinalStage locodeTo(Optional<String> locodeTo);

    _FinalStage locodeTo(String locodeTo);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ApiKeyStage, _FinalStage {
    private String apiKey;

    private Optional<String> locodeTo = Optional.empty();

    private Optional<String> locodeFrom = Optional.empty();

    private Optional<String> icaoTo = Optional.empty();

    private Optional<String> icaoFrom = Optional.empty();

    private Optional<String> iataTo = Optional.empty();

    private Optional<String> iataFrom = Optional.empty();

    private Optional<String> locationTo = Optional.empty();

    private Optional<String> locationFrom = Optional.empty();

    private Optional<Double> longTo = Optional.empty();

    private Optional<Double> latTo = Optional.empty();

    private Optional<Double> longFrom = Optional.empty();

    private Optional<Double> latFrom = Optional.empty();

    private Optional<String> tzTo = Optional.empty();

    private Optional<String> tzFrom = Optional.empty();

    private Optional<String> time = Optional.empty();

    private Optional<TimezoneConvertRequestFormat> format = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TimezoneConvertRequest other) {
      apiKey(other.getApiKey());
      format(other.getFormat());
      time(other.getTime());
      tzFrom(other.getTzFrom());
      tzTo(other.getTzTo());
      latFrom(other.getLatFrom());
      longFrom(other.getLongFrom());
      latTo(other.getLatTo());
      longTo(other.getLongTo());
      locationFrom(other.getLocationFrom());
      locationTo(other.getLocationTo());
      iataFrom(other.getIataFrom());
      iataTo(other.getIataTo());
      icaoFrom(other.getIcaoFrom());
      icaoTo(other.getIcaoTo());
      locodeFrom(other.getLocodeFrom());
      locodeTo(other.getLocodeTo());
      return this;
    }

    /**
     * <p>Your API key</p>
     * <p>Your API key</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apiKey")
    public _FinalStage apiKey(@NotNull String apiKey) {
      this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
      return this;
    }

    /**
     * <p>To UN/LO CODE.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage locodeTo(String locodeTo) {
      this.locodeTo = Optional.ofNullable(locodeTo);
      return this;
    }

    /**
     * <p>To UN/LO CODE.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "locode_to",
        nulls = Nulls.SKIP
    )
    public _FinalStage locodeTo(Optional<String> locodeTo) {
      this.locodeTo = locodeTo;
      return this;
    }

    /**
     * <p>From UN/LO CODE.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage locodeFrom(String locodeFrom) {
      this.locodeFrom = Optional.ofNullable(locodeFrom);
      return this;
    }

    /**
     * <p>From UN/LO CODE.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "locode_from",
        nulls = Nulls.SKIP
    )
    public _FinalStage locodeFrom(Optional<String> locodeFrom) {
      this.locodeFrom = locodeFrom;
      return this;
    }

    /**
     * <p>To ICAO airport code.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage icaoTo(String icaoTo) {
      this.icaoTo = Optional.ofNullable(icaoTo);
      return this;
    }

    /**
     * <p>To ICAO airport code.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "icao_to",
        nulls = Nulls.SKIP
    )
    public _FinalStage icaoTo(Optional<String> icaoTo) {
      this.icaoTo = icaoTo;
      return this;
    }

    /**
     * <p>From ICAO airport code (e.g., KJFK).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage icaoFrom(String icaoFrom) {
      this.icaoFrom = Optional.ofNullable(icaoFrom);
      return this;
    }

    /**
     * <p>From ICAO airport code (e.g., KJFK).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "icao_from",
        nulls = Nulls.SKIP
    )
    public _FinalStage icaoFrom(Optional<String> icaoFrom) {
      this.icaoFrom = icaoFrom;
      return this;
    }

    /**
     * <p>To IATA airport code.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage iataTo(String iataTo) {
      this.iataTo = Optional.ofNullable(iataTo);
      return this;
    }

    /**
     * <p>To IATA airport code.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "iata_to",
        nulls = Nulls.SKIP
    )
    public _FinalStage iataTo(Optional<String> iataTo) {
      this.iataTo = iataTo;
      return this;
    }

    /**
     * <p>From IATA airport code (e.g., JFK).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage iataFrom(String iataFrom) {
      this.iataFrom = Optional.ofNullable(iataFrom);
      return this;
    }

    /**
     * <p>From IATA airport code (e.g., JFK).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "iata_from",
        nulls = Nulls.SKIP
    )
    public _FinalStage iataFrom(Optional<String> iataFrom) {
      this.iataFrom = iataFrom;
      return this;
    }

    /**
     * <p>To location (city/country).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage locationTo(String locationTo) {
      this.locationTo = Optional.ofNullable(locationTo);
      return this;
    }

    /**
     * <p>To location (city/country).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "location_to",
        nulls = Nulls.SKIP
    )
    public _FinalStage locationTo(Optional<String> locationTo) {
      this.locationTo = locationTo;
      return this;
    }

    /**
     * <p>From location (city/country).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage locationFrom(String locationFrom) {
      this.locationFrom = Optional.ofNullable(locationFrom);
      return this;
    }

    /**
     * <p>From location (city/country).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "location_from",
        nulls = Nulls.SKIP
    )
    public _FinalStage locationFrom(Optional<String> locationFrom) {
      this.locationFrom = locationFrom;
      return this;
    }

    /**
     * <p>Longitude of target location.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage longTo(Double longTo) {
      this.longTo = Optional.ofNullable(longTo);
      return this;
    }

    /**
     * <p>Longitude of target location.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "long_to",
        nulls = Nulls.SKIP
    )
    public _FinalStage longTo(Optional<Double> longTo) {
      this.longTo = longTo;
      return this;
    }

    /**
     * <p>Latitude of target location.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage latTo(Double latTo) {
      this.latTo = Optional.ofNullable(latTo);
      return this;
    }

    /**
     * <p>Latitude of target location.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "lat_to",
        nulls = Nulls.SKIP
    )
    public _FinalStage latTo(Optional<Double> latTo) {
      this.latTo = latTo;
      return this;
    }

    /**
     * <p>Longitude of source location.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage longFrom(Double longFrom) {
      this.longFrom = Optional.ofNullable(longFrom);
      return this;
    }

    /**
     * <p>Longitude of source location.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "long_from",
        nulls = Nulls.SKIP
    )
    public _FinalStage longFrom(Optional<Double> longFrom) {
      this.longFrom = longFrom;
      return this;
    }

    /**
     * <p>Latitude of source location.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage latFrom(Double latFrom) {
      this.latFrom = Optional.ofNullable(latFrom);
      return this;
    }

    /**
     * <p>Latitude of source location.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "lat_from",
        nulls = Nulls.SKIP
    )
    public _FinalStage latFrom(Optional<Double> latFrom) {
      this.latFrom = latFrom;
      return this;
    }

    /**
     * <p>Target timezone name (e.g., <code>America/New_York</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage tzTo(String tzTo) {
      this.tzTo = Optional.ofNullable(tzTo);
      return this;
    }

    /**
     * <p>Target timezone name (e.g., <code>America/New_York</code>).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "tz_to",
        nulls = Nulls.SKIP
    )
    public _FinalStage tzTo(Optional<String> tzTo) {
      this.tzTo = tzTo;
      return this;
    }

    /**
     * <p>Source timezone name (e.g., <code>Asia/Kolkata</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage tzFrom(String tzFrom) {
      this.tzFrom = Optional.ofNullable(tzFrom);
      return this;
    }

    /**
     * <p>Source timezone name (e.g., <code>Asia/Kolkata</code>).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "tz_from",
        nulls = Nulls.SKIP
    )
    public _FinalStage tzFrom(Optional<String> tzFrom) {
      this.tzFrom = tzFrom;
      return this;
    }

    /**
     * <p>Time to convert in <code>yyyy-MM-dd HH:mm</code> or <code>yyyy-MM-dd HH:mm:ss</code> format.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage time(String time) {
      this.time = Optional.ofNullable(time);
      return this;
    }

    /**
     * <p>Time to convert in <code>yyyy-MM-dd HH:mm</code> or <code>yyyy-MM-dd HH:mm:ss</code> format.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "time",
        nulls = Nulls.SKIP
    )
    public _FinalStage time(Optional<String> time) {
      this.time = time;
      return this;
    }

    /**
     * <p>Format of the response .</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage format(TimezoneConvertRequestFormat format) {
      this.format = Optional.ofNullable(format);
      return this;
    }

    /**
     * <p>Format of the response .</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "format",
        nulls = Nulls.SKIP
    )
    public _FinalStage format(Optional<TimezoneConvertRequestFormat> format) {
      this.format = format;
      return this;
    }

    @java.lang.Override
    public TimezoneConvertRequest build() {
      return new TimezoneConvertRequest(apiKey, format, time, tzFrom, tzTo, latFrom, longFrom, latTo, longTo, locationFrom, locationTo, iataFrom, iataTo, icaoFrom, icaoTo, locodeFrom, locodeTo, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
