/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.apifreaks.sdk.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AstronomyLookupV2ResponseAstronomyEvening.Builder.class
)
public final class AstronomyLookupV2ResponseAstronomyEvening {
  private final String goldenHourBegin;

  private final String goldenHourEnd;

  private final String blueHourBegin;

  private final String blueHourEnd;

  private final String civilTwilightBegin;

  private final String civilTwilightEnd;

  private final String nauticalTwilightBegin;

  private final String nauticalTwilightEnd;

  private final String astronomicalTwilightBegin;

  private final String astronomicalTwilightEnd;

  private final Map<String, Object> additionalProperties;

  private AstronomyLookupV2ResponseAstronomyEvening(String goldenHourBegin, String goldenHourEnd,
      String blueHourBegin, String blueHourEnd, String civilTwilightBegin, String civilTwilightEnd,
      String nauticalTwilightBegin, String nauticalTwilightEnd, String astronomicalTwilightBegin,
      String astronomicalTwilightEnd, Map<String, Object> additionalProperties) {
    this.goldenHourBegin = goldenHourBegin;
    this.goldenHourEnd = goldenHourEnd;
    this.blueHourBegin = blueHourBegin;
    this.blueHourEnd = blueHourEnd;
    this.civilTwilightBegin = civilTwilightBegin;
    this.civilTwilightEnd = civilTwilightEnd;
    this.nauticalTwilightBegin = nauticalTwilightBegin;
    this.nauticalTwilightEnd = nauticalTwilightEnd;
    this.astronomicalTwilightBegin = astronomicalTwilightBegin;
    this.astronomicalTwilightEnd = astronomicalTwilightEnd;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The beginning of the golden hour in the evening
   */
  @JsonProperty("golden_hour_begin")
  public String getGoldenHourBegin() {
    return goldenHourBegin;
  }

  /**
   * @return The end of the golden hour in the evening
   */
  @JsonProperty("golden_hour_end")
  public String getGoldenHourEnd() {
    return goldenHourEnd;
  }

  /**
   * @return The beginning of the blue hour in the evening
   */
  @JsonProperty("blue_hour_begin")
  public String getBlueHourBegin() {
    return blueHourBegin;
  }

  /**
   * @return The end of the blue hour in the evening
   */
  @JsonProperty("blue_hour_end")
  public String getBlueHourEnd() {
    return blueHourEnd;
  }

  /**
   * @return The start of civil twilight in the evening
   */
  @JsonProperty("civil_twilight_begin")
  public String getCivilTwilightBegin() {
    return civilTwilightBegin;
  }

  /**
   * @return The end of civil twilight in the evening
   */
  @JsonProperty("civil_twilight_end")
  public String getCivilTwilightEnd() {
    return civilTwilightEnd;
  }

  /**
   * @return The start of nautical twilight in the evening
   */
  @JsonProperty("nautical_twilight_begin")
  public String getNauticalTwilightBegin() {
    return nauticalTwilightBegin;
  }

  /**
   * @return The end of nautical twilight in the evening
   */
  @JsonProperty("nautical_twilight_end")
  public String getNauticalTwilightEnd() {
    return nauticalTwilightEnd;
  }

  /**
   * @return The start of astronomical twilight in the evening
   */
  @JsonProperty("astronomical_twilight_begin")
  public String getAstronomicalTwilightBegin() {
    return astronomicalTwilightBegin;
  }

  /**
   * @return The end of astronomical twilight in the evening
   */
  @JsonProperty("astronomical_twilight_end")
  public String getAstronomicalTwilightEnd() {
    return astronomicalTwilightEnd;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AstronomyLookupV2ResponseAstronomyEvening && equalTo((AstronomyLookupV2ResponseAstronomyEvening) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AstronomyLookupV2ResponseAstronomyEvening other) {
    return goldenHourBegin.equals(other.goldenHourBegin) && goldenHourEnd.equals(other.goldenHourEnd) && blueHourBegin.equals(other.blueHourBegin) && blueHourEnd.equals(other.blueHourEnd) && civilTwilightBegin.equals(other.civilTwilightBegin) && civilTwilightEnd.equals(other.civilTwilightEnd) && nauticalTwilightBegin.equals(other.nauticalTwilightBegin) && nauticalTwilightEnd.equals(other.nauticalTwilightEnd) && astronomicalTwilightBegin.equals(other.astronomicalTwilightBegin) && astronomicalTwilightEnd.equals(other.astronomicalTwilightEnd);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.goldenHourBegin, this.goldenHourEnd, this.blueHourBegin, this.blueHourEnd, this.civilTwilightBegin, this.civilTwilightEnd, this.nauticalTwilightBegin, this.nauticalTwilightEnd, this.astronomicalTwilightBegin, this.astronomicalTwilightEnd);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static GoldenHourBeginStage builder() {
    return new Builder();
  }

  public interface GoldenHourBeginStage {
    /**
     * <p>The beginning of the golden hour in the evening</p>
     */
    GoldenHourEndStage goldenHourBegin(@NotNull String goldenHourBegin);

    Builder from(AstronomyLookupV2ResponseAstronomyEvening other);
  }

  public interface GoldenHourEndStage {
    /**
     * <p>The end of the golden hour in the evening</p>
     */
    BlueHourBeginStage goldenHourEnd(@NotNull String goldenHourEnd);
  }

  public interface BlueHourBeginStage {
    /**
     * <p>The beginning of the blue hour in the evening</p>
     */
    BlueHourEndStage blueHourBegin(@NotNull String blueHourBegin);
  }

  public interface BlueHourEndStage {
    /**
     * <p>The end of the blue hour in the evening</p>
     */
    CivilTwilightBeginStage blueHourEnd(@NotNull String blueHourEnd);
  }

  public interface CivilTwilightBeginStage {
    /**
     * <p>The start of civil twilight in the evening</p>
     */
    CivilTwilightEndStage civilTwilightBegin(@NotNull String civilTwilightBegin);
  }

  public interface CivilTwilightEndStage {
    /**
     * <p>The end of civil twilight in the evening</p>
     */
    NauticalTwilightBeginStage civilTwilightEnd(@NotNull String civilTwilightEnd);
  }

  public interface NauticalTwilightBeginStage {
    /**
     * <p>The start of nautical twilight in the evening</p>
     */
    NauticalTwilightEndStage nauticalTwilightBegin(@NotNull String nauticalTwilightBegin);
  }

  public interface NauticalTwilightEndStage {
    /**
     * <p>The end of nautical twilight in the evening</p>
     */
    AstronomicalTwilightBeginStage nauticalTwilightEnd(@NotNull String nauticalTwilightEnd);
  }

  public interface AstronomicalTwilightBeginStage {
    /**
     * <p>The start of astronomical twilight in the evening</p>
     */
    AstronomicalTwilightEndStage astronomicalTwilightBegin(
        @NotNull String astronomicalTwilightBegin);
  }

  public interface AstronomicalTwilightEndStage {
    /**
     * <p>The end of astronomical twilight in the evening</p>
     */
    _FinalStage astronomicalTwilightEnd(@NotNull String astronomicalTwilightEnd);
  }

  public interface _FinalStage {
    AstronomyLookupV2ResponseAstronomyEvening build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements GoldenHourBeginStage, GoldenHourEndStage, BlueHourBeginStage, BlueHourEndStage, CivilTwilightBeginStage, CivilTwilightEndStage, NauticalTwilightBeginStage, NauticalTwilightEndStage, AstronomicalTwilightBeginStage, AstronomicalTwilightEndStage, _FinalStage {
    private String goldenHourBegin;

    private String goldenHourEnd;

    private String blueHourBegin;

    private String blueHourEnd;

    private String civilTwilightBegin;

    private String civilTwilightEnd;

    private String nauticalTwilightBegin;

    private String nauticalTwilightEnd;

    private String astronomicalTwilightBegin;

    private String astronomicalTwilightEnd;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AstronomyLookupV2ResponseAstronomyEvening other) {
      goldenHourBegin(other.getGoldenHourBegin());
      goldenHourEnd(other.getGoldenHourEnd());
      blueHourBegin(other.getBlueHourBegin());
      blueHourEnd(other.getBlueHourEnd());
      civilTwilightBegin(other.getCivilTwilightBegin());
      civilTwilightEnd(other.getCivilTwilightEnd());
      nauticalTwilightBegin(other.getNauticalTwilightBegin());
      nauticalTwilightEnd(other.getNauticalTwilightEnd());
      astronomicalTwilightBegin(other.getAstronomicalTwilightBegin());
      astronomicalTwilightEnd(other.getAstronomicalTwilightEnd());
      return this;
    }

    /**
     * <p>The beginning of the golden hour in the evening</p>
     * <p>The beginning of the golden hour in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("golden_hour_begin")
    public GoldenHourEndStage goldenHourBegin(@NotNull String goldenHourBegin) {
      this.goldenHourBegin = Objects.requireNonNull(goldenHourBegin, "goldenHourBegin must not be null");
      return this;
    }

    /**
     * <p>The end of the golden hour in the evening</p>
     * <p>The end of the golden hour in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("golden_hour_end")
    public BlueHourBeginStage goldenHourEnd(@NotNull String goldenHourEnd) {
      this.goldenHourEnd = Objects.requireNonNull(goldenHourEnd, "goldenHourEnd must not be null");
      return this;
    }

    /**
     * <p>The beginning of the blue hour in the evening</p>
     * <p>The beginning of the blue hour in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("blue_hour_begin")
    public BlueHourEndStage blueHourBegin(@NotNull String blueHourBegin) {
      this.blueHourBegin = Objects.requireNonNull(blueHourBegin, "blueHourBegin must not be null");
      return this;
    }

    /**
     * <p>The end of the blue hour in the evening</p>
     * <p>The end of the blue hour in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("blue_hour_end")
    public CivilTwilightBeginStage blueHourEnd(@NotNull String blueHourEnd) {
      this.blueHourEnd = Objects.requireNonNull(blueHourEnd, "blueHourEnd must not be null");
      return this;
    }

    /**
     * <p>The start of civil twilight in the evening</p>
     * <p>The start of civil twilight in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("civil_twilight_begin")
    public CivilTwilightEndStage civilTwilightBegin(@NotNull String civilTwilightBegin) {
      this.civilTwilightBegin = Objects.requireNonNull(civilTwilightBegin, "civilTwilightBegin must not be null");
      return this;
    }

    /**
     * <p>The end of civil twilight in the evening</p>
     * <p>The end of civil twilight in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("civil_twilight_end")
    public NauticalTwilightBeginStage civilTwilightEnd(@NotNull String civilTwilightEnd) {
      this.civilTwilightEnd = Objects.requireNonNull(civilTwilightEnd, "civilTwilightEnd must not be null");
      return this;
    }

    /**
     * <p>The start of nautical twilight in the evening</p>
     * <p>The start of nautical twilight in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("nautical_twilight_begin")
    public NauticalTwilightEndStage nauticalTwilightBegin(@NotNull String nauticalTwilightBegin) {
      this.nauticalTwilightBegin = Objects.requireNonNull(nauticalTwilightBegin, "nauticalTwilightBegin must not be null");
      return this;
    }

    /**
     * <p>The end of nautical twilight in the evening</p>
     * <p>The end of nautical twilight in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("nautical_twilight_end")
    public AstronomicalTwilightBeginStage nauticalTwilightEnd(@NotNull String nauticalTwilightEnd) {
      this.nauticalTwilightEnd = Objects.requireNonNull(nauticalTwilightEnd, "nauticalTwilightEnd must not be null");
      return this;
    }

    /**
     * <p>The start of astronomical twilight in the evening</p>
     * <p>The start of astronomical twilight in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("astronomical_twilight_begin")
    public AstronomicalTwilightEndStage astronomicalTwilightBegin(
        @NotNull String astronomicalTwilightBegin) {
      this.astronomicalTwilightBegin = Objects.requireNonNull(astronomicalTwilightBegin, "astronomicalTwilightBegin must not be null");
      return this;
    }

    /**
     * <p>The end of astronomical twilight in the evening</p>
     * <p>The end of astronomical twilight in the evening</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("astronomical_twilight_end")
    public _FinalStage astronomicalTwilightEnd(@NotNull String astronomicalTwilightEnd) {
      this.astronomicalTwilightEnd = Objects.requireNonNull(astronomicalTwilightEnd, "astronomicalTwilightEnd must not be null");
      return this;
    }

    @java.lang.Override
    public AstronomyLookupV2ResponseAstronomyEvening build() {
      return new AstronomyLookupV2ResponseAstronomyEvening(goldenHourBegin, goldenHourEnd, blueHourBegin, blueHourEnd, civilTwilightBegin, civilTwilightEnd, nauticalTwilightBegin, nauticalTwilightEnd, astronomicalTwilightBegin, astronomicalTwilightEnd, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
