/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AstronomyLookupResponseLocation.Builder.class
)
public final class AstronomyLookupResponseLocation {
  private final Optional<String> locationString;

  private final Optional<String> continentCode;

  private final Optional<String> continentName;

  private final Optional<String> countryCode2;

  private final Optional<String> countryCode3;

  private final String countryName;

  private final Optional<String> countryNameOfficial;

  private final Optional<Boolean> isEu;

  private final String stateProv;

  private final Optional<String> stateCode;

  private final Optional<String> district;

  private final String city;

  private final Optional<String> zipcode;

  private final String latitude;

  private final String longitude;

  private final String locality;

  private final String elevation;

  private final Map<String, Object> additionalProperties;

  private AstronomyLookupResponseLocation(Optional<String> locationString,
      Optional<String> continentCode, Optional<String> continentName, Optional<String> countryCode2,
      Optional<String> countryCode3, String countryName, Optional<String> countryNameOfficial,
      Optional<Boolean> isEu, String stateProv, Optional<String> stateCode,
      Optional<String> district, String city, Optional<String> zipcode, String latitude,
      String longitude, String locality, String elevation,
      Map<String, Object> additionalProperties) {
    this.locationString = locationString;
    this.continentCode = continentCode;
    this.continentName = continentName;
    this.countryCode2 = countryCode2;
    this.countryCode3 = countryCode3;
    this.countryName = countryName;
    this.countryNameOfficial = countryNameOfficial;
    this.isEu = isEu;
    this.stateProv = stateProv;
    this.stateCode = stateCode;
    this.district = district;
    this.city = city;
    this.zipcode = zipcode;
    this.latitude = latitude;
    this.longitude = longitude;
    this.locality = locality;
    this.elevation = elevation;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The complete geographical location (returned when looking up by the location parameter).
   */
  @JsonProperty("location_string")
  public Optional<String> getLocationString() {
    return locationString;
  }

  @JsonProperty("continent_code")
  public Optional<String> getContinentCode() {
    return continentCode;
  }

  @JsonProperty("continent_name")
  public Optional<String> getContinentName() {
    return continentName;
  }

  @JsonProperty("country_code2")
  public Optional<String> getCountryCode2() {
    return countryCode2;
  }

  @JsonProperty("country_code3")
  public Optional<String> getCountryCode3() {
    return countryCode3;
  }

  @JsonProperty("country_name")
  public String getCountryName() {
    return countryName;
  }

  @JsonProperty("country_name_official")
  public Optional<String> getCountryNameOfficial() {
    return countryNameOfficial;
  }

  @JsonProperty("is_eu")
  public Optional<Boolean> getIsEu() {
    return isEu;
  }

  @JsonProperty("state_prov")
  public String getStateProv() {
    return stateProv;
  }

  @JsonProperty("state_code")
  public Optional<String> getStateCode() {
    return stateCode;
  }

  @JsonProperty("district")
  public Optional<String> getDistrict() {
    return district;
  }

  @JsonProperty("city")
  public String getCity() {
    return city;
  }

  @JsonProperty("zipcode")
  public Optional<String> getZipcode() {
    return zipcode;
  }

  @JsonProperty("latitude")
  public String getLatitude() {
    return latitude;
  }

  @JsonProperty("longitude")
  public String getLongitude() {
    return longitude;
  }

  @JsonProperty("locality")
  public String getLocality() {
    return locality;
  }

  @JsonProperty("elevation")
  public String getElevation() {
    return elevation;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AstronomyLookupResponseLocation && equalTo((AstronomyLookupResponseLocation) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AstronomyLookupResponseLocation other) {
    return locationString.equals(other.locationString) && continentCode.equals(other.continentCode) && continentName.equals(other.continentName) && countryCode2.equals(other.countryCode2) && countryCode3.equals(other.countryCode3) && countryName.equals(other.countryName) && countryNameOfficial.equals(other.countryNameOfficial) && isEu.equals(other.isEu) && stateProv.equals(other.stateProv) && stateCode.equals(other.stateCode) && district.equals(other.district) && city.equals(other.city) && zipcode.equals(other.zipcode) && latitude.equals(other.latitude) && longitude.equals(other.longitude) && locality.equals(other.locality) && elevation.equals(other.elevation);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.locationString, this.continentCode, this.continentName, this.countryCode2, this.countryCode3, this.countryName, this.countryNameOfficial, this.isEu, this.stateProv, this.stateCode, this.district, this.city, this.zipcode, this.latitude, this.longitude, this.locality, this.elevation);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CountryNameStage builder() {
    return new Builder();
  }

  public interface CountryNameStage {
    StateProvStage countryName(@NotNull String countryName);

    Builder from(AstronomyLookupResponseLocation other);
  }

  public interface StateProvStage {
    CityStage stateProv(@NotNull String stateProv);
  }

  public interface CityStage {
    LatitudeStage city(@NotNull String city);
  }

  public interface LatitudeStage {
    LongitudeStage latitude(@NotNull String latitude);
  }

  public interface LongitudeStage {
    LocalityStage longitude(@NotNull String longitude);
  }

  public interface LocalityStage {
    ElevationStage locality(@NotNull String locality);
  }

  public interface ElevationStage {
    _FinalStage elevation(@NotNull String elevation);
  }

  public interface _FinalStage {
    AstronomyLookupResponseLocation build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The complete geographical location (returned when looking up by the location parameter).</p>
     */
    _FinalStage locationString(Optional<String> locationString);

    _FinalStage locationString(String locationString);

    _FinalStage continentCode(Optional<String> continentCode);

    _FinalStage continentCode(String continentCode);

    _FinalStage continentName(Optional<String> continentName);

    _FinalStage continentName(String continentName);

    _FinalStage countryCode2(Optional<String> countryCode2);

    _FinalStage countryCode2(String countryCode2);

    _FinalStage countryCode3(Optional<String> countryCode3);

    _FinalStage countryCode3(String countryCode3);

    _FinalStage countryNameOfficial(Optional<String> countryNameOfficial);

    _FinalStage countryNameOfficial(String countryNameOfficial);

    _FinalStage isEu(Optional<Boolean> isEu);

    _FinalStage isEu(Boolean isEu);

    _FinalStage stateCode(Optional<String> stateCode);

    _FinalStage stateCode(String stateCode);

    _FinalStage district(Optional<String> district);

    _FinalStage district(String district);

    _FinalStage zipcode(Optional<String> zipcode);

    _FinalStage zipcode(String zipcode);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CountryNameStage, StateProvStage, CityStage, LatitudeStage, LongitudeStage, LocalityStage, ElevationStage, _FinalStage {
    private String countryName;

    private String stateProv;

    private String city;

    private String latitude;

    private String longitude;

    private String locality;

    private String elevation;

    private Optional<String> zipcode = Optional.empty();

    private Optional<String> district = Optional.empty();

    private Optional<String> stateCode = Optional.empty();

    private Optional<Boolean> isEu = Optional.empty();

    private Optional<String> countryNameOfficial = Optional.empty();

    private Optional<String> countryCode3 = Optional.empty();

    private Optional<String> countryCode2 = Optional.empty();

    private Optional<String> continentName = Optional.empty();

    private Optional<String> continentCode = Optional.empty();

    private Optional<String> locationString = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AstronomyLookupResponseLocation other) {
      locationString(other.getLocationString());
      continentCode(other.getContinentCode());
      continentName(other.getContinentName());
      countryCode2(other.getCountryCode2());
      countryCode3(other.getCountryCode3());
      countryName(other.getCountryName());
      countryNameOfficial(other.getCountryNameOfficial());
      isEu(other.getIsEu());
      stateProv(other.getStateProv());
      stateCode(other.getStateCode());
      district(other.getDistrict());
      city(other.getCity());
      zipcode(other.getZipcode());
      latitude(other.getLatitude());
      longitude(other.getLongitude());
      locality(other.getLocality());
      elevation(other.getElevation());
      return this;
    }

    @java.lang.Override
    @JsonSetter("country_name")
    public StateProvStage countryName(@NotNull String countryName) {
      this.countryName = Objects.requireNonNull(countryName, "countryName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("state_prov")
    public CityStage stateProv(@NotNull String stateProv) {
      this.stateProv = Objects.requireNonNull(stateProv, "stateProv must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("city")
    public LatitudeStage city(@NotNull String city) {
      this.city = Objects.requireNonNull(city, "city must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("latitude")
    public LongitudeStage latitude(@NotNull String latitude) {
      this.latitude = Objects.requireNonNull(latitude, "latitude must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("longitude")
    public LocalityStage longitude(@NotNull String longitude) {
      this.longitude = Objects.requireNonNull(longitude, "longitude must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("locality")
    public ElevationStage locality(@NotNull String locality) {
      this.locality = Objects.requireNonNull(locality, "locality must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("elevation")
    public _FinalStage elevation(@NotNull String elevation) {
      this.elevation = Objects.requireNonNull(elevation, "elevation must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage zipcode(String zipcode) {
      this.zipcode = Optional.ofNullable(zipcode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "zipcode",
        nulls = Nulls.SKIP
    )
    public _FinalStage zipcode(Optional<String> zipcode) {
      this.zipcode = zipcode;
      return this;
    }

    @java.lang.Override
    public _FinalStage district(String district) {
      this.district = Optional.ofNullable(district);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "district",
        nulls = Nulls.SKIP
    )
    public _FinalStage district(Optional<String> district) {
      this.district = district;
      return this;
    }

    @java.lang.Override
    public _FinalStage stateCode(String stateCode) {
      this.stateCode = Optional.ofNullable(stateCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "state_code",
        nulls = Nulls.SKIP
    )
    public _FinalStage stateCode(Optional<String> stateCode) {
      this.stateCode = stateCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage isEu(Boolean isEu) {
      this.isEu = Optional.ofNullable(isEu);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "is_eu",
        nulls = Nulls.SKIP
    )
    public _FinalStage isEu(Optional<Boolean> isEu) {
      this.isEu = isEu;
      return this;
    }

    @java.lang.Override
    public _FinalStage countryNameOfficial(String countryNameOfficial) {
      this.countryNameOfficial = Optional.ofNullable(countryNameOfficial);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "country_name_official",
        nulls = Nulls.SKIP
    )
    public _FinalStage countryNameOfficial(Optional<String> countryNameOfficial) {
      this.countryNameOfficial = countryNameOfficial;
      return this;
    }

    @java.lang.Override
    public _FinalStage countryCode3(String countryCode3) {
      this.countryCode3 = Optional.ofNullable(countryCode3);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "country_code3",
        nulls = Nulls.SKIP
    )
    public _FinalStage countryCode3(Optional<String> countryCode3) {
      this.countryCode3 = countryCode3;
      return this;
    }

    @java.lang.Override
    public _FinalStage countryCode2(String countryCode2) {
      this.countryCode2 = Optional.ofNullable(countryCode2);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "country_code2",
        nulls = Nulls.SKIP
    )
    public _FinalStage countryCode2(Optional<String> countryCode2) {
      this.countryCode2 = countryCode2;
      return this;
    }

    @java.lang.Override
    public _FinalStage continentName(String continentName) {
      this.continentName = Optional.ofNullable(continentName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "continent_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage continentName(Optional<String> continentName) {
      this.continentName = continentName;
      return this;
    }

    @java.lang.Override
    public _FinalStage continentCode(String continentCode) {
      this.continentCode = Optional.ofNullable(continentCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "continent_code",
        nulls = Nulls.SKIP
    )
    public _FinalStage continentCode(Optional<String> continentCode) {
      this.continentCode = continentCode;
      return this;
    }

    /**
     * <p>The complete geographical location (returned when looking up by the location parameter).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage locationString(String locationString) {
      this.locationString = Optional.ofNullable(locationString);
      return this;
    }

    /**
     * <p>The complete geographical location (returned when looking up by the location parameter).</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "location_string",
        nulls = Nulls.SKIP
    )
    public _FinalStage locationString(Optional<String> locationString) {
      this.locationString = locationString;
      return this;
    }

    @java.lang.Override
    public AstronomyLookupResponseLocation build() {
      return new AstronomyLookupResponseLocation(locationString, continentCode, continentName, countryCode2, countryCode3, countryName, countryNameOfficial, isEu, stateProv, stateCode, district, city, zipcode, latitude, longitude, locality, elevation, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
