/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BulkDomainAvailabilityCheckResponse.Builder.class
)
public final class BulkDomainAvailabilityCheckResponse {
  private final List<BulkDomainAvailabilityCheckResponseBulkDomainAvailableResponseItem> bulkDomainAvailableResponse;

  private final Map<String, Object> additionalProperties;

  private BulkDomainAvailabilityCheckResponse(
      List<BulkDomainAvailabilityCheckResponseBulkDomainAvailableResponseItem> bulkDomainAvailableResponse,
      Map<String, Object> additionalProperties) {
    this.bulkDomainAvailableResponse = bulkDomainAvailableResponse;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("bulk_domain_available_response")
  public List<BulkDomainAvailabilityCheckResponseBulkDomainAvailableResponseItem> getBulkDomainAvailableResponse(
      ) {
    return bulkDomainAvailableResponse;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BulkDomainAvailabilityCheckResponse && equalTo((BulkDomainAvailabilityCheckResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BulkDomainAvailabilityCheckResponse other) {
    return bulkDomainAvailableResponse.equals(other.bulkDomainAvailableResponse);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.bulkDomainAvailableResponse);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<BulkDomainAvailabilityCheckResponseBulkDomainAvailableResponseItem> bulkDomainAvailableResponse = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(BulkDomainAvailabilityCheckResponse other) {
      bulkDomainAvailableResponse(other.getBulkDomainAvailableResponse());
      return this;
    }

    @JsonSetter(
        value = "bulk_domain_available_response",
        nulls = Nulls.SKIP
    )
    public Builder bulkDomainAvailableResponse(
        List<BulkDomainAvailabilityCheckResponseBulkDomainAvailableResponseItem> bulkDomainAvailableResponse) {
      this.bulkDomainAvailableResponse.clear();
      this.bulkDomainAvailableResponse.addAll(bulkDomainAvailableResponse);
      return this;
    }

    public Builder addBulkDomainAvailableResponse(
        BulkDomainAvailabilityCheckResponseBulkDomainAvailableResponseItem bulkDomainAvailableResponse) {
      this.bulkDomainAvailableResponse.add(bulkDomainAvailableResponse);
      return this;
    }

    public Builder addAllBulkDomainAvailableResponse(
        List<BulkDomainAvailabilityCheckResponseBulkDomainAvailableResponseItem> bulkDomainAvailableResponse) {
      this.bulkDomainAvailableResponse.addAll(bulkDomainAvailableResponse);
      return this;
    }

    public BulkDomainAvailabilityCheckResponse build() {
      return new BulkDomainAvailabilityCheckResponse(bulkDomainAvailableResponse, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
