/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BulkScreenshotCaptureResponseResultsItem.Builder.class
)
public final class BulkScreenshotCaptureResponseResultsItem {
  private final String status;

  private final Optional<String> errorMessage;

  private final BulkScreenshotCaptureResponseResultsItemUrl url;

  private final Map<String, Object> additionalProperties;

  private BulkScreenshotCaptureResponseResultsItem(String status, Optional<String> errorMessage,
      BulkScreenshotCaptureResponseResultsItemUrl url, Map<String, Object> additionalProperties) {
    this.status = status;
    this.errorMessage = errorMessage;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("status")
  public String getStatus() {
    return status;
  }

  @JsonProperty("error_message")
  public Optional<String> getErrorMessage() {
    return errorMessage;
  }

  @JsonProperty("url")
  public BulkScreenshotCaptureResponseResultsItemUrl getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BulkScreenshotCaptureResponseResultsItem && equalTo((BulkScreenshotCaptureResponseResultsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BulkScreenshotCaptureResponseResultsItem other) {
    return status.equals(other.status) && errorMessage.equals(other.errorMessage) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status, this.errorMessage, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static StatusStage builder() {
    return new Builder();
  }

  public interface StatusStage {
    UrlStage status(@NotNull String status);

    Builder from(BulkScreenshotCaptureResponseResultsItem other);
  }

  public interface UrlStage {
    _FinalStage url(@NotNull BulkScreenshotCaptureResponseResultsItemUrl url);
  }

  public interface _FinalStage {
    BulkScreenshotCaptureResponseResultsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage errorMessage(Optional<String> errorMessage);

    _FinalStage errorMessage(String errorMessage);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements StatusStage, UrlStage, _FinalStage {
    private String status;

    private BulkScreenshotCaptureResponseResultsItemUrl url;

    private Optional<String> errorMessage = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BulkScreenshotCaptureResponseResultsItem other) {
      status(other.getStatus());
      errorMessage(other.getErrorMessage());
      url(other.getUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public UrlStage status(@NotNull String status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull BulkScreenshotCaptureResponseResultsItemUrl url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage errorMessage(String errorMessage) {
      this.errorMessage = Optional.ofNullable(errorMessage);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "error_message",
        nulls = Nulls.SKIP
    )
    public _FinalStage errorMessage(Optional<String> errorMessage) {
      this.errorMessage = errorMessage;
      return this;
    }

    @java.lang.Override
    public BulkScreenshotCaptureResponseResultsItem build() {
      return new BulkScreenshotCaptureResponseResultsItem(status, errorMessage, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
