/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CommodityLatestRatesRequestFormat {
  public static final CommodityLatestRatesRequestFormat JSON = new CommodityLatestRatesRequestFormat(Value.JSON, "json");

  private final Value value;

  private final String string;

  CommodityLatestRatesRequestFormat(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CommodityLatestRatesRequestFormat && this.string.equals(((CommodityLatestRatesRequestFormat) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case JSON:
        return visitor.visitJson();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CommodityLatestRatesRequestFormat valueOf(String value) {
    switch (value) {
      case "json":
        return JSON;
      default:
        return new CommodityLatestRatesRequestFormat(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    JSON,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitJson();

    T visitUnknown(String unknownType);
  }
}
