/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CommodityLatestRatesRequestUpdates {
  public static final CommodityLatestRatesRequestUpdates TEN_M = new CommodityLatestRatesRequestUpdates(Value.TEN_M, "10m");

  public static final CommodityLatestRatesRequestUpdates ONE_M = new CommodityLatestRatesRequestUpdates(Value.ONE_M, "1m");

  private final Value value;

  private final String string;

  CommodityLatestRatesRequestUpdates(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CommodityLatestRatesRequestUpdates && this.string.equals(((CommodityLatestRatesRequestUpdates) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case TEN_M:
        return visitor.visitTenM();
      case ONE_M:
        return visitor.visitOneM();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CommodityLatestRatesRequestUpdates valueOf(String value) {
    switch (value) {
      case "10m":
        return TEN_M;
      case "1m":
        return ONE_M;
      default:
        return new CommodityLatestRatesRequestUpdates(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    TEN_M,

    ONE_M,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitTenM();

    T visitOneM();

    T visitUnknown(String unknownType);
  }
}
