/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class CommoditySymbolsV2ResponseSymbolsItemUpdateInterval {
  public static final CommoditySymbolsV2ResponseSymbolsItemUpdateInterval PER_SECOND = new CommoditySymbolsV2ResponseSymbolsItemUpdateInterval(Value.PER_SECOND, "PER_SECOND");

  public static final CommoditySymbolsV2ResponseSymbolsItemUpdateInterval PER_MINUTE = new CommoditySymbolsV2ResponseSymbolsItemUpdateInterval(Value.PER_MINUTE, "PER_MINUTE");

  public static final CommoditySymbolsV2ResponseSymbolsItemUpdateInterval PER_DAY = new CommoditySymbolsV2ResponseSymbolsItemUpdateInterval(Value.PER_DAY, "PER_DAY");

  public static final CommoditySymbolsV2ResponseSymbolsItemUpdateInterval PER10MINUTES = new CommoditySymbolsV2ResponseSymbolsItemUpdateInterval(Value.PER10MINUTES, "PER_10_MINUTES");

  public static final CommoditySymbolsV2ResponseSymbolsItemUpdateInterval PER_MONTH = new CommoditySymbolsV2ResponseSymbolsItemUpdateInterval(Value.PER_MONTH, "PER_MONTH");

  public static final CommoditySymbolsV2ResponseSymbolsItemUpdateInterval PER_WEEK = new CommoditySymbolsV2ResponseSymbolsItemUpdateInterval(Value.PER_WEEK, "PER_WEEK");

  public static final CommoditySymbolsV2ResponseSymbolsItemUpdateInterval PER_HOUR = new CommoditySymbolsV2ResponseSymbolsItemUpdateInterval(Value.PER_HOUR, "PER_HOUR");

  private final Value value;

  private final String string;

  CommoditySymbolsV2ResponseSymbolsItemUpdateInterval(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof CommoditySymbolsV2ResponseSymbolsItemUpdateInterval && this.string.equals(((CommoditySymbolsV2ResponseSymbolsItemUpdateInterval) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PER_SECOND:
        return visitor.visitPerSecond();
      case PER_MINUTE:
        return visitor.visitPerMinute();
      case PER_DAY:
        return visitor.visitPerDay();
      case PER10MINUTES:
        return visitor.visitPer10Minutes();
      case PER_MONTH:
        return visitor.visitPerMonth();
      case PER_WEEK:
        return visitor.visitPerWeek();
      case PER_HOUR:
        return visitor.visitPerHour();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static CommoditySymbolsV2ResponseSymbolsItemUpdateInterval valueOf(String value) {
    switch (value) {
      case "PER_SECOND":
        return PER_SECOND;
      case "PER_MINUTE":
        return PER_MINUTE;
      case "PER_DAY":
        return PER_DAY;
      case "PER_10_MINUTES":
        return PER10MINUTES;
      case "PER_MONTH":
        return PER_MONTH;
      case "PER_WEEK":
        return PER_WEEK;
      case "PER_HOUR":
        return PER_HOUR;
      default:
        return new CommoditySymbolsV2ResponseSymbolsItemUpdateInterval(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PER_SECOND,

    PER_MINUTE,

    PER10MINUTES,

    PER_HOUR,

    PER_DAY,

    PER_WEEK,

    PER_MONTH,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPerSecond();

    T visitPerMinute();

    T visitPer10Minutes();

    T visitPerHour();

    T visitPerDay();

    T visitPerWeek();

    T visitPerMonth();

    T visitUnknown(String unknownType);
  }
}
