/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class DomainDnsLookupResponseDnsRecordsItemAddressDnsType {
  public static final DomainDnsLookupResponseDnsRecordsItemAddressDnsType A = new DomainDnsLookupResponseDnsRecordsItemAddressDnsType(Value.A, "A");

  public static final DomainDnsLookupResponseDnsRecordsItemAddressDnsType AAAA = new DomainDnsLookupResponseDnsRecordsItemAddressDnsType(Value.AAAA, "AAAA");

  private final Value value;

  private final String string;

  DomainDnsLookupResponseDnsRecordsItemAddressDnsType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof DomainDnsLookupResponseDnsRecordsItemAddressDnsType && this.string.equals(((DomainDnsLookupResponseDnsRecordsItemAddressDnsType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case A:
        return visitor.visitA();
      case AAAA:
        return visitor.visitAaaa();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static DomainDnsLookupResponseDnsRecordsItemAddressDnsType valueOf(String value) {
    switch (value) {
      case "A":
        return A;
      case "AAAA":
        return AAAA;
      default:
        return new DomainDnsLookupResponseDnsRecordsItemAddressDnsType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    A,

    AAAA,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitA();

    T visitAaaa();

    T visitUnknown(String unknownType);
  }
}
