/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.apifreaks.sdk.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DomainReputationResponseEmailDeliverabilityAuthenticationDmarc.Builder.class
)
public final class DomainReputationResponseEmailDeliverabilityAuthenticationDmarc {
  private final boolean present;

  private final String policy;

  private final boolean reportingConfigured;

  private final Map<String, Object> additionalProperties;

  private DomainReputationResponseEmailDeliverabilityAuthenticationDmarc(boolean present,
      String policy, boolean reportingConfigured, Map<String, Object> additionalProperties) {
    this.present = present;
    this.policy = policy;
    this.reportingConfigured = reportingConfigured;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Indicates whether a DMARC record was found.
   */
  @JsonProperty("present")
  public boolean getPresent() {
    return present;
  }

  /**
   * @return DMARC enforcement policy applied to failing messages (e.g. none, quarantine, reject).
   */
  @JsonProperty("policy")
  public String getPolicy() {
    return policy;
  }

  /**
   * @return Indicates whether DMARC aggregate / forensic reporting addresses are configured.
   */
  @JsonProperty("reporting_configured")
  public boolean getReportingConfigured() {
    return reportingConfigured;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DomainReputationResponseEmailDeliverabilityAuthenticationDmarc && equalTo((DomainReputationResponseEmailDeliverabilityAuthenticationDmarc) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DomainReputationResponseEmailDeliverabilityAuthenticationDmarc other) {
    return present == other.present && policy.equals(other.policy) && reportingConfigured == other.reportingConfigured;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.present, this.policy, this.reportingConfigured);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PresentStage builder() {
    return new Builder();
  }

  public interface PresentStage {
    /**
     * <p>Indicates whether a DMARC record was found.</p>
     */
    PolicyStage present(boolean present);

    Builder from(DomainReputationResponseEmailDeliverabilityAuthenticationDmarc other);
  }

  public interface PolicyStage {
    /**
     * <p>DMARC enforcement policy applied to failing messages (e.g. none, quarantine, reject).</p>
     */
    ReportingConfiguredStage policy(@NotNull String policy);
  }

  public interface ReportingConfiguredStage {
    /**
     * <p>Indicates whether DMARC aggregate / forensic reporting addresses are configured.</p>
     */
    _FinalStage reportingConfigured(boolean reportingConfigured);
  }

  public interface _FinalStage {
    DomainReputationResponseEmailDeliverabilityAuthenticationDmarc build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PresentStage, PolicyStage, ReportingConfiguredStage, _FinalStage {
    private boolean present;

    private String policy;

    private boolean reportingConfigured;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DomainReputationResponseEmailDeliverabilityAuthenticationDmarc other) {
      present(other.getPresent());
      policy(other.getPolicy());
      reportingConfigured(other.getReportingConfigured());
      return this;
    }

    /**
     * <p>Indicates whether a DMARC record was found.</p>
     * <p>Indicates whether a DMARC record was found.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("present")
    public PolicyStage present(boolean present) {
      this.present = present;
      return this;
    }

    /**
     * <p>DMARC enforcement policy applied to failing messages (e.g. none, quarantine, reject).</p>
     * <p>DMARC enforcement policy applied to failing messages (e.g. none, quarantine, reject).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("policy")
    public ReportingConfiguredStage policy(@NotNull String policy) {
      this.policy = Objects.requireNonNull(policy, "policy must not be null");
      return this;
    }

    /**
     * <p>Indicates whether DMARC aggregate / forensic reporting addresses are configured.</p>
     * <p>Indicates whether DMARC aggregate / forensic reporting addresses are configured.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("reporting_configured")
    public _FinalStage reportingConfigured(boolean reportingConfigured) {
      this.reportingConfigured = reportingConfigured;
      return this;
    }

    @java.lang.Override
    public DomainReputationResponseEmailDeliverabilityAuthenticationDmarc build() {
      return new DomainReputationResponseEmailDeliverabilityAuthenticationDmarc(present, policy, reportingConfigured, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
