/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.apifreaks.sdk.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem.Builder.class
)
public final class DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem {
  private final String policyId;

  private final Optional<DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItemPolicyQualifier> policyQualifier;

  private final Map<String, Object> additionalProperties;

  private DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem(
      String policyId,
      Optional<DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItemPolicyQualifier> policyQualifier,
      Map<String, Object> additionalProperties) {
    this.policyId = policyId;
    this.policyQualifier = policyQualifier;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Policy identifier
   */
  @JsonProperty("policyId")
  public String getPolicyId() {
    return policyId;
  }

  /**
   * @return Policy qualifier details
   */
  @JsonProperty("policyQualifier")
  public Optional<DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItemPolicyQualifier> getPolicyQualifier(
      ) {
    return policyQualifier;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem && equalTo((DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(
      DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem other) {
    return policyId.equals(other.policyId) && policyQualifier.equals(other.policyQualifier);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.policyId, this.policyQualifier);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PolicyIdStage builder() {
    return new Builder();
  }

  public interface PolicyIdStage {
    /**
     * <p>Policy identifier</p>
     */
    _FinalStage policyId(@NotNull String policyId);

    Builder from(
        DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem other);
  }

  public interface _FinalStage {
    DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Policy qualifier details</p>
     */
    _FinalStage policyQualifier(
        Optional<DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItemPolicyQualifier> policyQualifier);

    _FinalStage policyQualifier(
        DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItemPolicyQualifier policyQualifier);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PolicyIdStage, _FinalStage {
    private String policyId;

    private Optional<DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItemPolicyQualifier> policyQualifier = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(
        DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem other) {
      policyId(other.getPolicyId());
      policyQualifier(other.getPolicyQualifier());
      return this;
    }

    /**
     * <p>Policy identifier</p>
     * <p>Policy identifier</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("policyId")
    public _FinalStage policyId(@NotNull String policyId) {
      this.policyId = Objects.requireNonNull(policyId, "policyId must not be null");
      return this;
    }

    /**
     * <p>Policy qualifier details</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage policyQualifier(
        DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItemPolicyQualifier policyQualifier) {
      this.policyQualifier = Optional.ofNullable(policyQualifier);
      return this;
    }

    /**
     * <p>Policy qualifier details</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "policyQualifier",
        nulls = Nulls.SKIP
    )
    public _FinalStage policyQualifier(
        Optional<DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItemPolicyQualifier> policyQualifier) {
      this.policyQualifier = policyQualifier;
      return this;
    }

    @java.lang.Override
    public DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem build(
        ) {
      return new DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesItem(policyId, policyQualifier, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
