/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.apifreaks.sdk.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DomainReputationResponseEmailDeliverabilityIssuesItem.Builder.class
)
public final class DomainReputationResponseEmailDeliverabilityIssuesItem {
  private final Optional<String> code;

  private final Optional<String> severity;

  private final Optional<String> message;

  private final Optional<String> recommendation;

  private final Map<String, Object> additionalProperties;

  private DomainReputationResponseEmailDeliverabilityIssuesItem(Optional<String> code,
      Optional<String> severity, Optional<String> message, Optional<String> recommendation,
      Map<String, Object> additionalProperties) {
    this.code = code;
    this.severity = severity;
    this.message = message;
    this.recommendation = recommendation;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Machine-readable code identifying the specific deliverability issue.
   */
  @JsonProperty("code")
  public Optional<String> getCode() {
    return code;
  }

  /**
   * @return Severity level assigned to the detected issue.
   */
  @JsonProperty("severity")
  public Optional<String> getSeverity() {
    return severity;
  }

  /**
   * @return Human-readable explanation of the issue.
   */
  @JsonProperty("message")
  public Optional<String> getMessage() {
    return message;
  }

  /**
   * @return Plain-language description of the exact fix to apply.
   */
  @JsonProperty("recommendation")
  public Optional<String> getRecommendation() {
    return recommendation;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DomainReputationResponseEmailDeliverabilityIssuesItem && equalTo((DomainReputationResponseEmailDeliverabilityIssuesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DomainReputationResponseEmailDeliverabilityIssuesItem other) {
    return code.equals(other.code) && severity.equals(other.severity) && message.equals(other.message) && recommendation.equals(other.recommendation);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.code, this.severity, this.message, this.recommendation);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> code = Optional.empty();

    private Optional<String> severity = Optional.empty();

    private Optional<String> message = Optional.empty();

    private Optional<String> recommendation = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(DomainReputationResponseEmailDeliverabilityIssuesItem other) {
      code(other.getCode());
      severity(other.getSeverity());
      message(other.getMessage());
      recommendation(other.getRecommendation());
      return this;
    }

    /**
     * <p>Machine-readable code identifying the specific deliverability issue.</p>
     */
    @JsonSetter(
        value = "code",
        nulls = Nulls.SKIP
    )
    public Builder code(Optional<String> code) {
      this.code = code;
      return this;
    }

    public Builder code(String code) {
      this.code = Optional.ofNullable(code);
      return this;
    }

    /**
     * <p>Severity level assigned to the detected issue.</p>
     */
    @JsonSetter(
        value = "severity",
        nulls = Nulls.SKIP
    )
    public Builder severity(Optional<String> severity) {
      this.severity = severity;
      return this;
    }

    public Builder severity(String severity) {
      this.severity = Optional.ofNullable(severity);
      return this;
    }

    /**
     * <p>Human-readable explanation of the issue.</p>
     */
    @JsonSetter(
        value = "message",
        nulls = Nulls.SKIP
    )
    public Builder message(Optional<String> message) {
      this.message = message;
      return this;
    }

    public Builder message(String message) {
      this.message = Optional.ofNullable(message);
      return this;
    }

    /**
     * <p>Plain-language description of the exact fix to apply.</p>
     */
    @JsonSetter(
        value = "recommendation",
        nulls = Nulls.SKIP
    )
    public Builder recommendation(Optional<String> recommendation) {
      this.recommendation = recommendation;
      return this;
    }

    public Builder recommendation(String recommendation) {
      this.recommendation = Optional.ofNullable(recommendation);
      return this;
    }

    public DomainReputationResponseEmailDeliverabilityIssuesItem build() {
      return new DomainReputationResponseEmailDeliverabilityIssuesItem(code, severity, message, recommendation, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
