/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity {
  public static final DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity POSITIVE = new DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity(Value.POSITIVE, "positive");

  public static final DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity NEGATIVE = new DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity(Value.NEGATIVE, "negative");

  public static final DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity NEUTRAL = new DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity(Value.NEUTRAL, "neutral");

  private final Value value;

  private final String string;

  DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity && this.string.equals(((DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case POSITIVE:
        return visitor.visitPositive();
      case NEGATIVE:
        return visitor.visitNegative();
      case NEUTRAL:
        return visitor.visitNeutral();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity valueOf(
      String value) {
    switch (value) {
      case "positive":
        return POSITIVE;
      case "negative":
        return NEGATIVE;
      case "neutral":
        return NEUTRAL;
      default:
        return new DomainReputationResponseTrustSignalsSignalsPositiveItemPolarity(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    POSITIVE,

    NEGATIVE,

    NEUTRAL,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPositive();

    T visitNegative();

    T visitNeutral();

    T visitUnknown(String unknownType);
  }
}
