/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.apifreaks.sdk.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DomainReputationResponseTrustSignals.Builder.class
)
public final class DomainReputationResponseTrustSignals {
  private final int trustScore;

  private final String trustBand;

  private final DomainReputationResponseTrustSignalsSignals signals;

  private final DomainReputationResponseTrustSignalsIndicators indicators;

  private final Map<String, Object> additionalProperties;

  private DomainReputationResponseTrustSignals(int trustScore, String trustBand,
      DomainReputationResponseTrustSignalsSignals signals,
      DomainReputationResponseTrustSignalsIndicators indicators,
      Map<String, Object> additionalProperties) {
    this.trustScore = trustScore;
    this.trustBand = trustBand;
    this.signals = signals;
    this.indicators = indicators;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Overall trust score (0-100).
   */
  @JsonProperty("trust_score")
  public int getTrustScore() {
    return trustScore;
  }

  /**
   * @return Trust score band / category (e.g. low, medium, high).
   */
  @JsonProperty("trust_band")
  public String getTrustBand() {
    return trustBand;
  }

  /**
   * @return Signals contributing to the trust score.
   */
  @JsonProperty("signals")
  public DomainReputationResponseTrustSignalsSignals getSignals() {
    return signals;
  }

  /**
   * @return Individual trust / risk indicators for the domain.
   */
  @JsonProperty("indicators")
  public DomainReputationResponseTrustSignalsIndicators getIndicators() {
    return indicators;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DomainReputationResponseTrustSignals && equalTo((DomainReputationResponseTrustSignals) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DomainReputationResponseTrustSignals other) {
    return trustScore == other.trustScore && trustBand.equals(other.trustBand) && signals.equals(other.signals) && indicators.equals(other.indicators);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.trustScore, this.trustBand, this.signals, this.indicators);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TrustScoreStage builder() {
    return new Builder();
  }

  public interface TrustScoreStage {
    /**
     * <p>Overall trust score (0-100).</p>
     */
    TrustBandStage trustScore(int trustScore);

    Builder from(DomainReputationResponseTrustSignals other);
  }

  public interface TrustBandStage {
    /**
     * <p>Trust score band / category (e.g. low, medium, high).</p>
     */
    SignalsStage trustBand(@NotNull String trustBand);
  }

  public interface SignalsStage {
    /**
     * <p>Signals contributing to the trust score.</p>
     */
    IndicatorsStage signals(@NotNull DomainReputationResponseTrustSignalsSignals signals);
  }

  public interface IndicatorsStage {
    /**
     * <p>Individual trust / risk indicators for the domain.</p>
     */
    _FinalStage indicators(@NotNull DomainReputationResponseTrustSignalsIndicators indicators);
  }

  public interface _FinalStage {
    DomainReputationResponseTrustSignals build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TrustScoreStage, TrustBandStage, SignalsStage, IndicatorsStage, _FinalStage {
    private int trustScore;

    private String trustBand;

    private DomainReputationResponseTrustSignalsSignals signals;

    private DomainReputationResponseTrustSignalsIndicators indicators;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DomainReputationResponseTrustSignals other) {
      trustScore(other.getTrustScore());
      trustBand(other.getTrustBand());
      signals(other.getSignals());
      indicators(other.getIndicators());
      return this;
    }

    /**
     * <p>Overall trust score (0-100).</p>
     * <p>Overall trust score (0-100).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("trust_score")
    public TrustBandStage trustScore(int trustScore) {
      this.trustScore = trustScore;
      return this;
    }

    /**
     * <p>Trust score band / category (e.g. low, medium, high).</p>
     * <p>Trust score band / category (e.g. low, medium, high).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("trust_band")
    public SignalsStage trustBand(@NotNull String trustBand) {
      this.trustBand = Objects.requireNonNull(trustBand, "trustBand must not be null");
      return this;
    }

    /**
     * <p>Signals contributing to the trust score.</p>
     * <p>Signals contributing to the trust score.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("signals")
    public IndicatorsStage signals(@NotNull DomainReputationResponseTrustSignalsSignals signals) {
      this.signals = Objects.requireNonNull(signals, "signals must not be null");
      return this;
    }

    /**
     * <p>Individual trust / risk indicators for the domain.</p>
     * <p>Individual trust / risk indicators for the domain.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("indicators")
    public _FinalStage indicators(
        @NotNull DomainReputationResponseTrustSignalsIndicators indicators) {
      this.indicators = Objects.requireNonNull(indicators, "indicators must not be null");
      return this;
    }

    @java.lang.Override
    public DomainReputationResponseTrustSignals build() {
      return new DomainReputationResponseTrustSignals(trustScore, trustBand, signals, indicators, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
