/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority.Builder.class
)
public final class DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority {
  private final String name;

  private final int type;

  private final DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriorityDnsType dnsType;

  private final int ttl;

  private final String rawText;

  private final int rRsetType;

  private final String target;

  private final int priority;

  private final Map<String, Object> additionalProperties;

  private DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority(String name,
      int type,
      DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriorityDnsType dnsType,
      int ttl, String rawText, int rRsetType, String target, int priority,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.type = type;
    this.dnsType = dnsType;
    this.ttl = ttl;
    this.rawText = rawText;
    this.rRsetType = rRsetType;
    this.target = target;
    this.priority = priority;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("type")
  public int getType() {
    return type;
  }

  @JsonProperty("dnsType")
  public DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriorityDnsType getDnsType(
      ) {
    return dnsType;
  }

  @JsonProperty("ttl")
  public int getTtl() {
    return ttl;
  }

  @JsonProperty("rawText")
  public String getRawText() {
    return rawText;
  }

  @JsonProperty("rRsetType")
  public int getRRsetType() {
    return rRsetType;
  }

  @JsonProperty("target")
  public String getTarget() {
    return target;
  }

  @JsonProperty("priority")
  public int getPriority() {
    return priority;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority && equalTo((DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(
      DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority other) {
    return name.equals(other.name) && type == other.type && dnsType.equals(other.dnsType) && ttl == other.ttl && rawText.equals(other.rawText) && rRsetType == other.rRsetType && target.equals(other.target) && priority == other.priority;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.type, this.dnsType, this.ttl, this.rawText, this.rRsetType, this.target, this.priority);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    TypeStage name(@NotNull String name);

    Builder from(DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority other);
  }

  public interface TypeStage {
    DnsTypeStage type(int type);
  }

  public interface DnsTypeStage {
    TtlStage dnsType(
        @NotNull DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriorityDnsType dnsType);
  }

  public interface TtlStage {
    RawTextStage ttl(int ttl);
  }

  public interface RawTextStage {
    RRsetTypeStage rawText(@NotNull String rawText);
  }

  public interface RRsetTypeStage {
    TargetStage rRsetType(int rRsetType);
  }

  public interface TargetStage {
    PriorityStage target(@NotNull String target);
  }

  public interface PriorityStage {
    _FinalStage priority(int priority);
  }

  public interface _FinalStage {
    DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, TypeStage, DnsTypeStage, TtlStage, RawTextStage, RRsetTypeStage, TargetStage, PriorityStage, _FinalStage {
    private String name;

    private int type;

    private DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriorityDnsType dnsType;

    private int ttl;

    private String rawText;

    private int rRsetType;

    private String target;

    private int priority;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(
        DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority other) {
      name(other.getName());
      type(other.getType());
      dnsType(other.getDnsType());
      ttl(other.getTtl());
      rawText(other.getRawText());
      rRsetType(other.getRRsetType());
      target(other.getTarget());
      priority(other.getPriority());
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public TypeStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public DnsTypeStage type(int type) {
      this.type = type;
      return this;
    }

    @java.lang.Override
    @JsonSetter("dnsType")
    public TtlStage dnsType(
        @NotNull DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriorityDnsType dnsType) {
      this.dnsType = Objects.requireNonNull(dnsType, "dnsType must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("ttl")
    public RawTextStage ttl(int ttl) {
      this.ttl = ttl;
      return this;
    }

    @java.lang.Override
    @JsonSetter("rawText")
    public RRsetTypeStage rawText(@NotNull String rawText) {
      this.rawText = Objects.requireNonNull(rawText, "rawText must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("rRsetType")
    public TargetStage rRsetType(int rRsetType) {
      this.rRsetType = rRsetType;
      return this;
    }

    @java.lang.Override
    @JsonSetter("target")
    public PriorityStage target(@NotNull String target) {
      this.target = Objects.requireNonNull(target, "target must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("priority")
    public _FinalStage priority(int priority) {
      this.priority = priority;
      return this;
    }

    @java.lang.Override
    public DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority build() {
      return new DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriority(name, type, dnsType, ttl, rawText, rRsetType, target, priority, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
