/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class DomainReputationResponseRiskCategorySeverity {
  public static final DomainReputationResponseRiskCategorySeverity MEDIUM = new DomainReputationResponseRiskCategorySeverity(Value.MEDIUM, "medium");

  public static final DomainReputationResponseRiskCategorySeverity LOW = new DomainReputationResponseRiskCategorySeverity(Value.LOW, "low");

  public static final DomainReputationResponseRiskCategorySeverity HIGH = new DomainReputationResponseRiskCategorySeverity(Value.HIGH, "high");

  public static final DomainReputationResponseRiskCategorySeverity NONE = new DomainReputationResponseRiskCategorySeverity(Value.NONE, "none");

  private final Value value;

  private final String string;

  DomainReputationResponseRiskCategorySeverity(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof DomainReputationResponseRiskCategorySeverity && this.string.equals(((DomainReputationResponseRiskCategorySeverity) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case MEDIUM:
        return visitor.visitMedium();
      case LOW:
        return visitor.visitLow();
      case HIGH:
        return visitor.visitHigh();
      case NONE:
        return visitor.visitNone();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static DomainReputationResponseRiskCategorySeverity valueOf(String value) {
    switch (value) {
      case "medium":
        return MEDIUM;
      case "low":
        return LOW;
      case "high":
        return HIGH;
      case "none":
        return NONE;
      default:
        return new DomainReputationResponseRiskCategorySeverity(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    NONE,

    LOW,

    MEDIUM,

    HIGH,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitNone();

    T visitLow();

    T visitMedium();

    T visitHigh();

    T visitUnknown(String unknownType);
  }
}
