/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemOneDnsType {
  public static final DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemOneDnsType CNAME = new DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemOneDnsType(Value.CNAME, "CNAME");

  private final Value value;

  private final String string;

  DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemOneDnsType(Value value,
      String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemOneDnsType && this.string.equals(((DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemOneDnsType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CNAME:
        return visitor.visitCname();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemOneDnsType valueOf(
      String value) {
    switch (value) {
      case "CNAME":
        return CNAME;
      default:
        return new DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemOneDnsType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CNAME,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitCname();

    T visitUnknown(String unknownType);
  }
}
