/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.apifreaks.sdk.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DomainReputationResponseRiskCategorySourcesItem.Builder.class
)
public final class DomainReputationResponseRiskCategorySourcesItem {
  private final String source;

  private final String indicator;

  private final String threatType;

  private final float confidence;

  private final String firstSeen;

  private final String lastSeen;

  private final Map<String, Object> additionalProperties;

  private DomainReputationResponseRiskCategorySourcesItem(String source, String indicator,
      String threatType, float confidence, String firstSeen, String lastSeen,
      Map<String, Object> additionalProperties) {
    this.source = source;
    this.indicator = indicator;
    this.threatType = threatType;
    this.confidence = confidence;
    this.firstSeen = firstSeen;
    this.lastSeen = lastSeen;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Name of the threat intelligence source (e.g. Spamhaus).
   */
  @JsonProperty("source")
  public String getSource() {
    return source;
  }

  /**
   * @return Indicator matched by this source.
   */
  @JsonProperty("indicator")
  public String getIndicator() {
    return indicator;
  }

  /**
   * @return Threat type reported by this source.
   */
  @JsonProperty("threat_type")
  public String getThreatType() {
    return threatType;
  }

  /**
   * @return Confidence score from this source (0-1).
   */
  @JsonProperty("confidence")
  public float getConfidence() {
    return confidence;
  }

  /**
   * @return First time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).
   */
  @JsonProperty("first_seen")
  public String getFirstSeen() {
    return firstSeen;
  }

  /**
   * @return Last time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).
   */
  @JsonProperty("last_seen")
  public String getLastSeen() {
    return lastSeen;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DomainReputationResponseRiskCategorySourcesItem && equalTo((DomainReputationResponseRiskCategorySourcesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DomainReputationResponseRiskCategorySourcesItem other) {
    return source.equals(other.source) && indicator.equals(other.indicator) && threatType.equals(other.threatType) && confidence == other.confidence && firstSeen.equals(other.firstSeen) && lastSeen.equals(other.lastSeen);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.source, this.indicator, this.threatType, this.confidence, this.firstSeen, this.lastSeen);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SourceStage builder() {
    return new Builder();
  }

  public interface SourceStage {
    /**
     * <p>Name of the threat intelligence source (e.g. Spamhaus).</p>
     */
    IndicatorStage source(@NotNull String source);

    Builder from(DomainReputationResponseRiskCategorySourcesItem other);
  }

  public interface IndicatorStage {
    /**
     * <p>Indicator matched by this source.</p>
     */
    ThreatTypeStage indicator(@NotNull String indicator);
  }

  public interface ThreatTypeStage {
    /**
     * <p>Threat type reported by this source.</p>
     */
    ConfidenceStage threatType(@NotNull String threatType);
  }

  public interface ConfidenceStage {
    /**
     * <p>Confidence score from this source (0-1).</p>
     */
    FirstSeenStage confidence(float confidence);
  }

  public interface FirstSeenStage {
    /**
     * <p>First time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).</p>
     */
    LastSeenStage firstSeen(@NotNull String firstSeen);
  }

  public interface LastSeenStage {
    /**
     * <p>Last time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).</p>
     */
    _FinalStage lastSeen(@NotNull String lastSeen);
  }

  public interface _FinalStage {
    DomainReputationResponseRiskCategorySourcesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SourceStage, IndicatorStage, ThreatTypeStage, ConfidenceStage, FirstSeenStage, LastSeenStage, _FinalStage {
    private String source;

    private String indicator;

    private String threatType;

    private float confidence;

    private String firstSeen;

    private String lastSeen;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DomainReputationResponseRiskCategorySourcesItem other) {
      source(other.getSource());
      indicator(other.getIndicator());
      threatType(other.getThreatType());
      confidence(other.getConfidence());
      firstSeen(other.getFirstSeen());
      lastSeen(other.getLastSeen());
      return this;
    }

    /**
     * <p>Name of the threat intelligence source (e.g. Spamhaus).</p>
     * <p>Name of the threat intelligence source (e.g. Spamhaus).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("source")
    public IndicatorStage source(@NotNull String source) {
      this.source = Objects.requireNonNull(source, "source must not be null");
      return this;
    }

    /**
     * <p>Indicator matched by this source.</p>
     * <p>Indicator matched by this source.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("indicator")
    public ThreatTypeStage indicator(@NotNull String indicator) {
      this.indicator = Objects.requireNonNull(indicator, "indicator must not be null");
      return this;
    }

    /**
     * <p>Threat type reported by this source.</p>
     * <p>Threat type reported by this source.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("threat_type")
    public ConfidenceStage threatType(@NotNull String threatType) {
      this.threatType = Objects.requireNonNull(threatType, "threatType must not be null");
      return this;
    }

    /**
     * <p>Confidence score from this source (0-1).</p>
     * <p>Confidence score from this source (0-1).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("confidence")
    public FirstSeenStage confidence(float confidence) {
      this.confidence = confidence;
      return this;
    }

    /**
     * <p>First time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).</p>
     * <p>First time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("first_seen")
    public LastSeenStage firstSeen(@NotNull String firstSeen) {
      this.firstSeen = Objects.requireNonNull(firstSeen, "firstSeen must not be null");
      return this;
    }

    /**
     * <p>Last time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).</p>
     * <p>Last time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("last_seen")
    public _FinalStage lastSeen(@NotNull String lastSeen) {
      this.lastSeen = Objects.requireNonNull(lastSeen, "lastSeen must not be null");
      return this;
    }

    @java.lang.Override
    public DomainReputationResponseRiskCategorySourcesItem build() {
      return new DomainReputationResponseRiskCategorySourcesItem(source, indicator, threatType, confidence, firstSeen, lastSeen, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
