/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class FloodForecastRequestPrecision {
  public static final FloodForecastRequestPrecision DAILY = new FloodForecastRequestPrecision(Value.DAILY, "daily");

  private final Value value;

  private final String string;

  FloodForecastRequestPrecision(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof FloodForecastRequestPrecision && this.string.equals(((FloodForecastRequestPrecision) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case DAILY:
        return visitor.visitDaily();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static FloodForecastRequestPrecision valueOf(String value) {
    switch (value) {
      case "daily":
        return DAILY;
      default:
        return new FloodForecastRequestPrecision(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    DAILY,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitDaily();

    T visitUnknown(String unknownType);
  }
}
