/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.apifreaks.sdk.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GeolocationLookupV2ResponseAsn.Builder.class
)
public final class GeolocationLookupV2ResponseAsn {
  private final Optional<String> asNumber;

  private final Optional<String> organization;

  private final Optional<String> country;

  private final Optional<String> type;

  private final Optional<String> domain;

  private final Optional<String> dateAllocated;

  private final Optional<String> rir;

  private final Map<String, Object> additionalProperties;

  private GeolocationLookupV2ResponseAsn(Optional<String> asNumber, Optional<String> organization,
      Optional<String> country, Optional<String> type, Optional<String> domain,
      Optional<String> dateAllocated, Optional<String> rir,
      Map<String, Object> additionalProperties) {
    this.asNumber = asNumber;
    this.organization = organization;
    this.country = country;
    this.type = type;
    this.domain = domain;
    this.dateAllocated = dateAllocated;
    this.rir = rir;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return ASN identifier in AS&lt;number&gt; format associated with the IP's network.
   */
  @JsonProperty("as_number")
  public Optional<String> getAsNumber() {
    return asNumber;
  }

  /**
   * @return ASN operator name.
   */
  @JsonProperty("organization")
  public Optional<String> getOrganization() {
    return organization;
  }

  /**
   * @return ASN registration country as ISO 3166-1 alpha-2.
   */
  @JsonProperty("country")
  public Optional<String> getCountry() {
    return country;
  }

  /**
   * @return ASN category (ISP, HOSTING, BUSINESS, etc.).
   */
  @JsonProperty("type")
  public Optional<String> getType() {
    return type;
  }

  /**
   * @return ASN operator domain name.
   */
  @JsonProperty("domain")
  public Optional<String> getDomain() {
    return domain;
  }

  /**
   * @return ASN allocation date in YYYY-MM-DD format.
   */
  @JsonProperty("date_allocated")
  public Optional<String> getDateAllocated() {
    return dateAllocated;
  }

  /**
   * @return Regional Internet Registry that allocated the ASN.
   */
  @JsonProperty("rir")
  public Optional<String> getRir() {
    return rir;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GeolocationLookupV2ResponseAsn && equalTo((GeolocationLookupV2ResponseAsn) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GeolocationLookupV2ResponseAsn other) {
    return asNumber.equals(other.asNumber) && organization.equals(other.organization) && country.equals(other.country) && type.equals(other.type) && domain.equals(other.domain) && dateAllocated.equals(other.dateAllocated) && rir.equals(other.rir);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.asNumber, this.organization, this.country, this.type, this.domain, this.dateAllocated, this.rir);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> asNumber = Optional.empty();

    private Optional<String> organization = Optional.empty();

    private Optional<String> country = Optional.empty();

    private Optional<String> type = Optional.empty();

    private Optional<String> domain = Optional.empty();

    private Optional<String> dateAllocated = Optional.empty();

    private Optional<String> rir = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(GeolocationLookupV2ResponseAsn other) {
      asNumber(other.getAsNumber());
      organization(other.getOrganization());
      country(other.getCountry());
      type(other.getType());
      domain(other.getDomain());
      dateAllocated(other.getDateAllocated());
      rir(other.getRir());
      return this;
    }

    /**
     * <p>ASN identifier in AS&lt;number&gt; format associated with the IP's network.</p>
     */
    @JsonSetter(
        value = "as_number",
        nulls = Nulls.SKIP
    )
    public Builder asNumber(Optional<String> asNumber) {
      this.asNumber = asNumber;
      return this;
    }

    public Builder asNumber(String asNumber) {
      this.asNumber = Optional.ofNullable(asNumber);
      return this;
    }

    /**
     * <p>ASN operator name.</p>
     */
    @JsonSetter(
        value = "organization",
        nulls = Nulls.SKIP
    )
    public Builder organization(Optional<String> organization) {
      this.organization = organization;
      return this;
    }

    public Builder organization(String organization) {
      this.organization = Optional.ofNullable(organization);
      return this;
    }

    /**
     * <p>ASN registration country as ISO 3166-1 alpha-2.</p>
     */
    @JsonSetter(
        value = "country",
        nulls = Nulls.SKIP
    )
    public Builder country(Optional<String> country) {
      this.country = country;
      return this;
    }

    public Builder country(String country) {
      this.country = Optional.ofNullable(country);
      return this;
    }

    /**
     * <p>ASN category (ISP, HOSTING, BUSINESS, etc.).</p>
     */
    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<String> type) {
      this.type = type;
      return this;
    }

    public Builder type(String type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * <p>ASN operator domain name.</p>
     */
    @JsonSetter(
        value = "domain",
        nulls = Nulls.SKIP
    )
    public Builder domain(Optional<String> domain) {
      this.domain = domain;
      return this;
    }

    public Builder domain(String domain) {
      this.domain = Optional.ofNullable(domain);
      return this;
    }

    /**
     * <p>ASN allocation date in YYYY-MM-DD format.</p>
     */
    @JsonSetter(
        value = "date_allocated",
        nulls = Nulls.SKIP
    )
    public Builder dateAllocated(Optional<String> dateAllocated) {
      this.dateAllocated = dateAllocated;
      return this;
    }

    public Builder dateAllocated(String dateAllocated) {
      this.dateAllocated = Optional.ofNullable(dateAllocated);
      return this;
    }

    /**
     * <p>Regional Internet Registry that allocated the ASN.</p>
     */
    @JsonSetter(
        value = "rir",
        nulls = Nulls.SKIP
    )
    public Builder rir(Optional<String> rir) {
      this.rir = rir;
      return this;
    }

    public Builder rir(String rir) {
      this.rir = Optional.ofNullable(rir);
      return this;
    }

    public GeolocationLookupV2ResponseAsn build() {
      return new GeolocationLookupV2ResponseAsn(asNumber, organization, country, type, domain, dateAllocated, rir, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
