/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GetCountriesResponseCountriesItem.Builder.class
)
public final class GetCountriesResponseCountriesItem {
  private final String name;

  private final String isoAlpha2;

  private final String isoAlpha3;

  private final int isoNumeric;

  private final String capital;

  private final String region;

  private final String subregion;

  private final Map<String, Object> additionalProperties;

  private GetCountriesResponseCountriesItem(String name, String isoAlpha2, String isoAlpha3,
      int isoNumeric, String capital, String region, String subregion,
      Map<String, Object> additionalProperties) {
    this.name = name;
    this.isoAlpha2 = isoAlpha2;
    this.isoAlpha3 = isoAlpha3;
    this.isoNumeric = isoNumeric;
    this.capital = capital;
    this.region = region;
    this.subregion = subregion;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("iso_alpha_2")
  public String getIsoAlpha2() {
    return isoAlpha2;
  }

  @JsonProperty("iso_alpha_3")
  public String getIsoAlpha3() {
    return isoAlpha3;
  }

  @JsonProperty("iso_numeric")
  public int getIsoNumeric() {
    return isoNumeric;
  }

  @JsonProperty("capital")
  public String getCapital() {
    return capital;
  }

  @JsonProperty("region")
  public String getRegion() {
    return region;
  }

  @JsonProperty("subregion")
  public String getSubregion() {
    return subregion;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GetCountriesResponseCountriesItem && equalTo((GetCountriesResponseCountriesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GetCountriesResponseCountriesItem other) {
    return name.equals(other.name) && isoAlpha2.equals(other.isoAlpha2) && isoAlpha3.equals(other.isoAlpha3) && isoNumeric == other.isoNumeric && capital.equals(other.capital) && region.equals(other.region) && subregion.equals(other.subregion);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.name, this.isoAlpha2, this.isoAlpha3, this.isoNumeric, this.capital, this.region, this.subregion);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    IsoAlpha2Stage name(@NotNull String name);

    Builder from(GetCountriesResponseCountriesItem other);
  }

  public interface IsoAlpha2Stage {
    IsoAlpha3Stage isoAlpha2(@NotNull String isoAlpha2);
  }

  public interface IsoAlpha3Stage {
    IsoNumericStage isoAlpha3(@NotNull String isoAlpha3);
  }

  public interface IsoNumericStage {
    CapitalStage isoNumeric(int isoNumeric);
  }

  public interface CapitalStage {
    RegionStage capital(@NotNull String capital);
  }

  public interface RegionStage {
    SubregionStage region(@NotNull String region);
  }

  public interface SubregionStage {
    _FinalStage subregion(@NotNull String subregion);
  }

  public interface _FinalStage {
    GetCountriesResponseCountriesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, IsoAlpha2Stage, IsoAlpha3Stage, IsoNumericStage, CapitalStage, RegionStage, SubregionStage, _FinalStage {
    private String name;

    private String isoAlpha2;

    private String isoAlpha3;

    private int isoNumeric;

    private String capital;

    private String region;

    private String subregion;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GetCountriesResponseCountriesItem other) {
      name(other.getName());
      isoAlpha2(other.getIsoAlpha2());
      isoAlpha3(other.getIsoAlpha3());
      isoNumeric(other.getIsoNumeric());
      capital(other.getCapital());
      region(other.getRegion());
      subregion(other.getSubregion());
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public IsoAlpha2Stage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("iso_alpha_2")
    public IsoAlpha3Stage isoAlpha2(@NotNull String isoAlpha2) {
      this.isoAlpha2 = Objects.requireNonNull(isoAlpha2, "isoAlpha2 must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("iso_alpha_3")
    public IsoNumericStage isoAlpha3(@NotNull String isoAlpha3) {
      this.isoAlpha3 = Objects.requireNonNull(isoAlpha3, "isoAlpha3 must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("iso_numeric")
    public CapitalStage isoNumeric(int isoNumeric) {
      this.isoNumeric = isoNumeric;
      return this;
    }

    @java.lang.Override
    @JsonSetter("capital")
    public RegionStage capital(@NotNull String capital) {
      this.capital = Objects.requireNonNull(capital, "capital must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("region")
    public SubregionStage region(@NotNull String region) {
      this.region = Objects.requireNonNull(region, "region must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("subregion")
    public _FinalStage subregion(@NotNull String subregion) {
      this.subregion = Objects.requireNonNull(subregion, "subregion must not be null");
      return this;
    }

    @java.lang.Override
    public GetCountriesResponseCountriesItem build() {
      return new GetCountriesResponseCountriesItem(name, isoAlpha2, isoAlpha3, isoNumeric, capital, region, subregion, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
