/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class GetFlagsRequestType {
  public static final GetFlagsRequestType COUNTRY = new GetFlagsRequestType(Value.COUNTRY, "country");

  public static final GetFlagsRequestType ORGANIZATION = new GetFlagsRequestType(Value.ORGANIZATION, "organization");

  private final Value value;

  private final String string;

  GetFlagsRequestType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof GetFlagsRequestType && this.string.equals(((GetFlagsRequestType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case COUNTRY:
        return visitor.visitCountry();
      case ORGANIZATION:
        return visitor.visitOrganization();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static GetFlagsRequestType valueOf(String value) {
    switch (value) {
      case "country":
        return COUNTRY;
      case "organization":
        return ORGANIZATION;
      default:
        return new GetFlagsRequestType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    COUNTRY,

    ORGANIZATION,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitCountry();

    T visitOrganization();

    T visitUnknown(String unknownType);
  }
}
