/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = IpSecurityLookupResponseSecurity.Builder.class
)
public final class IpSecurityLookupResponseSecurity {
  private final Optional<Double> threatScore;

  private final Optional<Boolean> isTor;

  private final Optional<Boolean> isProxy;

  private final Optional<List<String>> proxyProviderNames;

  private final Optional<Double> proxyConfidenceScore;

  private final Optional<String> proxyLastSeen;

  private final Optional<Boolean> isResidentialProxy;

  private final Optional<Boolean> isVpn;

  private final Optional<List<String>> vpnProviderNames;

  private final Optional<Double> vpnConfidenceScore;

  private final Optional<String> vpnLastSeen;

  private final Optional<Boolean> isRelay;

  private final Optional<String> relayProviderName;

  private final Optional<Boolean> isAnonymous;

  private final Optional<Boolean> isKnownAttacker;

  private final Optional<Boolean> isBot;

  private final Optional<Boolean> isSpam;

  private final Optional<Boolean> isCloudProvider;

  private final Optional<String> cloudProviderName;

  private final Map<String, Object> additionalProperties;

  private IpSecurityLookupResponseSecurity(Optional<Double> threatScore, Optional<Boolean> isTor,
      Optional<Boolean> isProxy, Optional<List<String>> proxyProviderNames,
      Optional<Double> proxyConfidenceScore, Optional<String> proxyLastSeen,
      Optional<Boolean> isResidentialProxy, Optional<Boolean> isVpn,
      Optional<List<String>> vpnProviderNames, Optional<Double> vpnConfidenceScore,
      Optional<String> vpnLastSeen, Optional<Boolean> isRelay, Optional<String> relayProviderName,
      Optional<Boolean> isAnonymous, Optional<Boolean> isKnownAttacker, Optional<Boolean> isBot,
      Optional<Boolean> isSpam, Optional<Boolean> isCloudProvider,
      Optional<String> cloudProviderName, Map<String, Object> additionalProperties) {
    this.threatScore = threatScore;
    this.isTor = isTor;
    this.isProxy = isProxy;
    this.proxyProviderNames = proxyProviderNames;
    this.proxyConfidenceScore = proxyConfidenceScore;
    this.proxyLastSeen = proxyLastSeen;
    this.isResidentialProxy = isResidentialProxy;
    this.isVpn = isVpn;
    this.vpnProviderNames = vpnProviderNames;
    this.vpnConfidenceScore = vpnConfidenceScore;
    this.vpnLastSeen = vpnLastSeen;
    this.isRelay = isRelay;
    this.relayProviderName = relayProviderName;
    this.isAnonymous = isAnonymous;
    this.isKnownAttacker = isKnownAttacker;
    this.isBot = isBot;
    this.isSpam = isSpam;
    this.isCloudProvider = isCloudProvider;
    this.cloudProviderName = cloudProviderName;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("threat_score")
  public Optional<Double> getThreatScore() {
    return threatScore;
  }

  @JsonProperty("is_tor")
  public Optional<Boolean> getIsTor() {
    return isTor;
  }

  @JsonProperty("is_proxy")
  public Optional<Boolean> getIsProxy() {
    return isProxy;
  }

  @JsonProperty("proxy_provider_names")
  public Optional<List<String>> getProxyProviderNames() {
    return proxyProviderNames;
  }

  @JsonProperty("proxy_confidence_score")
  public Optional<Double> getProxyConfidenceScore() {
    return proxyConfidenceScore;
  }

  @JsonProperty("proxy_last_seen")
  public Optional<String> getProxyLastSeen() {
    return proxyLastSeen;
  }

  @JsonProperty("is_residential_proxy")
  public Optional<Boolean> getIsResidentialProxy() {
    return isResidentialProxy;
  }

  @JsonProperty("is_vpn")
  public Optional<Boolean> getIsVpn() {
    return isVpn;
  }

  @JsonProperty("vpn_provider_names")
  public Optional<List<String>> getVpnProviderNames() {
    return vpnProviderNames;
  }

  @JsonProperty("vpn_confidence_score")
  public Optional<Double> getVpnConfidenceScore() {
    return vpnConfidenceScore;
  }

  @JsonProperty("vpn_last_seen")
  public Optional<String> getVpnLastSeen() {
    return vpnLastSeen;
  }

  @JsonProperty("is_relay")
  public Optional<Boolean> getIsRelay() {
    return isRelay;
  }

  @JsonProperty("relay_provider_name")
  public Optional<String> getRelayProviderName() {
    return relayProviderName;
  }

  @JsonProperty("is_anonymous")
  public Optional<Boolean> getIsAnonymous() {
    return isAnonymous;
  }

  @JsonProperty("is_known_attacker")
  public Optional<Boolean> getIsKnownAttacker() {
    return isKnownAttacker;
  }

  @JsonProperty("is_bot")
  public Optional<Boolean> getIsBot() {
    return isBot;
  }

  @JsonProperty("is_spam")
  public Optional<Boolean> getIsSpam() {
    return isSpam;
  }

  @JsonProperty("is_cloud_provider")
  public Optional<Boolean> getIsCloudProvider() {
    return isCloudProvider;
  }

  @JsonProperty("cloud_provider_name")
  public Optional<String> getCloudProviderName() {
    return cloudProviderName;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof IpSecurityLookupResponseSecurity && equalTo((IpSecurityLookupResponseSecurity) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(IpSecurityLookupResponseSecurity other) {
    return threatScore.equals(other.threatScore) && isTor.equals(other.isTor) && isProxy.equals(other.isProxy) && proxyProviderNames.equals(other.proxyProviderNames) && proxyConfidenceScore.equals(other.proxyConfidenceScore) && proxyLastSeen.equals(other.proxyLastSeen) && isResidentialProxy.equals(other.isResidentialProxy) && isVpn.equals(other.isVpn) && vpnProviderNames.equals(other.vpnProviderNames) && vpnConfidenceScore.equals(other.vpnConfidenceScore) && vpnLastSeen.equals(other.vpnLastSeen) && isRelay.equals(other.isRelay) && relayProviderName.equals(other.relayProviderName) && isAnonymous.equals(other.isAnonymous) && isKnownAttacker.equals(other.isKnownAttacker) && isBot.equals(other.isBot) && isSpam.equals(other.isSpam) && isCloudProvider.equals(other.isCloudProvider) && cloudProviderName.equals(other.cloudProviderName);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.threatScore, this.isTor, this.isProxy, this.proxyProviderNames, this.proxyConfidenceScore, this.proxyLastSeen, this.isResidentialProxy, this.isVpn, this.vpnProviderNames, this.vpnConfidenceScore, this.vpnLastSeen, this.isRelay, this.relayProviderName, this.isAnonymous, this.isKnownAttacker, this.isBot, this.isSpam, this.isCloudProvider, this.cloudProviderName);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Double> threatScore = Optional.empty();

    private Optional<Boolean> isTor = Optional.empty();

    private Optional<Boolean> isProxy = Optional.empty();

    private Optional<List<String>> proxyProviderNames = Optional.empty();

    private Optional<Double> proxyConfidenceScore = Optional.empty();

    private Optional<String> proxyLastSeen = Optional.empty();

    private Optional<Boolean> isResidentialProxy = Optional.empty();

    private Optional<Boolean> isVpn = Optional.empty();

    private Optional<List<String>> vpnProviderNames = Optional.empty();

    private Optional<Double> vpnConfidenceScore = Optional.empty();

    private Optional<String> vpnLastSeen = Optional.empty();

    private Optional<Boolean> isRelay = Optional.empty();

    private Optional<String> relayProviderName = Optional.empty();

    private Optional<Boolean> isAnonymous = Optional.empty();

    private Optional<Boolean> isKnownAttacker = Optional.empty();

    private Optional<Boolean> isBot = Optional.empty();

    private Optional<Boolean> isSpam = Optional.empty();

    private Optional<Boolean> isCloudProvider = Optional.empty();

    private Optional<String> cloudProviderName = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(IpSecurityLookupResponseSecurity other) {
      threatScore(other.getThreatScore());
      isTor(other.getIsTor());
      isProxy(other.getIsProxy());
      proxyProviderNames(other.getProxyProviderNames());
      proxyConfidenceScore(other.getProxyConfidenceScore());
      proxyLastSeen(other.getProxyLastSeen());
      isResidentialProxy(other.getIsResidentialProxy());
      isVpn(other.getIsVpn());
      vpnProviderNames(other.getVpnProviderNames());
      vpnConfidenceScore(other.getVpnConfidenceScore());
      vpnLastSeen(other.getVpnLastSeen());
      isRelay(other.getIsRelay());
      relayProviderName(other.getRelayProviderName());
      isAnonymous(other.getIsAnonymous());
      isKnownAttacker(other.getIsKnownAttacker());
      isBot(other.getIsBot());
      isSpam(other.getIsSpam());
      isCloudProvider(other.getIsCloudProvider());
      cloudProviderName(other.getCloudProviderName());
      return this;
    }

    @JsonSetter(
        value = "threat_score",
        nulls = Nulls.SKIP
    )
    public Builder threatScore(Optional<Double> threatScore) {
      this.threatScore = threatScore;
      return this;
    }

    public Builder threatScore(Double threatScore) {
      this.threatScore = Optional.ofNullable(threatScore);
      return this;
    }

    @JsonSetter(
        value = "is_tor",
        nulls = Nulls.SKIP
    )
    public Builder isTor(Optional<Boolean> isTor) {
      this.isTor = isTor;
      return this;
    }

    public Builder isTor(Boolean isTor) {
      this.isTor = Optional.ofNullable(isTor);
      return this;
    }

    @JsonSetter(
        value = "is_proxy",
        nulls = Nulls.SKIP
    )
    public Builder isProxy(Optional<Boolean> isProxy) {
      this.isProxy = isProxy;
      return this;
    }

    public Builder isProxy(Boolean isProxy) {
      this.isProxy = Optional.ofNullable(isProxy);
      return this;
    }

    @JsonSetter(
        value = "proxy_provider_names",
        nulls = Nulls.SKIP
    )
    public Builder proxyProviderNames(Optional<List<String>> proxyProviderNames) {
      this.proxyProviderNames = proxyProviderNames;
      return this;
    }

    public Builder proxyProviderNames(List<String> proxyProviderNames) {
      this.proxyProviderNames = Optional.ofNullable(proxyProviderNames);
      return this;
    }

    @JsonSetter(
        value = "proxy_confidence_score",
        nulls = Nulls.SKIP
    )
    public Builder proxyConfidenceScore(Optional<Double> proxyConfidenceScore) {
      this.proxyConfidenceScore = proxyConfidenceScore;
      return this;
    }

    public Builder proxyConfidenceScore(Double proxyConfidenceScore) {
      this.proxyConfidenceScore = Optional.ofNullable(proxyConfidenceScore);
      return this;
    }

    @JsonSetter(
        value = "proxy_last_seen",
        nulls = Nulls.SKIP
    )
    public Builder proxyLastSeen(Optional<String> proxyLastSeen) {
      this.proxyLastSeen = proxyLastSeen;
      return this;
    }

    public Builder proxyLastSeen(String proxyLastSeen) {
      this.proxyLastSeen = Optional.ofNullable(proxyLastSeen);
      return this;
    }

    @JsonSetter(
        value = "is_residential_proxy",
        nulls = Nulls.SKIP
    )
    public Builder isResidentialProxy(Optional<Boolean> isResidentialProxy) {
      this.isResidentialProxy = isResidentialProxy;
      return this;
    }

    public Builder isResidentialProxy(Boolean isResidentialProxy) {
      this.isResidentialProxy = Optional.ofNullable(isResidentialProxy);
      return this;
    }

    @JsonSetter(
        value = "is_vpn",
        nulls = Nulls.SKIP
    )
    public Builder isVpn(Optional<Boolean> isVpn) {
      this.isVpn = isVpn;
      return this;
    }

    public Builder isVpn(Boolean isVpn) {
      this.isVpn = Optional.ofNullable(isVpn);
      return this;
    }

    @JsonSetter(
        value = "vpn_provider_names",
        nulls = Nulls.SKIP
    )
    public Builder vpnProviderNames(Optional<List<String>> vpnProviderNames) {
      this.vpnProviderNames = vpnProviderNames;
      return this;
    }

    public Builder vpnProviderNames(List<String> vpnProviderNames) {
      this.vpnProviderNames = Optional.ofNullable(vpnProviderNames);
      return this;
    }

    @JsonSetter(
        value = "vpn_confidence_score",
        nulls = Nulls.SKIP
    )
    public Builder vpnConfidenceScore(Optional<Double> vpnConfidenceScore) {
      this.vpnConfidenceScore = vpnConfidenceScore;
      return this;
    }

    public Builder vpnConfidenceScore(Double vpnConfidenceScore) {
      this.vpnConfidenceScore = Optional.ofNullable(vpnConfidenceScore);
      return this;
    }

    @JsonSetter(
        value = "vpn_last_seen",
        nulls = Nulls.SKIP
    )
    public Builder vpnLastSeen(Optional<String> vpnLastSeen) {
      this.vpnLastSeen = vpnLastSeen;
      return this;
    }

    public Builder vpnLastSeen(String vpnLastSeen) {
      this.vpnLastSeen = Optional.ofNullable(vpnLastSeen);
      return this;
    }

    @JsonSetter(
        value = "is_relay",
        nulls = Nulls.SKIP
    )
    public Builder isRelay(Optional<Boolean> isRelay) {
      this.isRelay = isRelay;
      return this;
    }

    public Builder isRelay(Boolean isRelay) {
      this.isRelay = Optional.ofNullable(isRelay);
      return this;
    }

    @JsonSetter(
        value = "relay_provider_name",
        nulls = Nulls.SKIP
    )
    public Builder relayProviderName(Optional<String> relayProviderName) {
      this.relayProviderName = relayProviderName;
      return this;
    }

    public Builder relayProviderName(String relayProviderName) {
      this.relayProviderName = Optional.ofNullable(relayProviderName);
      return this;
    }

    @JsonSetter(
        value = "is_anonymous",
        nulls = Nulls.SKIP
    )
    public Builder isAnonymous(Optional<Boolean> isAnonymous) {
      this.isAnonymous = isAnonymous;
      return this;
    }

    public Builder isAnonymous(Boolean isAnonymous) {
      this.isAnonymous = Optional.ofNullable(isAnonymous);
      return this;
    }

    @JsonSetter(
        value = "is_known_attacker",
        nulls = Nulls.SKIP
    )
    public Builder isKnownAttacker(Optional<Boolean> isKnownAttacker) {
      this.isKnownAttacker = isKnownAttacker;
      return this;
    }

    public Builder isKnownAttacker(Boolean isKnownAttacker) {
      this.isKnownAttacker = Optional.ofNullable(isKnownAttacker);
      return this;
    }

    @JsonSetter(
        value = "is_bot",
        nulls = Nulls.SKIP
    )
    public Builder isBot(Optional<Boolean> isBot) {
      this.isBot = isBot;
      return this;
    }

    public Builder isBot(Boolean isBot) {
      this.isBot = Optional.ofNullable(isBot);
      return this;
    }

    @JsonSetter(
        value = "is_spam",
        nulls = Nulls.SKIP
    )
    public Builder isSpam(Optional<Boolean> isSpam) {
      this.isSpam = isSpam;
      return this;
    }

    public Builder isSpam(Boolean isSpam) {
      this.isSpam = Optional.ofNullable(isSpam);
      return this;
    }

    @JsonSetter(
        value = "is_cloud_provider",
        nulls = Nulls.SKIP
    )
    public Builder isCloudProvider(Optional<Boolean> isCloudProvider) {
      this.isCloudProvider = isCloudProvider;
      return this;
    }

    public Builder isCloudProvider(Boolean isCloudProvider) {
      this.isCloudProvider = Optional.ofNullable(isCloudProvider);
      return this;
    }

    @JsonSetter(
        value = "cloud_provider_name",
        nulls = Nulls.SKIP
    )
    public Builder cloudProviderName(Optional<String> cloudProviderName) {
      this.cloudProviderName = cloudProviderName;
      return this;
    }

    public Builder cloudProviderName(String cloudProviderName) {
      this.cloudProviderName = Optional.ofNullable(cloudProviderName);
      return this;
    }

    public IpSecurityLookupResponseSecurity build() {
      return new IpSecurityLookupResponseSecurity(threatScore, isTor, isProxy, proxyProviderNames, proxyConfidenceScore, proxyLastSeen, isResidentialProxy, isVpn, vpnProviderNames, vpnConfidenceScore, vpnLastSeen, isRelay, relayProviderName, isAnonymous, isKnownAttacker, isBot, isSpam, isCloudProvider, cloudProviderName, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
