/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PdfUploadResourcesRequestFormat {
  public static final PdfUploadResourcesRequestFormat XML = new PdfUploadResourcesRequestFormat(Value.XML, "xml");

  public static final PdfUploadResourcesRequestFormat JSON = new PdfUploadResourcesRequestFormat(Value.JSON, "json");

  private final Value value;

  private final String string;

  PdfUploadResourcesRequestFormat(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PdfUploadResourcesRequestFormat && this.string.equals(((PdfUploadResourcesRequestFormat) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case XML:
        return visitor.visitXml();
      case JSON:
        return visitor.visitJson();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PdfUploadResourcesRequestFormat valueOf(String value) {
    switch (value) {
      case "xml":
        return XML;
      case "json":
        return JSON;
      default:
        return new PdfUploadResourcesRequestFormat(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    JSON,

    XML,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitJson();

    T visitXml();

    T visitUnknown(String unknownType);
  }
}
