/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PdfUploadBinaryResponse.Builder.class
)
public final class PdfUploadBinaryResponse {
  private final Optional<String> fileName;

  private final String fileId;

  private final Map<String, Object> additionalProperties;

  private PdfUploadBinaryResponse(Optional<String> fileName, String fileId,
      Map<String, Object> additionalProperties) {
    this.fileName = fileName;
    this.fileId = fileId;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The name of the uploaded file.
   */
  @JsonProperty("fileName")
  public Optional<String> getFileName() {
    return fileName;
  }

  /**
   * @return The unique identifier assigned to the uploaded file.
   */
  @JsonProperty("fileId")
  public String getFileId() {
    return fileId;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PdfUploadBinaryResponse && equalTo((PdfUploadBinaryResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PdfUploadBinaryResponse other) {
    return fileName.equals(other.fileName) && fileId.equals(other.fileId);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.fileName, this.fileId);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static FileIdStage builder() {
    return new Builder();
  }

  public interface FileIdStage {
    /**
     * <p>The unique identifier assigned to the uploaded file.</p>
     */
    _FinalStage fileId(@NotNull String fileId);

    Builder from(PdfUploadBinaryResponse other);
  }

  public interface _FinalStage {
    PdfUploadBinaryResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The name of the uploaded file.</p>
     */
    _FinalStage fileName(Optional<String> fileName);

    _FinalStage fileName(String fileName);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements FileIdStage, _FinalStage {
    private String fileId;

    private Optional<String> fileName = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(PdfUploadBinaryResponse other) {
      fileName(other.getFileName());
      fileId(other.getFileId());
      return this;
    }

    /**
     * <p>The unique identifier assigned to the uploaded file.</p>
     * <p>The unique identifier assigned to the uploaded file.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("fileId")
    public _FinalStage fileId(@NotNull String fileId) {
      this.fileId = Objects.requireNonNull(fileId, "fileId must not be null");
      return this;
    }

    /**
     * <p>The name of the uploaded file.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage fileName(String fileName) {
      this.fileName = Optional.ofNullable(fileName);
      return this;
    }

    /**
     * <p>The name of the uploaded file.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "fileName",
        nulls = Nulls.SKIP
    )
    public _FinalStage fileName(Optional<String> fileName) {
      this.fileName = fileName;
      return this;
    }

    @java.lang.Override
    public PdfUploadBinaryResponse build() {
      return new PdfUploadBinaryResponse(fileName, fileId, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
