/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TimezoneLookupResponseLoCodeDetails.Builder.class
)
public final class TimezoneLookupResponseLoCodeDetails {
  private final Optional<String> loCode;

  private final Optional<String> city;

  private final Optional<Double> longitude;

  private final Optional<Double> latitude;

  private final Optional<String> stateCode;

  private final Optional<String> countryCode;

  private final Optional<String> countryName;

  private final Optional<String> locationType;

  private final Map<String, Object> additionalProperties;

  private TimezoneLookupResponseLoCodeDetails(Optional<String> loCode, Optional<String> city,
      Optional<Double> longitude, Optional<Double> latitude, Optional<String> stateCode,
      Optional<String> countryCode, Optional<String> countryName, Optional<String> locationType,
      Map<String, Object> additionalProperties) {
    this.loCode = loCode;
    this.city = city;
    this.longitude = longitude;
    this.latitude = latitude;
    this.stateCode = stateCode;
    this.countryCode = countryCode;
    this.countryName = countryName;
    this.locationType = locationType;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("lo_code")
  public Optional<String> getLoCode() {
    return loCode;
  }

  @JsonProperty("city")
  public Optional<String> getCity() {
    return city;
  }

  @JsonProperty("longitude")
  public Optional<Double> getLongitude() {
    return longitude;
  }

  @JsonProperty("latitude")
  public Optional<Double> getLatitude() {
    return latitude;
  }

  @JsonProperty("state_code")
  public Optional<String> getStateCode() {
    return stateCode;
  }

  @JsonProperty("country_code")
  public Optional<String> getCountryCode() {
    return countryCode;
  }

  @JsonProperty("country_name")
  public Optional<String> getCountryName() {
    return countryName;
  }

  @JsonProperty("location_type")
  public Optional<String> getLocationType() {
    return locationType;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TimezoneLookupResponseLoCodeDetails && equalTo((TimezoneLookupResponseLoCodeDetails) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TimezoneLookupResponseLoCodeDetails other) {
    return loCode.equals(other.loCode) && city.equals(other.city) && longitude.equals(other.longitude) && latitude.equals(other.latitude) && stateCode.equals(other.stateCode) && countryCode.equals(other.countryCode) && countryName.equals(other.countryName) && locationType.equals(other.locationType);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.loCode, this.city, this.longitude, this.latitude, this.stateCode, this.countryCode, this.countryName, this.locationType);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> loCode = Optional.empty();

    private Optional<String> city = Optional.empty();

    private Optional<Double> longitude = Optional.empty();

    private Optional<Double> latitude = Optional.empty();

    private Optional<String> stateCode = Optional.empty();

    private Optional<String> countryCode = Optional.empty();

    private Optional<String> countryName = Optional.empty();

    private Optional<String> locationType = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(TimezoneLookupResponseLoCodeDetails other) {
      loCode(other.getLoCode());
      city(other.getCity());
      longitude(other.getLongitude());
      latitude(other.getLatitude());
      stateCode(other.getStateCode());
      countryCode(other.getCountryCode());
      countryName(other.getCountryName());
      locationType(other.getLocationType());
      return this;
    }

    @JsonSetter(
        value = "lo_code",
        nulls = Nulls.SKIP
    )
    public Builder loCode(Optional<String> loCode) {
      this.loCode = loCode;
      return this;
    }

    public Builder loCode(String loCode) {
      this.loCode = Optional.ofNullable(loCode);
      return this;
    }

    @JsonSetter(
        value = "city",
        nulls = Nulls.SKIP
    )
    public Builder city(Optional<String> city) {
      this.city = city;
      return this;
    }

    public Builder city(String city) {
      this.city = Optional.ofNullable(city);
      return this;
    }

    @JsonSetter(
        value = "longitude",
        nulls = Nulls.SKIP
    )
    public Builder longitude(Optional<Double> longitude) {
      this.longitude = longitude;
      return this;
    }

    public Builder longitude(Double longitude) {
      this.longitude = Optional.ofNullable(longitude);
      return this;
    }

    @JsonSetter(
        value = "latitude",
        nulls = Nulls.SKIP
    )
    public Builder latitude(Optional<Double> latitude) {
      this.latitude = latitude;
      return this;
    }

    public Builder latitude(Double latitude) {
      this.latitude = Optional.ofNullable(latitude);
      return this;
    }

    @JsonSetter(
        value = "state_code",
        nulls = Nulls.SKIP
    )
    public Builder stateCode(Optional<String> stateCode) {
      this.stateCode = stateCode;
      return this;
    }

    public Builder stateCode(String stateCode) {
      this.stateCode = Optional.ofNullable(stateCode);
      return this;
    }

    @JsonSetter(
        value = "country_code",
        nulls = Nulls.SKIP
    )
    public Builder countryCode(Optional<String> countryCode) {
      this.countryCode = countryCode;
      return this;
    }

    public Builder countryCode(String countryCode) {
      this.countryCode = Optional.ofNullable(countryCode);
      return this;
    }

    @JsonSetter(
        value = "country_name",
        nulls = Nulls.SKIP
    )
    public Builder countryName(Optional<String> countryName) {
      this.countryName = countryName;
      return this;
    }

    public Builder countryName(String countryName) {
      this.countryName = Optional.ofNullable(countryName);
      return this;
    }

    @JsonSetter(
        value = "location_type",
        nulls = Nulls.SKIP
    )
    public Builder locationType(Optional<String> locationType) {
      this.locationType = locationType;
      return this;
    }

    public Builder locationType(String locationType) {
      this.locationType = Optional.ofNullable(locationType);
      return this;
    }

    public TimezoneLookupResponseLoCodeDetails build() {
      return new TimezoneLookupResponseLoCodeDetails(loCode, city, longitude, latitude, stateCode, countryCode, countryName, locationType, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
