/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = VatValidateResponse.Builder.class
)
public final class VatValidateResponse {
  private final String countryCode;

  private final String vatNumber;

  private final String requesterCountryCode;

  private final String requesterVatNumber;

  private final OffsetDateTime requestedAt;

  private final VatValidateResponseValidation validation;

  private final VatValidateResponseCompany company;

  private final Map<String, Object> additionalProperties;

  private VatValidateResponse(String countryCode, String vatNumber,
      String requesterCountryCode, String requesterVatNumber,
      OffsetDateTime requestedAt, VatValidateResponseValidation validation,
      VatValidateResponseCompany company, Map<String, Object> additionalProperties) {
    this.countryCode = countryCode;
    this.vatNumber = vatNumber;
    this.requesterCountryCode = requesterCountryCode;
    this.requesterVatNumber = requesterVatNumber;
    this.requestedAt = requestedAt;
    this.validation = validation;
    this.company = company;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("country_code")
  public String getCountryCode() {
    return countryCode;
  }

  @JsonProperty("vat_number")
  public String getVatNumber() {
    return vatNumber;
  }

  @JsonProperty("requester_country_code")
  public String getRequesterCountryCode() {
    return requesterCountryCode;
  }

  @JsonProperty("requester_vat_number")
  public String getRequesterVatNumber() {
    return requesterVatNumber;
  }

  @JsonProperty("requested_at")
  public OffsetDateTime getRequestedAt() {
    return requestedAt;
  }

  @JsonProperty("validation")
  public VatValidateResponseValidation getValidation() {
    return validation;
  }

  @JsonProperty("company")
  public VatValidateResponseCompany getCompany() {
    return company;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof VatValidateResponse && equalTo((VatValidateResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(VatValidateResponse other) {
    return countryCode.equals(other.countryCode) && vatNumber.equals(other.vatNumber) && requesterCountryCode.equals(other.requesterCountryCode) && requesterVatNumber.equals(other.requesterVatNumber) && requestedAt.equals(other.requestedAt) && validation.equals(other.validation) && company.equals(other.company);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.countryCode, this.vatNumber, this.requesterCountryCode, this.requesterVatNumber, this.requestedAt, this.validation, this.company);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CountryCodeStage builder() {
    return new Builder();
  }

  public interface CountryCodeStage {
    VatNumberStage countryCode(@NotNull String countryCode);

    Builder from(VatValidateResponse other);
  }

  public interface VatNumberStage {
    RequesterCountryCodeStage vatNumber(@NotNull String vatNumber);
  }

  public interface RequesterCountryCodeStage {
    RequesterVatNumberStage requesterCountryCode(@NotNull String requesterCountryCode);
  }

  public interface RequesterVatNumberStage {
    RequestedAtStage requesterVatNumber(@NotNull String requesterVatNumber);
  }

  public interface RequestedAtStage {
    ValidationStage requestedAt(@NotNull OffsetDateTime requestedAt);
  }

  public interface ValidationStage {
    CompanyStage validation(@NotNull VatValidateResponseValidation validation);
  }

  public interface CompanyStage {
    _FinalStage company(@NotNull VatValidateResponseCompany company);
  }

  public interface _FinalStage {
    VatValidateResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CountryCodeStage, VatNumberStage, RequesterCountryCodeStage, RequesterVatNumberStage, RequestedAtStage, ValidationStage, CompanyStage, _FinalStage {
    private String countryCode;

    private String vatNumber;

    private String requesterCountryCode;

    private String requesterVatNumber;

    private OffsetDateTime requestedAt;

    private VatValidateResponseValidation validation;

    private VatValidateResponseCompany company;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(VatValidateResponse other) {
      countryCode(other.getCountryCode());
      vatNumber(other.getVatNumber());
      requesterCountryCode(other.getRequesterCountryCode());
      requesterVatNumber(other.getRequesterVatNumber());
      requestedAt(other.getRequestedAt());
      validation(other.getValidation());
      company(other.getCompany());
      return this;
    }

    @java.lang.Override
    @JsonSetter("country_code")
    public VatNumberStage countryCode(@NotNull String countryCode) {
      this.countryCode = Objects.requireNonNull(countryCode, "countryCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("vat_number")
    public RequesterCountryCodeStage vatNumber(@NotNull String vatNumber) {
      this.vatNumber = Objects.requireNonNull(vatNumber, "vatNumber must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("requester_country_code")
    public RequesterVatNumberStage requesterCountryCode(@NotNull String requesterCountryCode) {
      this.requesterCountryCode = Objects.requireNonNull(requesterCountryCode, "requesterCountryCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("requester_vat_number")
    public RequestedAtStage requesterVatNumber(@NotNull String requesterVatNumber) {
      this.requesterVatNumber = Objects.requireNonNull(requesterVatNumber, "requesterVatNumber must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("requested_at")
    public ValidationStage requestedAt(@NotNull OffsetDateTime requestedAt) {
      this.requestedAt = Objects.requireNonNull(requestedAt, "requestedAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("validation")
    public CompanyStage validation(@NotNull VatValidateResponseValidation validation) {
      this.validation = Objects.requireNonNull(validation, "validation must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("company")
    public _FinalStage company(@NotNull VatValidateResponseCompany company) {
      this.company = Objects.requireNonNull(company, "company must not be null");
      return this;
    }

    @java.lang.Override
    public VatValidateResponse build() {
      return new VatValidateResponse(countryCode, vatNumber, requesterCountryCode, requesterVatNumber, requestedAt, validation, company, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
