/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebScrapeRequestBodyBlockUrlInstructionsItemFillImageCaptcha.Builder.class
)
public final class WebScrapeRequestBodyBlockUrlInstructionsItemFillImageCaptcha {
  private final Optional<List<Map<String, Object>>> fillImageCaptcha;

  private final Map<String, Object> additionalProperties;

  private WebScrapeRequestBodyBlockUrlInstructionsItemFillImageCaptcha(
      Optional<List<Map<String, Object>>> fillImageCaptcha,
      Map<String, Object> additionalProperties) {
    this.fillImageCaptcha = fillImageCaptcha;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Captures and fills CAPTCHA values automatically.
   */
  @JsonProperty("fillImageCaptcha")
  public Optional<List<Map<String, Object>>> getFillImageCaptcha() {
    return fillImageCaptcha;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebScrapeRequestBodyBlockUrlInstructionsItemFillImageCaptcha && equalTo((WebScrapeRequestBodyBlockUrlInstructionsItemFillImageCaptcha) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebScrapeRequestBodyBlockUrlInstructionsItemFillImageCaptcha other) {
    return fillImageCaptcha.equals(other.fillImageCaptcha);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.fillImageCaptcha);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<List<Map<String, Object>>> fillImageCaptcha = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WebScrapeRequestBodyBlockUrlInstructionsItemFillImageCaptcha other) {
      fillImageCaptcha(other.getFillImageCaptcha());
      return this;
    }

    /**
     * <p>Captures and fills CAPTCHA values automatically.</p>
     */
    @JsonSetter(
        value = "fillImageCaptcha",
        nulls = Nulls.SKIP
    )
    public Builder fillImageCaptcha(Optional<List<Map<String, Object>>> fillImageCaptcha) {
      this.fillImageCaptcha = fillImageCaptcha;
      return this;
    }

    public Builder fillImageCaptcha(List<Map<String, Object>> fillImageCaptcha) {
      this.fillImageCaptcha = Optional.ofNullable(fillImageCaptcha);
      return this;
    }

    public WebScrapeRequestBodyBlockUrlInstructionsItemFillImageCaptcha build() {
      return new WebScrapeRequestBodyBlockUrlInstructionsItemFillImageCaptcha(fillImageCaptcha, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
