/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebScrapeRequestBodyBlockUrlInstructionsItemClick.Builder.class
)
public final class WebScrapeRequestBodyBlockUrlInstructionsItemClick {
  private final Optional<String> click;

  private final Map<String, Object> additionalProperties;

  private WebScrapeRequestBodyBlockUrlInstructionsItemClick(Optional<String> click,
      Map<String, Object> additionalProperties) {
    this.click = click;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("click")
  public Optional<String> getClick() {
    return click;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebScrapeRequestBodyBlockUrlInstructionsItemClick && equalTo((WebScrapeRequestBodyBlockUrlInstructionsItemClick) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebScrapeRequestBodyBlockUrlInstructionsItemClick other) {
    return click.equals(other.click);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.click);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> click = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WebScrapeRequestBodyBlockUrlInstructionsItemClick other) {
      click(other.getClick());
      return this;
    }

    @JsonSetter(
        value = "click",
        nulls = Nulls.SKIP
    )
    public Builder click(Optional<String> click) {
      this.click = click;
      return this;
    }

    public Builder click(String click) {
      this.click = Optional.ofNullable(click);
      return this;
    }

    public WebScrapeRequestBodyBlockUrlInstructionsItemClick build() {
      return new WebScrapeRequestBodyBlockUrlInstructionsItemClick(click, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
