/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebScrapeRequestBodyBlockUrlInstructionsItemJsExe.Builder.class
)
public final class WebScrapeRequestBodyBlockUrlInstructionsItemJsExe {
  private final Optional<String> jsExe;

  private final Map<String, Object> additionalProperties;

  private WebScrapeRequestBodyBlockUrlInstructionsItemJsExe(Optional<String> jsExe,
      Map<String, Object> additionalProperties) {
    this.jsExe = jsExe;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("jsExe")
  public Optional<String> getJsExe() {
    return jsExe;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebScrapeRequestBodyBlockUrlInstructionsItemJsExe && equalTo((WebScrapeRequestBodyBlockUrlInstructionsItemJsExe) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebScrapeRequestBodyBlockUrlInstructionsItemJsExe other) {
    return jsExe.equals(other.jsExe);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.jsExe);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> jsExe = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WebScrapeRequestBodyBlockUrlInstructionsItemJsExe other) {
      jsExe(other.getJsExe());
      return this;
    }

    @JsonSetter(
        value = "jsExe",
        nulls = Nulls.SKIP
    )
    public Builder jsExe(Optional<String> jsExe) {
      this.jsExe = jsExe;
      return this;
    }

    public Builder jsExe(String jsExe) {
      this.jsExe = Optional.ofNullable(jsExe);
      return this;
    }

    public WebScrapeRequestBodyBlockUrlInstructionsItemJsExe build() {
      return new WebScrapeRequestBodyBlockUrlInstructionsItemJsExe(jsExe, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
