/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebScrapeRequestBodyBlockUrlInstructionsItemResolveAudioCaptcha.Builder.class
)
public final class WebScrapeRequestBodyBlockUrlInstructionsItemResolveAudioCaptcha {
  private final Optional<Map<String, Object>> resolveAudioCaptcha;

  private final Map<String, Object> additionalProperties;

  private WebScrapeRequestBodyBlockUrlInstructionsItemResolveAudioCaptcha(
      Optional<Map<String, Object>> resolveAudioCaptcha, Map<String, Object> additionalProperties) {
    this.resolveAudioCaptcha = resolveAudioCaptcha;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Solves audio CAPTCHA challenges.
   */
  @JsonProperty("resolveAudioCaptcha")
  public Optional<Map<String, Object>> getResolveAudioCaptcha() {
    return resolveAudioCaptcha;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebScrapeRequestBodyBlockUrlInstructionsItemResolveAudioCaptcha && equalTo((WebScrapeRequestBodyBlockUrlInstructionsItemResolveAudioCaptcha) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebScrapeRequestBodyBlockUrlInstructionsItemResolveAudioCaptcha other) {
    return resolveAudioCaptcha.equals(other.resolveAudioCaptcha);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.resolveAudioCaptcha);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Map<String, Object>> resolveAudioCaptcha = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WebScrapeRequestBodyBlockUrlInstructionsItemResolveAudioCaptcha other) {
      resolveAudioCaptcha(other.getResolveAudioCaptcha());
      return this;
    }

    /**
     * <p>Solves audio CAPTCHA challenges.</p>
     */
    @JsonSetter(
        value = "resolveAudioCaptcha",
        nulls = Nulls.SKIP
    )
    public Builder resolveAudioCaptcha(Optional<Map<String, Object>> resolveAudioCaptcha) {
      this.resolveAudioCaptcha = resolveAudioCaptcha;
      return this;
    }

    public Builder resolveAudioCaptcha(Map<String, Object> resolveAudioCaptcha) {
      this.resolveAudioCaptcha = Optional.ofNullable(resolveAudioCaptcha);
      return this;
    }

    public WebScrapeRequestBodyBlockUrlInstructionsItemResolveAudioCaptcha build() {
      return new WebScrapeRequestBodyBlockUrlInstructionsItemResolveAudioCaptcha(resolveAudioCaptcha, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
