/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ZipcodeDistanceRequestUnit {
  public static final ZipcodeDistanceRequestUnit KM = new ZipcodeDistanceRequestUnit(Value.KM, "km");

  public static final ZipcodeDistanceRequestUnit IN = new ZipcodeDistanceRequestUnit(Value.IN, "in");

  public static final ZipcodeDistanceRequestUnit MI = new ZipcodeDistanceRequestUnit(Value.MI, "mi");

  public static final ZipcodeDistanceRequestUnit FT = new ZipcodeDistanceRequestUnit(Value.FT, "ft");

  public static final ZipcodeDistanceRequestUnit YD = new ZipcodeDistanceRequestUnit(Value.YD, "yd");

  public static final ZipcodeDistanceRequestUnit M = new ZipcodeDistanceRequestUnit(Value.M, "m");

  private final Value value;

  private final String string;

  ZipcodeDistanceRequestUnit(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ZipcodeDistanceRequestUnit && this.string.equals(((ZipcodeDistanceRequestUnit) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case KM:
        return visitor.visitKm();
      case IN:
        return visitor.visitIn();
      case MI:
        return visitor.visitMi();
      case FT:
        return visitor.visitFt();
      case YD:
        return visitor.visitYd();
      case M:
        return visitor.visitM();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ZipcodeDistanceRequestUnit valueOf(String value) {
    switch (value) {
      case "km":
        return KM;
      case "in":
        return IN;
      case "mi":
        return MI;
      case "ft":
        return FT;
      case "yd":
        return YD;
      case "m":
        return M;
      default:
        return new ZipcodeDistanceRequestUnit(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    M,

    KM,

    MI,

    FT,

    YD,

    IN,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitM();

    T visitKm();

    T visitMi();

    T visitFt();

    T visitYd();

    T visitIn();

    T visitUnknown(String unknownType);
  }
}
