/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.apifreaks.sdk.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.apifreaks.sdk.core.ObjectMappers;
import java.lang.Float;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ZipcodeSearchByRadiusResponseResultsItem.Builder.class
)
public final class ZipcodeSearchByRadiusResponseResultsItem {
  private final Optional<String> code;

  private final Optional<String> region;

  private final Optional<String> city;

  private final Optional<String> district;

  private final Optional<Float> distance;

  private final Map<String, Object> additionalProperties;

  private ZipcodeSearchByRadiusResponseResultsItem(Optional<String> code, Optional<String> region,
      Optional<String> city, Optional<String> district,
      Optional<Float> distance, Map<String, Object> additionalProperties) {
    this.code = code;
    this.region = region;
    this.city = city;
    this.district = district;
    this.distance = distance;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("code")
  public Optional<String> getCode() {
    return code;
  }

  @JsonProperty("region")
  public Optional<String> getRegion() {
    return region;
  }

  @JsonProperty("city")
  public Optional<String> getCity() {
    return city;
  }

  @JsonProperty("district")
  public Optional<String> getDistrict() {
    return district;
  }

  @JsonProperty("distance")
  public Optional<Float> getDistance() {
    return distance;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ZipcodeSearchByRadiusResponseResultsItem && equalTo((ZipcodeSearchByRadiusResponseResultsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ZipcodeSearchByRadiusResponseResultsItem other) {
    return code.equals(other.code) && region.equals(other.region) && city.equals(other.city) && district.equals(other.district) && distance.equals(other.distance);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.code, this.region, this.city, this.district, this.distance);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> code = Optional.empty();

    private Optional<String> region = Optional.empty();

    private Optional<String> city = Optional.empty();

    private Optional<String> district = Optional.empty();

    private Optional<Float> distance = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ZipcodeSearchByRadiusResponseResultsItem other) {
      code(other.getCode());
      region(other.getRegion());
      city(other.getCity());
      district(other.getDistrict());
      distance(other.getDistance());
      return this;
    }

    @JsonSetter(
        value = "code",
        nulls = Nulls.SKIP
    )
    public Builder code(Optional<String> code) {
      this.code = code;
      return this;
    }

    public Builder code(String code) {
      this.code = Optional.ofNullable(code);
      return this;
    }

    @JsonSetter(
        value = "region",
        nulls = Nulls.SKIP
    )
    public Builder region(Optional<String> region) {
      this.region = region;
      return this;
    }

    public Builder region(String region) {
      this.region = Optional.ofNullable(region);
      return this;
    }

    @JsonSetter(
        value = "city",
        nulls = Nulls.SKIP
    )
    public Builder city(Optional<String> city) {
      this.city = city;
      return this;
    }

    public Builder city(String city) {
      this.city = Optional.ofNullable(city);
      return this;
    }

    @JsonSetter(
        value = "district",
        nulls = Nulls.SKIP
    )
    public Builder district(Optional<String> district) {
      this.district = district;
      return this;
    }

    public Builder district(String district) {
      this.district = Optional.ofNullable(district);
      return this;
    }

    @JsonSetter(
        value = "distance",
        nulls = Nulls.SKIP
    )
    public Builder distance(Optional<Float> distance) {
      this.distance = distance;
      return this;
    }

    public Builder distance(Float distance) {
      this.distance = Optional.ofNullable(distance);
      return this;
    }

    public ZipcodeSearchByRadiusResponseResultsItem build() {
      return new ZipcodeSearchByRadiusResponseResultsItem(code, region, city, district, distance, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
