/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BulkCurrentWeatherResponseBulkItemCurrent.Builder.class
)
public final class BulkCurrentWeatherResponseBulkItemCurrent {
  private final OffsetDateTime timestamp;

  private final float temperature2M;

  private final float relativeHumidity2M;

  private final float apparentTemperature;

  private final float snowfall;

  private final float rain;

  private final float showers;

  private final float precipitation;

  private final int weatherCode;

  private final float cloudCover;

  private final float pressureMsl;

  private final float surfacePressure;

  private final float windSpeed10M;

  private final int windDirection10M;

  private final float windGusts10M;

  private final BulkCurrentWeatherResponseBulkItemCurrentAstronomy astronomy;

  private final BulkCurrentWeatherResponseBulkItemCurrentAirQuality airQuality;

  private final Map<String, Object> additionalProperties;

  private BulkCurrentWeatherResponseBulkItemCurrent(OffsetDateTime timestamp, float temperature2M,
      float relativeHumidity2M, float apparentTemperature, float snowfall, float rain,
      float showers, float precipitation, int weatherCode, float cloudCover, float pressureMsl,
      float surfacePressure, float windSpeed10M, int windDirection10M, float windGusts10M,
      BulkCurrentWeatherResponseBulkItemCurrentAstronomy astronomy,
      BulkCurrentWeatherResponseBulkItemCurrentAirQuality airQuality,
      Map<String, Object> additionalProperties) {
    this.timestamp = timestamp;
    this.temperature2M = temperature2M;
    this.relativeHumidity2M = relativeHumidity2M;
    this.apparentTemperature = apparentTemperature;
    this.snowfall = snowfall;
    this.rain = rain;
    this.showers = showers;
    this.precipitation = precipitation;
    this.weatherCode = weatherCode;
    this.cloudCover = cloudCover;
    this.pressureMsl = pressureMsl;
    this.surfacePressure = surfacePressure;
    this.windSpeed10M = windSpeed10M;
    this.windDirection10M = windDirection10M;
    this.windGusts10M = windGusts10M;
    this.astronomy = astronomy;
    this.airQuality = airQuality;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return ISO 8601 formatted timestamp of the current weather observation.
   */
  @JsonProperty("timestamp")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  /**
   * @return Current air temperature (°C) measured at 2 meters above ground.
   */
  @JsonProperty("temperature_2m")
  public float getTemperature2M() {
    return temperature2M;
  }

  /**
   * @return Current relative humidity percentage at 2 meters above ground.
   */
  @JsonProperty("relative_humidity_2m")
  public float getRelativeHumidity2M() {
    return relativeHumidity2M;
  }

  /**
   * @return Current apparent temperature (°C) accounting for wind chill and humidity.
   */
  @JsonProperty("apparent_temperature")
  public float getApparentTemperature() {
    return apparentTemperature;
  }

  /**
   * @return Current snowfall accumulation in centimeters.
   */
  @JsonProperty("snowfall")
  public float getSnowfall() {
    return snowfall;
  }

  /**
   * @return Current rainfall accumulation in millimeters.
   */
  @JsonProperty("rain")
  public float getRain() {
    return rain;
  }

  /**
   * @return Current shower precipitation in millimeters.
   */
  @JsonProperty("showers")
  public float getShowers() {
    return showers;
  }

  /**
   * @return Total precipitation (mm) including rain, showers, and snowfall.
   */
  @JsonProperty("precipitation")
  public float getPrecipitation() {
    return precipitation;
  }

  /**
   * @return WMO weather condition code representing current conditions. Supported codes: 0 clear sky; 1, 2, 3 varying cloud cover; 45, 48 fog; 51, 53, 55 drizzle; 56, 57 freezing drizzle; 61, 63, 65 rain; 66, 67 freezing rain; 71, 73, 75 snowfall; 77 snow grains; 80, 81, 82 rain showers; 85, 86 snow showers; 95 thunderstorm; 96, 99 thunderstorm with hail.
   */
  @JsonProperty("weather_code")
  public int getWeatherCode() {
    return weatherCode;
  }

  /**
   * @return Current percentage of sky covered by clouds.
   */
  @JsonProperty("cloud_cover")
  public float getCloudCover() {
    return cloudCover;
  }

  /**
   * @return Current atmospheric pressure (hPa) adjusted to mean sea level.
   */
  @JsonProperty("pressure_msl")
  public float getPressureMsl() {
    return pressureMsl;
  }

  /**
   * @return Current atmospheric pressure (hPa) at surface level.
   */
  @JsonProperty("surface_pressure")
  public float getSurfacePressure() {
    return surfacePressure;
  }

  /**
   * @return Current wind speed (km/h) at 10 meters above ground.
   */
  @JsonProperty("wind_speed_10m")
  public float getWindSpeed10M() {
    return windSpeed10M;
  }

  /**
   * @return Current wind direction in degrees at 10 meters above ground.
   */
  @JsonProperty("wind_direction_10m")
  public int getWindDirection10M() {
    return windDirection10M;
  }

  /**
   * @return Current wind gust speed (km/h) at 10 meters above ground.
   */
  @JsonProperty("wind_gusts_10m")
  public float getWindGusts10M() {
    return windGusts10M;
  }

  /**
   * @return Astronomical information including sunrise, sunset, and moon phases for the current date.
   */
  @JsonProperty("astronomy")
  public BulkCurrentWeatherResponseBulkItemCurrentAstronomy getAstronomy() {
    return astronomy;
  }

  /**
   * @return Air quality metrics including pollutant concentrations and AQI values.
   */
  @JsonProperty("air_quality")
  public BulkCurrentWeatherResponseBulkItemCurrentAirQuality getAirQuality() {
    return airQuality;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BulkCurrentWeatherResponseBulkItemCurrent && equalTo((BulkCurrentWeatherResponseBulkItemCurrent) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BulkCurrentWeatherResponseBulkItemCurrent other) {
    return timestamp.equals(other.timestamp) && temperature2M == other.temperature2M && relativeHumidity2M == other.relativeHumidity2M && apparentTemperature == other.apparentTemperature && snowfall == other.snowfall && rain == other.rain && showers == other.showers && precipitation == other.precipitation && weatherCode == other.weatherCode && cloudCover == other.cloudCover && pressureMsl == other.pressureMsl && surfacePressure == other.surfacePressure && windSpeed10M == other.windSpeed10M && windDirection10M == other.windDirection10M && windGusts10M == other.windGusts10M && astronomy.equals(other.astronomy) && airQuality.equals(other.airQuality);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.timestamp, this.temperature2M, this.relativeHumidity2M, this.apparentTemperature, this.snowfall, this.rain, this.showers, this.precipitation, this.weatherCode, this.cloudCover, this.pressureMsl, this.surfacePressure, this.windSpeed10M, this.windDirection10M, this.windGusts10M, this.astronomy, this.airQuality);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TimestampStage builder() {
    return new Builder();
  }

  public interface TimestampStage {
    /**
     * <p>ISO 8601 formatted timestamp of the current weather observation.</p>
     */
    Temperature2MStage timestamp(@NotNull OffsetDateTime timestamp);

    Builder from(BulkCurrentWeatherResponseBulkItemCurrent other);
  }

  public interface Temperature2MStage {
    /**
     * <p>Current air temperature (°C) measured at 2 meters above ground.</p>
     */
    RelativeHumidity2MStage temperature2M(float temperature2M);
  }

  public interface RelativeHumidity2MStage {
    /**
     * <p>Current relative humidity percentage at 2 meters above ground.</p>
     */
    ApparentTemperatureStage relativeHumidity2M(float relativeHumidity2M);
  }

  public interface ApparentTemperatureStage {
    /**
     * <p>Current apparent temperature (°C) accounting for wind chill and humidity.</p>
     */
    SnowfallStage apparentTemperature(float apparentTemperature);
  }

  public interface SnowfallStage {
    /**
     * <p>Current snowfall accumulation in centimeters.</p>
     */
    RainStage snowfall(float snowfall);
  }

  public interface RainStage {
    /**
     * <p>Current rainfall accumulation in millimeters.</p>
     */
    ShowersStage rain(float rain);
  }

  public interface ShowersStage {
    /**
     * <p>Current shower precipitation in millimeters.</p>
     */
    PrecipitationStage showers(float showers);
  }

  public interface PrecipitationStage {
    /**
     * <p>Total precipitation (mm) including rain, showers, and snowfall.</p>
     */
    WeatherCodeStage precipitation(float precipitation);
  }

  public interface WeatherCodeStage {
    /**
     * <p>WMO weather condition code representing current conditions. Supported codes: 0 clear sky; 1, 2, 3 varying cloud cover; 45, 48 fog; 51, 53, 55 drizzle; 56, 57 freezing drizzle; 61, 63, 65 rain; 66, 67 freezing rain; 71, 73, 75 snowfall; 77 snow grains; 80, 81, 82 rain showers; 85, 86 snow showers; 95 thunderstorm; 96, 99 thunderstorm with hail.</p>
     */
    CloudCoverStage weatherCode(int weatherCode);
  }

  public interface CloudCoverStage {
    /**
     * <p>Current percentage of sky covered by clouds.</p>
     */
    PressureMslStage cloudCover(float cloudCover);
  }

  public interface PressureMslStage {
    /**
     * <p>Current atmospheric pressure (hPa) adjusted to mean sea level.</p>
     */
    SurfacePressureStage pressureMsl(float pressureMsl);
  }

  public interface SurfacePressureStage {
    /**
     * <p>Current atmospheric pressure (hPa) at surface level.</p>
     */
    WindSpeed10MStage surfacePressure(float surfacePressure);
  }

  public interface WindSpeed10MStage {
    /**
     * <p>Current wind speed (km/h) at 10 meters above ground.</p>
     */
    WindDirection10MStage windSpeed10M(float windSpeed10M);
  }

  public interface WindDirection10MStage {
    /**
     * <p>Current wind direction in degrees at 10 meters above ground.</p>
     */
    WindGusts10MStage windDirection10M(int windDirection10M);
  }

  public interface WindGusts10MStage {
    /**
     * <p>Current wind gust speed (km/h) at 10 meters above ground.</p>
     */
    AstronomyStage windGusts10M(float windGusts10M);
  }

  public interface AstronomyStage {
    /**
     * <p>Astronomical information including sunrise, sunset, and moon phases for the current date.</p>
     */
    AirQualityStage astronomy(
        @NotNull BulkCurrentWeatherResponseBulkItemCurrentAstronomy astronomy);
  }

  public interface AirQualityStage {
    /**
     * <p>Air quality metrics including pollutant concentrations and AQI values.</p>
     */
    _FinalStage airQuality(@NotNull BulkCurrentWeatherResponseBulkItemCurrentAirQuality airQuality);
  }

  public interface _FinalStage {
    BulkCurrentWeatherResponseBulkItemCurrent build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TimestampStage, Temperature2MStage, RelativeHumidity2MStage, ApparentTemperatureStage, SnowfallStage, RainStage, ShowersStage, PrecipitationStage, WeatherCodeStage, CloudCoverStage, PressureMslStage, SurfacePressureStage, WindSpeed10MStage, WindDirection10MStage, WindGusts10MStage, AstronomyStage, AirQualityStage, _FinalStage {
    private OffsetDateTime timestamp;

    private float temperature2M;

    private float relativeHumidity2M;

    private float apparentTemperature;

    private float snowfall;

    private float rain;

    private float showers;

    private float precipitation;

    private int weatherCode;

    private float cloudCover;

    private float pressureMsl;

    private float surfacePressure;

    private float windSpeed10M;

    private int windDirection10M;

    private float windGusts10M;

    private BulkCurrentWeatherResponseBulkItemCurrentAstronomy astronomy;

    private BulkCurrentWeatherResponseBulkItemCurrentAirQuality airQuality;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BulkCurrentWeatherResponseBulkItemCurrent other) {
      timestamp(other.getTimestamp());
      temperature2M(other.getTemperature2M());
      relativeHumidity2M(other.getRelativeHumidity2M());
      apparentTemperature(other.getApparentTemperature());
      snowfall(other.getSnowfall());
      rain(other.getRain());
      showers(other.getShowers());
      precipitation(other.getPrecipitation());
      weatherCode(other.getWeatherCode());
      cloudCover(other.getCloudCover());
      pressureMsl(other.getPressureMsl());
      surfacePressure(other.getSurfacePressure());
      windSpeed10M(other.getWindSpeed10M());
      windDirection10M(other.getWindDirection10M());
      windGusts10M(other.getWindGusts10M());
      astronomy(other.getAstronomy());
      airQuality(other.getAirQuality());
      return this;
    }

    /**
     * <p>ISO 8601 formatted timestamp of the current weather observation.</p>
     * <p>ISO 8601 formatted timestamp of the current weather observation.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("timestamp")
    public Temperature2MStage timestamp(@NotNull OffsetDateTime timestamp) {
      this.timestamp = Objects.requireNonNull(timestamp, "timestamp must not be null");
      return this;
    }

    /**
     * <p>Current air temperature (°C) measured at 2 meters above ground.</p>
     * <p>Current air temperature (°C) measured at 2 meters above ground.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("temperature_2m")
    public RelativeHumidity2MStage temperature2M(float temperature2M) {
      this.temperature2M = temperature2M;
      return this;
    }

    /**
     * <p>Current relative humidity percentage at 2 meters above ground.</p>
     * <p>Current relative humidity percentage at 2 meters above ground.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("relative_humidity_2m")
    public ApparentTemperatureStage relativeHumidity2M(float relativeHumidity2M) {
      this.relativeHumidity2M = relativeHumidity2M;
      return this;
    }

    /**
     * <p>Current apparent temperature (°C) accounting for wind chill and humidity.</p>
     * <p>Current apparent temperature (°C) accounting for wind chill and humidity.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("apparent_temperature")
    public SnowfallStage apparentTemperature(float apparentTemperature) {
      this.apparentTemperature = apparentTemperature;
      return this;
    }

    /**
     * <p>Current snowfall accumulation in centimeters.</p>
     * <p>Current snowfall accumulation in centimeters.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("snowfall")
    public RainStage snowfall(float snowfall) {
      this.snowfall = snowfall;
      return this;
    }

    /**
     * <p>Current rainfall accumulation in millimeters.</p>
     * <p>Current rainfall accumulation in millimeters.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("rain")
    public ShowersStage rain(float rain) {
      this.rain = rain;
      return this;
    }

    /**
     * <p>Current shower precipitation in millimeters.</p>
     * <p>Current shower precipitation in millimeters.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("showers")
    public PrecipitationStage showers(float showers) {
      this.showers = showers;
      return this;
    }

    /**
     * <p>Total precipitation (mm) including rain, showers, and snowfall.</p>
     * <p>Total precipitation (mm) including rain, showers, and snowfall.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("precipitation")
    public WeatherCodeStage precipitation(float precipitation) {
      this.precipitation = precipitation;
      return this;
    }

    /**
     * <p>WMO weather condition code representing current conditions. Supported codes: 0 clear sky; 1, 2, 3 varying cloud cover; 45, 48 fog; 51, 53, 55 drizzle; 56, 57 freezing drizzle; 61, 63, 65 rain; 66, 67 freezing rain; 71, 73, 75 snowfall; 77 snow grains; 80, 81, 82 rain showers; 85, 86 snow showers; 95 thunderstorm; 96, 99 thunderstorm with hail.</p>
     * <p>WMO weather condition code representing current conditions. Supported codes: 0 clear sky; 1, 2, 3 varying cloud cover; 45, 48 fog; 51, 53, 55 drizzle; 56, 57 freezing drizzle; 61, 63, 65 rain; 66, 67 freezing rain; 71, 73, 75 snowfall; 77 snow grains; 80, 81, 82 rain showers; 85, 86 snow showers; 95 thunderstorm; 96, 99 thunderstorm with hail.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("weather_code")
    public CloudCoverStage weatherCode(int weatherCode) {
      this.weatherCode = weatherCode;
      return this;
    }

    /**
     * <p>Current percentage of sky covered by clouds.</p>
     * <p>Current percentage of sky covered by clouds.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("cloud_cover")
    public PressureMslStage cloudCover(float cloudCover) {
      this.cloudCover = cloudCover;
      return this;
    }

    /**
     * <p>Current atmospheric pressure (hPa) adjusted to mean sea level.</p>
     * <p>Current atmospheric pressure (hPa) adjusted to mean sea level.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("pressure_msl")
    public SurfacePressureStage pressureMsl(float pressureMsl) {
      this.pressureMsl = pressureMsl;
      return this;
    }

    /**
     * <p>Current atmospheric pressure (hPa) at surface level.</p>
     * <p>Current atmospheric pressure (hPa) at surface level.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("surface_pressure")
    public WindSpeed10MStage surfacePressure(float surfacePressure) {
      this.surfacePressure = surfacePressure;
      return this;
    }

    /**
     * <p>Current wind speed (km/h) at 10 meters above ground.</p>
     * <p>Current wind speed (km/h) at 10 meters above ground.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("wind_speed_10m")
    public WindDirection10MStage windSpeed10M(float windSpeed10M) {
      this.windSpeed10M = windSpeed10M;
      return this;
    }

    /**
     * <p>Current wind direction in degrees at 10 meters above ground.</p>
     * <p>Current wind direction in degrees at 10 meters above ground.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("wind_direction_10m")
    public WindGusts10MStage windDirection10M(int windDirection10M) {
      this.windDirection10M = windDirection10M;
      return this;
    }

    /**
     * <p>Current wind gust speed (km/h) at 10 meters above ground.</p>
     * <p>Current wind gust speed (km/h) at 10 meters above ground.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("wind_gusts_10m")
    public AstronomyStage windGusts10M(float windGusts10M) {
      this.windGusts10M = windGusts10M;
      return this;
    }

    /**
     * <p>Astronomical information including sunrise, sunset, and moon phases for the current date.</p>
     * <p>Astronomical information including sunrise, sunset, and moon phases for the current date.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("astronomy")
    public AirQualityStage astronomy(
        @NotNull BulkCurrentWeatherResponseBulkItemCurrentAstronomy astronomy) {
      this.astronomy = Objects.requireNonNull(astronomy, "astronomy must not be null");
      return this;
    }

    /**
     * <p>Air quality metrics including pollutant concentrations and AQI values.</p>
     * <p>Air quality metrics including pollutant concentrations and AQI values.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("air_quality")
    public _FinalStage airQuality(
        @NotNull BulkCurrentWeatherResponseBulkItemCurrentAirQuality airQuality) {
      this.airQuality = Objects.requireNonNull(airQuality, "airQuality must not be null");
      return this;
    }

    @java.lang.Override
    public BulkCurrentWeatherResponseBulkItemCurrent build() {
      return new BulkCurrentWeatherResponseBulkItemCurrent(timestamp, temperature2M, relativeHumidity2M, apparentTemperature, snowfall, rain, showers, precipitation, weatherCode, cloudCover, pressureMsl, surfacePressure, windSpeed10M, windDirection10M, windGusts10M, astronomy, airQuality, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
