/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Float;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BulkVatRateByCountryResponseCountriesItem.Builder.class
)
public final class BulkVatRateByCountryResponseCountriesItem {
  private final String country;

  private final Optional<String> state;

  private final Optional<String> type;

  private final Optional<String> currency;

  private final Optional<Float> standardRate;

  private final Optional<List<Float>> reducedRate;

  private final Optional<List<Float>> superReducedRate;

  private final Optional<Float> parkingRate;

  private final Optional<Map<String, Float>> categories;

  private final Map<String, Object> additionalProperties;

  private BulkVatRateByCountryResponseCountriesItem(String country, Optional<String> state,
      Optional<String> type, Optional<String> currency, Optional<Float> standardRate,
      Optional<List<Float>> reducedRate, Optional<List<Float>> superReducedRate,
      Optional<Float> parkingRate, Optional<Map<String, Float>> categories,
      Map<String, Object> additionalProperties) {
    this.country = country;
    this.state = state;
    this.type = type;
    this.currency = currency;
    this.standardRate = standardRate;
    this.reducedRate = reducedRate;
    this.superReducedRate = superReducedRate;
    this.parkingRate = parkingRate;
    this.categories = categories;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Country identifier in Alpha-2 (US), Alpha-3 (USA), or full name (United_States). Case-insensitive and may use underscores.
   */
  @JsonProperty("country")
  public String getCountry() {
    return country;
  }

  /**
   * @return Optional state identifier in Alpha-2 (NY) or full name (New_York). Required only for state-level taxation. Case-insensitive and may use underscores.
   */
  @JsonProperty("state")
  public Optional<String> getState() {
    return state;
  }

  /**
   * @return Tax type applied for the country or state. Possible values include vat or none.
   */
  @JsonProperty("type")
  public Optional<String> getType() {
    return type;
  }

  /**
   * @return ISO 4217 currency code.
   */
  @JsonProperty("currency")
  public Optional<String> getCurrency() {
    return currency;
  }

  /**
   * @return Standard VAT or sales tax rate. Zero indicates no tax.
   */
  @JsonProperty("standard_rate")
  public Optional<Float> getStandardRate() {
    return standardRate;
  }

  /**
   * @return Optional reduced VAT rates applicable in the country.
   */
  @JsonProperty("reduced_rate")
  public Optional<List<Float>> getReducedRate() {
    return reducedRate;
  }

  /**
   * @return Optional super-reduced VAT rates applicable in specific categories.
   */
  @JsonProperty("super_reduced_rate")
  public Optional<List<Float>> getSuperReducedRate() {
    return superReducedRate;
  }

  @JsonProperty("parking_rate")
  public Optional<Float> getParkingRate() {
    return parkingRate;
  }

  /**
   * @return Optional category-wise VAT rates.
   */
  @JsonProperty("categories")
  public Optional<Map<String, Float>> getCategories() {
    return categories;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BulkVatRateByCountryResponseCountriesItem && equalTo((BulkVatRateByCountryResponseCountriesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BulkVatRateByCountryResponseCountriesItem other) {
    return country.equals(other.country) && state.equals(other.state) && type.equals(other.type) && currency.equals(other.currency) && standardRate.equals(other.standardRate) && reducedRate.equals(other.reducedRate) && superReducedRate.equals(other.superReducedRate) && parkingRate.equals(other.parkingRate) && categories.equals(other.categories);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.country, this.state, this.type, this.currency, this.standardRate, this.reducedRate, this.superReducedRate, this.parkingRate, this.categories);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CountryStage builder() {
    return new Builder();
  }

  public interface CountryStage {
    /**
     * <p>Country identifier in Alpha-2 (US), Alpha-3 (USA), or full name (United_States). Case-insensitive and may use underscores.</p>
     */
    _FinalStage country(@NotNull String country);

    Builder from(BulkVatRateByCountryResponseCountriesItem other);
  }

  public interface _FinalStage {
    BulkVatRateByCountryResponseCountriesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Optional state identifier in Alpha-2 (NY) or full name (New_York). Required only for state-level taxation. Case-insensitive and may use underscores.</p>
     */
    _FinalStage state(Optional<String> state);

    _FinalStage state(String state);

    /**
     * <p>Tax type applied for the country or state. Possible values include vat or none.</p>
     */
    _FinalStage type(Optional<String> type);

    _FinalStage type(String type);

    /**
     * <p>ISO 4217 currency code.</p>
     */
    _FinalStage currency(Optional<String> currency);

    _FinalStage currency(String currency);

    /**
     * <p>Standard VAT or sales tax rate. Zero indicates no tax.</p>
     */
    _FinalStage standardRate(Optional<Float> standardRate);

    _FinalStage standardRate(Float standardRate);

    /**
     * <p>Optional reduced VAT rates applicable in the country.</p>
     */
    _FinalStage reducedRate(Optional<List<Float>> reducedRate);

    _FinalStage reducedRate(List<Float> reducedRate);

    /**
     * <p>Optional super-reduced VAT rates applicable in specific categories.</p>
     */
    _FinalStage superReducedRate(Optional<List<Float>> superReducedRate);

    _FinalStage superReducedRate(List<Float> superReducedRate);

    _FinalStage parkingRate(Optional<Float> parkingRate);

    _FinalStage parkingRate(Float parkingRate);

    /**
     * <p>Optional category-wise VAT rates.</p>
     */
    _FinalStage categories(Optional<Map<String, Float>> categories);

    _FinalStage categories(Map<String, Float> categories);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CountryStage, _FinalStage {
    private String country;

    private Optional<Map<String, Float>> categories = Optional.empty();

    private Optional<Float> parkingRate = Optional.empty();

    private Optional<List<Float>> superReducedRate = Optional.empty();

    private Optional<List<Float>> reducedRate = Optional.empty();

    private Optional<Float> standardRate = Optional.empty();

    private Optional<String> currency = Optional.empty();

    private Optional<String> type = Optional.empty();

    private Optional<String> state = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BulkVatRateByCountryResponseCountriesItem other) {
      country(other.getCountry());
      state(other.getState());
      type(other.getType());
      currency(other.getCurrency());
      standardRate(other.getStandardRate());
      reducedRate(other.getReducedRate());
      superReducedRate(other.getSuperReducedRate());
      parkingRate(other.getParkingRate());
      categories(other.getCategories());
      return this;
    }

    /**
     * <p>Country identifier in Alpha-2 (US), Alpha-3 (USA), or full name (United_States). Case-insensitive and may use underscores.</p>
     * <p>Country identifier in Alpha-2 (US), Alpha-3 (USA), or full name (United_States). Case-insensitive and may use underscores.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("country")
    public _FinalStage country(@NotNull String country) {
      this.country = Objects.requireNonNull(country, "country must not be null");
      return this;
    }

    /**
     * <p>Optional category-wise VAT rates.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage categories(Map<String, Float> categories) {
      this.categories = Optional.ofNullable(categories);
      return this;
    }

    /**
     * <p>Optional category-wise VAT rates.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "categories",
        nulls = Nulls.SKIP
    )
    public _FinalStage categories(Optional<Map<String, Float>> categories) {
      this.categories = categories;
      return this;
    }

    @java.lang.Override
    public _FinalStage parkingRate(Float parkingRate) {
      this.parkingRate = Optional.ofNullable(parkingRate);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "parking_rate",
        nulls = Nulls.SKIP
    )
    public _FinalStage parkingRate(Optional<Float> parkingRate) {
      this.parkingRate = parkingRate;
      return this;
    }

    /**
     * <p>Optional super-reduced VAT rates applicable in specific categories.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage superReducedRate(List<Float> superReducedRate) {
      this.superReducedRate = Optional.ofNullable(superReducedRate);
      return this;
    }

    /**
     * <p>Optional super-reduced VAT rates applicable in specific categories.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "super_reduced_rate",
        nulls = Nulls.SKIP
    )
    public _FinalStage superReducedRate(Optional<List<Float>> superReducedRate) {
      this.superReducedRate = superReducedRate;
      return this;
    }

    /**
     * <p>Optional reduced VAT rates applicable in the country.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage reducedRate(List<Float> reducedRate) {
      this.reducedRate = Optional.ofNullable(reducedRate);
      return this;
    }

    /**
     * <p>Optional reduced VAT rates applicable in the country.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "reduced_rate",
        nulls = Nulls.SKIP
    )
    public _FinalStage reducedRate(Optional<List<Float>> reducedRate) {
      this.reducedRate = reducedRate;
      return this;
    }

    /**
     * <p>Standard VAT or sales tax rate. Zero indicates no tax.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage standardRate(Float standardRate) {
      this.standardRate = Optional.ofNullable(standardRate);
      return this;
    }

    /**
     * <p>Standard VAT or sales tax rate. Zero indicates no tax.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "standard_rate",
        nulls = Nulls.SKIP
    )
    public _FinalStage standardRate(Optional<Float> standardRate) {
      this.standardRate = standardRate;
      return this;
    }

    /**
     * <p>ISO 4217 currency code.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage currency(String currency) {
      this.currency = Optional.ofNullable(currency);
      return this;
    }

    /**
     * <p>ISO 4217 currency code.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "currency",
        nulls = Nulls.SKIP
    )
    public _FinalStage currency(Optional<String> currency) {
      this.currency = currency;
      return this;
    }

    /**
     * <p>Tax type applied for the country or state. Possible values include vat or none.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage type(String type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * <p>Tax type applied for the country or state. Possible values include vat or none.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public _FinalStage type(Optional<String> type) {
      this.type = type;
      return this;
    }

    /**
     * <p>Optional state identifier in Alpha-2 (NY) or full name (New_York). Required only for state-level taxation. Case-insensitive and may use underscores.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage state(String state) {
      this.state = Optional.ofNullable(state);
      return this;
    }

    /**
     * <p>Optional state identifier in Alpha-2 (NY) or full name (New_York). Required only for state-level taxation. Case-insensitive and may use underscores.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "state",
        nulls = Nulls.SKIP
    )
    public _FinalStage state(Optional<String> state) {
      this.state = state;
      return this;
    }

    @java.lang.Override
    public BulkVatRateByCountryResponseCountriesItem build() {
      return new BulkVatRateByCountryResponseCountriesItem(country, state, type, currency, standardRate, reducedRate, superReducedRate, parkingRate, categories, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
