/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CommodityLatestRatesResponse.Builder.class
)
public final class CommodityLatestRatesResponse {
  private final boolean success;

  private final double timestamp;

  private final Map<String, Double> rates;

  private final Map<String, CommodityLatestRatesResponseMetadataValue> metadata;

  private final Map<String, Object> additionalProperties;

  private CommodityLatestRatesResponse(boolean success, double timestamp, Map<String, Double> rates,
      Map<String, CommodityLatestRatesResponseMetadataValue> metadata,
      Map<String, Object> additionalProperties) {
    this.success = success;
    this.timestamp = timestamp;
    this.rates = rates;
    this.metadata = metadata;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return API request success indicator. 'true' for successful requests.
   */
  @JsonProperty("success")
  public boolean getSuccess() {
    return success;
  }

  /**
   * @return Unix timestamp indicating when the response was generated.
   */
  @JsonProperty("timestamp")
  public double getTimestamp() {
    return timestamp;
  }

  /**
   * @return Map containing rate data for all the requested commodities.
   */
  @JsonProperty("rates")
  public Map<String, Double> getRates() {
    return rates;
  }

  /**
   * @return Map containing detailed information for all the requested commodities keyed by commodity symbol.
   */
  @JsonProperty("metadata")
  public Map<String, CommodityLatestRatesResponseMetadataValue> getMetadata() {
    return metadata;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CommodityLatestRatesResponse && equalTo((CommodityLatestRatesResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CommodityLatestRatesResponse other) {
    return success == other.success && timestamp == other.timestamp && rates.equals(other.rates) && metadata.equals(other.metadata);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.success, this.timestamp, this.rates, this.metadata);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SuccessStage builder() {
    return new Builder();
  }

  public interface SuccessStage {
    /**
     * <p>API request success indicator. 'true' for successful requests.</p>
     */
    TimestampStage success(boolean success);

    Builder from(CommodityLatestRatesResponse other);
  }

  public interface TimestampStage {
    /**
     * <p>Unix timestamp indicating when the response was generated.</p>
     */
    _FinalStage timestamp(double timestamp);
  }

  public interface _FinalStage {
    CommodityLatestRatesResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Map containing rate data for all the requested commodities.</p>
     */
    _FinalStage rates(Map<String, Double> rates);

    _FinalStage putAllRates(Map<String, Double> rates);

    _FinalStage rates(String key, Double value);

    /**
     * <p>Map containing detailed information for all the requested commodities keyed by commodity symbol.</p>
     */
    _FinalStage metadata(Map<String, CommodityLatestRatesResponseMetadataValue> metadata);

    _FinalStage putAllMetadata(Map<String, CommodityLatestRatesResponseMetadataValue> metadata);

    _FinalStage metadata(String key, CommodityLatestRatesResponseMetadataValue value);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SuccessStage, TimestampStage, _FinalStage {
    private boolean success;

    private double timestamp;

    private Map<String, CommodityLatestRatesResponseMetadataValue> metadata = new LinkedHashMap<>();

    private Map<String, Double> rates = new LinkedHashMap<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CommodityLatestRatesResponse other) {
      success(other.getSuccess());
      timestamp(other.getTimestamp());
      rates(other.getRates());
      metadata(other.getMetadata());
      return this;
    }

    /**
     * <p>API request success indicator. 'true' for successful requests.</p>
     * <p>API request success indicator. 'true' for successful requests.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("success")
    public TimestampStage success(boolean success) {
      this.success = success;
      return this;
    }

    /**
     * <p>Unix timestamp indicating when the response was generated.</p>
     * <p>Unix timestamp indicating when the response was generated.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("timestamp")
    public _FinalStage timestamp(double timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    /**
     * <p>Map containing detailed information for all the requested commodities keyed by commodity symbol.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metadata(String key, CommodityLatestRatesResponseMetadataValue value) {
      this.metadata.put(key, value);
      return this;
    }

    /**
     * <p>Map containing detailed information for all the requested commodities keyed by commodity symbol.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage putAllMetadata(
        Map<String, CommodityLatestRatesResponseMetadataValue> metadata) {
      if (metadata != null) {
        this.metadata.putAll(metadata);
      }
      return this;
    }

    /**
     * <p>Map containing detailed information for all the requested commodities keyed by commodity symbol.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metadata",
        nulls = Nulls.SKIP
    )
    public _FinalStage metadata(Map<String, CommodityLatestRatesResponseMetadataValue> metadata) {
      this.metadata.clear();
      if (metadata != null) {
        this.metadata.putAll(metadata);
      }
      return this;
    }

    /**
     * <p>Map containing rate data for all the requested commodities.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage rates(String key, Double value) {
      this.rates.put(key, value);
      return this;
    }

    /**
     * <p>Map containing rate data for all the requested commodities.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage putAllRates(Map<String, Double> rates) {
      if (rates != null) {
        this.rates.putAll(rates);
      }
      return this;
    }

    /**
     * <p>Map containing rate data for all the requested commodities.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "rates",
        nulls = Nulls.SKIP
    )
    public _FinalStage rates(Map<String, Double> rates) {
      this.rates.clear();
      if (rates != null) {
        this.rates.putAll(rates);
      }
      return this;
    }

    @java.lang.Override
    public CommodityLatestRatesResponse build() {
      return new CommodityLatestRatesResponse(success, timestamp, rates, metadata, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
