/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CurrencySupportedResponseSupportedCurrenciesMapValue.Builder.class
)
public final class CurrencySupportedResponseSupportedCurrenciesMapValue {
  private final String currencyCode;

  private final String currencyName;

  private final String countryCode;

  private final String countryName;

  private final CurrencySupportedResponseSupportedCurrenciesMapValueStatus status;

  private final String availableFrom;

  private final String availableUntil;

  private final String icon;

  private final Map<String, Object> additionalProperties;

  private CurrencySupportedResponseSupportedCurrenciesMapValue(String currencyCode,
      String currencyName, String countryCode, String countryName,
      CurrencySupportedResponseSupportedCurrenciesMapValueStatus status, String availableFrom,
      String availableUntil, String icon, Map<String, Object> additionalProperties) {
    this.currencyCode = currencyCode;
    this.currencyName = currencyName;
    this.countryCode = countryCode;
    this.countryName = countryName;
    this.status = status;
    this.availableFrom = availableFrom;
    this.availableUntil = availableUntil;
    this.icon = icon;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("currencyCode")
  public String getCurrencyCode() {
    return currencyCode;
  }

  @JsonProperty("currencyName")
  public String getCurrencyName() {
    return currencyName;
  }

  @JsonProperty("countryCode")
  public String getCountryCode() {
    return countryCode;
  }

  @JsonProperty("countryName")
  public String getCountryName() {
    return countryName;
  }

  @JsonProperty("status")
  public CurrencySupportedResponseSupportedCurrenciesMapValueStatus getStatus() {
    return status;
  }

  @JsonProperty("availableFrom")
  public String getAvailableFrom() {
    return availableFrom;
  }

  @JsonProperty("availableUntil")
  public String getAvailableUntil() {
    return availableUntil;
  }

  @JsonProperty("icon")
  public String getIcon() {
    return icon;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CurrencySupportedResponseSupportedCurrenciesMapValue && equalTo((CurrencySupportedResponseSupportedCurrenciesMapValue) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CurrencySupportedResponseSupportedCurrenciesMapValue other) {
    return currencyCode.equals(other.currencyCode) && currencyName.equals(other.currencyName) && countryCode.equals(other.countryCode) && countryName.equals(other.countryName) && status.equals(other.status) && availableFrom.equals(other.availableFrom) && availableUntil.equals(other.availableUntil) && icon.equals(other.icon);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.currencyCode, this.currencyName, this.countryCode, this.countryName, this.status, this.availableFrom, this.availableUntil, this.icon);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CurrencyCodeStage builder() {
    return new Builder();
  }

  public interface CurrencyCodeStage {
    CurrencyNameStage currencyCode(@NotNull String currencyCode);

    Builder from(CurrencySupportedResponseSupportedCurrenciesMapValue other);
  }

  public interface CurrencyNameStage {
    CountryCodeStage currencyName(@NotNull String currencyName);
  }

  public interface CountryCodeStage {
    CountryNameStage countryCode(@NotNull String countryCode);
  }

  public interface CountryNameStage {
    StatusStage countryName(@NotNull String countryName);
  }

  public interface StatusStage {
    AvailableFromStage status(
        @NotNull CurrencySupportedResponseSupportedCurrenciesMapValueStatus status);
  }

  public interface AvailableFromStage {
    AvailableUntilStage availableFrom(@NotNull String availableFrom);
  }

  public interface AvailableUntilStage {
    IconStage availableUntil(@NotNull String availableUntil);
  }

  public interface IconStage {
    _FinalStage icon(@NotNull String icon);
  }

  public interface _FinalStage {
    CurrencySupportedResponseSupportedCurrenciesMapValue build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CurrencyCodeStage, CurrencyNameStage, CountryCodeStage, CountryNameStage, StatusStage, AvailableFromStage, AvailableUntilStage, IconStage, _FinalStage {
    private String currencyCode;

    private String currencyName;

    private String countryCode;

    private String countryName;

    private CurrencySupportedResponseSupportedCurrenciesMapValueStatus status;

    private String availableFrom;

    private String availableUntil;

    private String icon;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CurrencySupportedResponseSupportedCurrenciesMapValue other) {
      currencyCode(other.getCurrencyCode());
      currencyName(other.getCurrencyName());
      countryCode(other.getCountryCode());
      countryName(other.getCountryName());
      status(other.getStatus());
      availableFrom(other.getAvailableFrom());
      availableUntil(other.getAvailableUntil());
      icon(other.getIcon());
      return this;
    }

    @java.lang.Override
    @JsonSetter("currencyCode")
    public CurrencyNameStage currencyCode(@NotNull String currencyCode) {
      this.currencyCode = Objects.requireNonNull(currencyCode, "currencyCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("currencyName")
    public CountryCodeStage currencyName(@NotNull String currencyName) {
      this.currencyName = Objects.requireNonNull(currencyName, "currencyName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("countryCode")
    public CountryNameStage countryCode(@NotNull String countryCode) {
      this.countryCode = Objects.requireNonNull(countryCode, "countryCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("countryName")
    public StatusStage countryName(@NotNull String countryName) {
      this.countryName = Objects.requireNonNull(countryName, "countryName must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public AvailableFromStage status(
        @NotNull CurrencySupportedResponseSupportedCurrenciesMapValueStatus status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("availableFrom")
    public AvailableUntilStage availableFrom(@NotNull String availableFrom) {
      this.availableFrom = Objects.requireNonNull(availableFrom, "availableFrom must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("availableUntil")
    public IconStage availableUntil(@NotNull String availableUntil) {
      this.availableUntil = Objects.requireNonNull(availableUntil, "availableUntil must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("icon")
    public _FinalStage icon(@NotNull String icon) {
      this.icon = Objects.requireNonNull(icon, "icon must not be null");
      return this;
    }

    @java.lang.Override
    public CurrencySupportedResponseSupportedCurrenciesMapValue build() {
      return new CurrencySupportedResponseSupportedCurrenciesMapValue(currencyCode, currencyName, countryCode, countryName, status, availableFrom, availableUntil, icon, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
