/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemSingleNameDnsType {
  public static final DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemSingleNameDnsType NS = new DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemSingleNameDnsType(Value.NS, "NS");

  private final Value value;

  private final String string;

  DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemSingleNameDnsType(Value value,
      String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemSingleNameDnsType && this.string.equals(((DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemSingleNameDnsType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case NS:
        return visitor.visitNs();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemSingleNameDnsType valueOf(
      String value) {
    switch (value) {
      case "NS":
        return NS;
      default:
        return new DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemSingleNameDnsType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    NS,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitNs();

    T visitUnknown(String unknownType);
  }
}
