/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DomainDnsLookupResponse.Builder.class
)
public final class DomainDnsLookupResponse {
  private final boolean status;

  private final OffsetDateTime queryTime;

  private final String domainName;

  private final boolean domainRegistered;

  private final DomainDnsLookupResponseDnsTypes dnsTypes;

  private final List<DomainDnsLookupResponseDnsRecordsItem> dnsRecords;

  private final Map<String, Object> additionalProperties;

  private DomainDnsLookupResponse(boolean status, OffsetDateTime queryTime, String domainName,
      boolean domainRegistered, DomainDnsLookupResponseDnsTypes dnsTypes,
      List<DomainDnsLookupResponseDnsRecordsItem> dnsRecords,
      Map<String, Object> additionalProperties) {
    this.status = status;
    this.queryTime = queryTime;
    this.domainName = domainName;
    this.domainRegistered = domainRegistered;
    this.dnsTypes = dnsTypes;
    this.dnsRecords = dnsRecords;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Indicates whether the query was processed successfully.
   */
  @JsonProperty("status")
  public boolean getStatus() {
    return status;
  }

  /**
   * @return Time at which the query was made (Format:YYYY-MM-DD HH:mm:ss).
   */
  @JsonProperty("queryTime")
  public OffsetDateTime getQueryTime() {
    return queryTime;
  }

  /**
   * @return Queried domain.
   */
  @JsonProperty("domainName")
  public String getDomainName() {
    return domainName;
  }

  /**
   * @return Indicates whether the domain is registered.
   */
  @JsonProperty("domainRegistered")
  public boolean getDomainRegistered() {
    return domainRegistered;
  }

  @JsonProperty("dnsTypes")
  public DomainDnsLookupResponseDnsTypes getDnsTypes() {
    return dnsTypes;
  }

  /**
   * @return List of DNS records, each based on its type.
   */
  @JsonProperty("dnsRecords")
  public List<DomainDnsLookupResponseDnsRecordsItem> getDnsRecords() {
    return dnsRecords;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DomainDnsLookupResponse && equalTo((DomainDnsLookupResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DomainDnsLookupResponse other) {
    return status == other.status && queryTime.equals(other.queryTime) && domainName.equals(other.domainName) && domainRegistered == other.domainRegistered && dnsTypes.equals(other.dnsTypes) && dnsRecords.equals(other.dnsRecords);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.status, this.queryTime, this.domainName, this.domainRegistered, this.dnsTypes, this.dnsRecords);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static StatusStage builder() {
    return new Builder();
  }

  public interface StatusStage {
    /**
     * <p>Indicates whether the query was processed successfully.</p>
     */
    QueryTimeStage status(boolean status);

    Builder from(DomainDnsLookupResponse other);
  }

  public interface QueryTimeStage {
    /**
     * <p>Time at which the query was made (Format:YYYY-MM-DD HH:mm:ss).</p>
     */
    DomainNameStage queryTime(@NotNull OffsetDateTime queryTime);
  }

  public interface DomainNameStage {
    /**
     * <p>Queried domain.</p>
     */
    DomainRegisteredStage domainName(@NotNull String domainName);
  }

  public interface DomainRegisteredStage {
    /**
     * <p>Indicates whether the domain is registered.</p>
     */
    DnsTypesStage domainRegistered(boolean domainRegistered);
  }

  public interface DnsTypesStage {
    _FinalStage dnsTypes(@NotNull DomainDnsLookupResponseDnsTypes dnsTypes);
  }

  public interface _FinalStage {
    DomainDnsLookupResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>List of DNS records, each based on its type.</p>
     */
    _FinalStage dnsRecords(List<DomainDnsLookupResponseDnsRecordsItem> dnsRecords);

    _FinalStage addDnsRecords(DomainDnsLookupResponseDnsRecordsItem dnsRecords);

    _FinalStage addAllDnsRecords(List<DomainDnsLookupResponseDnsRecordsItem> dnsRecords);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements StatusStage, QueryTimeStage, DomainNameStage, DomainRegisteredStage, DnsTypesStage, _FinalStage {
    private boolean status;

    private OffsetDateTime queryTime;

    private String domainName;

    private boolean domainRegistered;

    private DomainDnsLookupResponseDnsTypes dnsTypes;

    private List<DomainDnsLookupResponseDnsRecordsItem> dnsRecords = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DomainDnsLookupResponse other) {
      status(other.getStatus());
      queryTime(other.getQueryTime());
      domainName(other.getDomainName());
      domainRegistered(other.getDomainRegistered());
      dnsTypes(other.getDnsTypes());
      dnsRecords(other.getDnsRecords());
      return this;
    }

    /**
     * <p>Indicates whether the query was processed successfully.</p>
     * <p>Indicates whether the query was processed successfully.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("status")
    public QueryTimeStage status(boolean status) {
      this.status = status;
      return this;
    }

    /**
     * <p>Time at which the query was made (Format:YYYY-MM-DD HH:mm:ss).</p>
     * <p>Time at which the query was made (Format:YYYY-MM-DD HH:mm:ss).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("queryTime")
    public DomainNameStage queryTime(@NotNull OffsetDateTime queryTime) {
      this.queryTime = Objects.requireNonNull(queryTime, "queryTime must not be null");
      return this;
    }

    /**
     * <p>Queried domain.</p>
     * <p>Queried domain.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("domainName")
    public DomainRegisteredStage domainName(@NotNull String domainName) {
      this.domainName = Objects.requireNonNull(domainName, "domainName must not be null");
      return this;
    }

    /**
     * <p>Indicates whether the domain is registered.</p>
     * <p>Indicates whether the domain is registered.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("domainRegistered")
    public DnsTypesStage domainRegistered(boolean domainRegistered) {
      this.domainRegistered = domainRegistered;
      return this;
    }

    @java.lang.Override
    @JsonSetter("dnsTypes")
    public _FinalStage dnsTypes(@NotNull DomainDnsLookupResponseDnsTypes dnsTypes) {
      this.dnsTypes = Objects.requireNonNull(dnsTypes, "dnsTypes must not be null");
      return this;
    }

    /**
     * <p>List of DNS records, each based on its type.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllDnsRecords(List<DomainDnsLookupResponseDnsRecordsItem> dnsRecords) {
      if (dnsRecords != null) {
        this.dnsRecords.addAll(dnsRecords);
      }
      return this;
    }

    /**
     * <p>List of DNS records, each based on its type.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addDnsRecords(DomainDnsLookupResponseDnsRecordsItem dnsRecords) {
      this.dnsRecords.add(dnsRecords);
      return this;
    }

    /**
     * <p>List of DNS records, each based on its type.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "dnsRecords",
        nulls = Nulls.SKIP
    )
    public _FinalStage dnsRecords(List<DomainDnsLookupResponseDnsRecordsItem> dnsRecords) {
      this.dnsRecords.clear();
      if (dnsRecords != null) {
        this.dnsRecords.addAll(dnsRecords);
      }
      return this;
    }

    @java.lang.Override
    public DomainDnsLookupResponse build() {
      return new DomainDnsLookupResponse(status, queryTime, domainName, domainRegistered, dnsTypes, dnsRecords, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
