/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class MarineWeatherRequestPrecision {
  public static final MarineWeatherRequestPrecision HOURLY = new MarineWeatherRequestPrecision(Value.HOURLY, "hourly");

  public static final MarineWeatherRequestPrecision DAILY = new MarineWeatherRequestPrecision(Value.DAILY, "daily");

  public static final MarineWeatherRequestPrecision MINUTELY = new MarineWeatherRequestPrecision(Value.MINUTELY, "minutely");

  private final Value value;

  private final String string;

  MarineWeatherRequestPrecision(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof MarineWeatherRequestPrecision && this.string.equals(((MarineWeatherRequestPrecision) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case HOURLY:
        return visitor.visitHourly();
      case DAILY:
        return visitor.visitDaily();
      case MINUTELY:
        return visitor.visitMinutely();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static MarineWeatherRequestPrecision valueOf(String value) {
    switch (value) {
      case "hourly":
        return HOURLY;
      case "daily":
        return DAILY;
      case "minutely":
        return MINUTELY;
      default:
        return new MarineWeatherRequestPrecision(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    DAILY,

    HOURLY,

    MINUTELY,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitDaily();

    T visitHourly();

    T visitMinutely();

    T visitUnknown(String unknownType);
  }
}
