/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ReadabilityScoreResponseReadabilityScoresColemanLiauIndex.Builder.class
)
public final class ReadabilityScoreResponseReadabilityScoresColemanLiauIndex {
  private final Optional<Double> score;

  private final Optional<String> level;

  private final Map<String, Object> additionalProperties;

  private ReadabilityScoreResponseReadabilityScoresColemanLiauIndex(Optional<Double> score,
      Optional<String> level, Map<String, Object> additionalProperties) {
    this.score = score;
    this.level = level;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The metric score
   */
  @JsonProperty("score")
  public Optional<Double> getScore() {
    return score;
  }

  /**
   * @return Human-readable difficulty level for that metric
   */
  @JsonProperty("level")
  public Optional<String> getLevel() {
    return level;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ReadabilityScoreResponseReadabilityScoresColemanLiauIndex && equalTo((ReadabilityScoreResponseReadabilityScoresColemanLiauIndex) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ReadabilityScoreResponseReadabilityScoresColemanLiauIndex other) {
    return score.equals(other.score) && level.equals(other.level);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.score, this.level);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Double> score = Optional.empty();

    private Optional<String> level = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ReadabilityScoreResponseReadabilityScoresColemanLiauIndex other) {
      score(other.getScore());
      level(other.getLevel());
      return this;
    }

    /**
     * <p>The metric score</p>
     */
    @JsonSetter(
        value = "score",
        nulls = Nulls.SKIP
    )
    public Builder score(Optional<Double> score) {
      this.score = score;
      return this;
    }

    public Builder score(Double score) {
      this.score = Optional.ofNullable(score);
      return this;
    }

    /**
     * <p>Human-readable difficulty level for that metric</p>
     */
    @JsonSetter(
        value = "level",
        nulls = Nulls.SKIP
    )
    public Builder level(Optional<String> level) {
      this.level = level;
      return this;
    }

    public Builder level(String level) {
      this.level = Optional.ofNullable(level);
      return this;
    }

    public ReadabilityScoreResponseReadabilityScoresColemanLiauIndex build() {
      return new ReadabilityScoreResponseReadabilityScoresColemanLiauIndex(score, level, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
