/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TimezoneLookupResponseAirportDetails.Builder.class
)
public final class TimezoneLookupResponseAirportDetails {
  private final String type;

  private final String name;

  private final String longitude;

  private final String latitude;

  private final double elevationFt;

  private final String continentCode;

  private final String countryCode;

  private final String stateCode;

  private final String city;

  private final String iataCode;

  private final String icaoCode;

  private final String faaCode;

  private final Map<String, Object> additionalProperties;

  private TimezoneLookupResponseAirportDetails(String type, String name, String longitude,
      String latitude, double elevationFt, String continentCode, String countryCode,
      String stateCode, String city, String iataCode, String icaoCode, String faaCode,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.name = name;
    this.longitude = longitude;
    this.latitude = latitude;
    this.elevationFt = elevationFt;
    this.continentCode = continentCode;
    this.countryCode = countryCode;
    this.stateCode = stateCode;
    this.city = city;
    this.iataCode = iataCode;
    this.icaoCode = icaoCode;
    this.faaCode = faaCode;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public String getType() {
    return type;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("longitude")
  public String getLongitude() {
    return longitude;
  }

  @JsonProperty("latitude")
  public String getLatitude() {
    return latitude;
  }

  @JsonProperty("elevation_ft")
  public double getElevationFt() {
    return elevationFt;
  }

  @JsonProperty("continent_code")
  public String getContinentCode() {
    return continentCode;
  }

  @JsonProperty("country_code")
  public String getCountryCode() {
    return countryCode;
  }

  @JsonProperty("state_code")
  public String getStateCode() {
    return stateCode;
  }

  @JsonProperty("city")
  public String getCity() {
    return city;
  }

  @JsonProperty("iata_code")
  public String getIataCode() {
    return iataCode;
  }

  @JsonProperty("icao_code")
  public String getIcaoCode() {
    return icaoCode;
  }

  @JsonProperty("faa_code")
  public String getFaaCode() {
    return faaCode;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TimezoneLookupResponseAirportDetails && equalTo((TimezoneLookupResponseAirportDetails) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TimezoneLookupResponseAirportDetails other) {
    return type.equals(other.type) && name.equals(other.name) && longitude.equals(other.longitude) && latitude.equals(other.latitude) && elevationFt == other.elevationFt && continentCode.equals(other.continentCode) && countryCode.equals(other.countryCode) && stateCode.equals(other.stateCode) && city.equals(other.city) && iataCode.equals(other.iataCode) && icaoCode.equals(other.icaoCode) && faaCode.equals(other.faaCode);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.name, this.longitude, this.latitude, this.elevationFt, this.continentCode, this.countryCode, this.stateCode, this.city, this.iataCode, this.icaoCode, this.faaCode);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    NameStage type(@NotNull String type);

    Builder from(TimezoneLookupResponseAirportDetails other);
  }

  public interface NameStage {
    LongitudeStage name(@NotNull String name);
  }

  public interface LongitudeStage {
    LatitudeStage longitude(@NotNull String longitude);
  }

  public interface LatitudeStage {
    ElevationFtStage latitude(@NotNull String latitude);
  }

  public interface ElevationFtStage {
    ContinentCodeStage elevationFt(double elevationFt);
  }

  public interface ContinentCodeStage {
    CountryCodeStage continentCode(@NotNull String continentCode);
  }

  public interface CountryCodeStage {
    StateCodeStage countryCode(@NotNull String countryCode);
  }

  public interface StateCodeStage {
    CityStage stateCode(@NotNull String stateCode);
  }

  public interface CityStage {
    IataCodeStage city(@NotNull String city);
  }

  public interface IataCodeStage {
    IcaoCodeStage iataCode(@NotNull String iataCode);
  }

  public interface IcaoCodeStage {
    FaaCodeStage icaoCode(@NotNull String icaoCode);
  }

  public interface FaaCodeStage {
    _FinalStage faaCode(@NotNull String faaCode);
  }

  public interface _FinalStage {
    TimezoneLookupResponseAirportDetails build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, NameStage, LongitudeStage, LatitudeStage, ElevationFtStage, ContinentCodeStage, CountryCodeStage, StateCodeStage, CityStage, IataCodeStage, IcaoCodeStage, FaaCodeStage, _FinalStage {
    private String type;

    private String name;

    private String longitude;

    private String latitude;

    private double elevationFt;

    private String continentCode;

    private String countryCode;

    private String stateCode;

    private String city;

    private String iataCode;

    private String icaoCode;

    private String faaCode;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TimezoneLookupResponseAirportDetails other) {
      type(other.getType());
      name(other.getName());
      longitude(other.getLongitude());
      latitude(other.getLatitude());
      elevationFt(other.getElevationFt());
      continentCode(other.getContinentCode());
      countryCode(other.getCountryCode());
      stateCode(other.getStateCode());
      city(other.getCity());
      iataCode(other.getIataCode());
      icaoCode(other.getIcaoCode());
      faaCode(other.getFaaCode());
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public NameStage type(@NotNull String type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public LongitudeStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("longitude")
    public LatitudeStage longitude(@NotNull String longitude) {
      this.longitude = Objects.requireNonNull(longitude, "longitude must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("latitude")
    public ElevationFtStage latitude(@NotNull String latitude) {
      this.latitude = Objects.requireNonNull(latitude, "latitude must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("elevation_ft")
    public ContinentCodeStage elevationFt(double elevationFt) {
      this.elevationFt = elevationFt;
      return this;
    }

    @java.lang.Override
    @JsonSetter("continent_code")
    public CountryCodeStage continentCode(@NotNull String continentCode) {
      this.continentCode = Objects.requireNonNull(continentCode, "continentCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("country_code")
    public StateCodeStage countryCode(@NotNull String countryCode) {
      this.countryCode = Objects.requireNonNull(countryCode, "countryCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("state_code")
    public CityStage stateCode(@NotNull String stateCode) {
      this.stateCode = Objects.requireNonNull(stateCode, "stateCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("city")
    public IataCodeStage city(@NotNull String city) {
      this.city = Objects.requireNonNull(city, "city must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("iata_code")
    public IcaoCodeStage iataCode(@NotNull String iataCode) {
      this.iataCode = Objects.requireNonNull(iataCode, "iataCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("icao_code")
    public FaaCodeStage icaoCode(@NotNull String icaoCode) {
      this.icaoCode = Objects.requireNonNull(icaoCode, "icaoCode must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("faa_code")
    public _FinalStage faaCode(@NotNull String faaCode) {
      this.faaCode = Objects.requireNonNull(faaCode, "faaCode must not be null");
      return this;
    }

    @java.lang.Override
    public TimezoneLookupResponseAirportDetails build() {
      return new TimezoneLookupResponseAirportDetails(type, name, longitude, latitude, elevationFt, continentCode, countryCode, stateCode, city, iataCode, icaoCode, faaCode, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
