/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WeatherTimeSeriesResponseHistoricalValueDaily.Builder.class
)
public final class WeatherTimeSeriesResponseHistoricalValueDaily {
  private final Optional<OffsetDateTime> timestamp;

  private final Optional<Integer> weatherCode;

  private final Optional<Double> temperature2MMean;

  private final Optional<Double> temperature2MMax;

  private final Optional<Double> temperature2MMin;

  private final Optional<Double> apparentTemperatureMean;

  private final Optional<Double> apparentTemperatureMax;

  private final Optional<Double> apparentTemperatureMin;

  private final Optional<Double> precipitationSum;

  private final Optional<Double> rainSum;

  private final Optional<Double> snowfallSum;

  private final Optional<Double> windSpeed10MMax;

  private final Optional<Double> windGusts10MMax;

  private final Optional<Double> windSpeed10MMean;

  private final Optional<Double> windSpeed10MMin;

  private final Optional<Double> windGusts10MMin;

  private final Optional<Double> windGusts10MMean;

  private final Optional<Integer> windDirection10MDominant;

  private final Optional<Double> shortwaveRadiationSum;

  private final Optional<Double> et0FaoEvapotranspirationSum;

  private final Optional<Double> cloudCoverMean;

  private final Optional<Double> dewPoint2MMean;

  private final Optional<Double> dewPoint2MMax;

  private final Optional<Double> dewPoint2MMin;

  private final Optional<Double> relativeHumidity2MMean;

  private final Optional<Integer> relativeHumidity2MMax;

  private final Optional<Integer> relativeHumidity2MMin;

  private final Optional<Double> pressureMslMean;

  private final Optional<Double> surfacePressureMean;

  private final Map<String, Object> additionalProperties;

  private WeatherTimeSeriesResponseHistoricalValueDaily(Optional<OffsetDateTime> timestamp,
      Optional<Integer> weatherCode, Optional<Double> temperature2MMean,
      Optional<Double> temperature2MMax, Optional<Double> temperature2MMin,
      Optional<Double> apparentTemperatureMean, Optional<Double> apparentTemperatureMax,
      Optional<Double> apparentTemperatureMin, Optional<Double> precipitationSum,
      Optional<Double> rainSum, Optional<Double> snowfallSum, Optional<Double> windSpeed10MMax,
      Optional<Double> windGusts10MMax, Optional<Double> windSpeed10MMean,
      Optional<Double> windSpeed10MMin, Optional<Double> windGusts10MMin,
      Optional<Double> windGusts10MMean, Optional<Integer> windDirection10MDominant,
      Optional<Double> shortwaveRadiationSum, Optional<Double> et0FaoEvapotranspirationSum,
      Optional<Double> cloudCoverMean, Optional<Double> dewPoint2MMean,
      Optional<Double> dewPoint2MMax, Optional<Double> dewPoint2MMin,
      Optional<Double> relativeHumidity2MMean, Optional<Integer> relativeHumidity2MMax,
      Optional<Integer> relativeHumidity2MMin, Optional<Double> pressureMslMean,
      Optional<Double> surfacePressureMean, Map<String, Object> additionalProperties) {
    this.timestamp = timestamp;
    this.weatherCode = weatherCode;
    this.temperature2MMean = temperature2MMean;
    this.temperature2MMax = temperature2MMax;
    this.temperature2MMin = temperature2MMin;
    this.apparentTemperatureMean = apparentTemperatureMean;
    this.apparentTemperatureMax = apparentTemperatureMax;
    this.apparentTemperatureMin = apparentTemperatureMin;
    this.precipitationSum = precipitationSum;
    this.rainSum = rainSum;
    this.snowfallSum = snowfallSum;
    this.windSpeed10MMax = windSpeed10MMax;
    this.windGusts10MMax = windGusts10MMax;
    this.windSpeed10MMean = windSpeed10MMean;
    this.windSpeed10MMin = windSpeed10MMin;
    this.windGusts10MMin = windGusts10MMin;
    this.windGusts10MMean = windGusts10MMean;
    this.windDirection10MDominant = windDirection10MDominant;
    this.shortwaveRadiationSum = shortwaveRadiationSum;
    this.et0FaoEvapotranspirationSum = et0FaoEvapotranspirationSum;
    this.cloudCoverMean = cloudCoverMean;
    this.dewPoint2MMean = dewPoint2MMean;
    this.dewPoint2MMax = dewPoint2MMax;
    this.dewPoint2MMin = dewPoint2MMin;
    this.relativeHumidity2MMean = relativeHumidity2MMean;
    this.relativeHumidity2MMax = relativeHumidity2MMax;
    this.relativeHumidity2MMin = relativeHumidity2MMin;
    this.pressureMslMean = pressureMslMean;
    this.surfacePressureMean = surfacePressureMean;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return ISO 8601 formatted timestamp
   */
  @JsonProperty("timestamp")
  public Optional<OffsetDateTime> getTimestamp() {
    return timestamp;
  }

  /**
   * @return Weather condition code
   */
  @JsonProperty("weather_code")
  public Optional<Integer> getWeatherCode() {
    return weatherCode;
  }

  /**
   * @return Daily mean air temperature at 2 meters (°C)
   */
  @JsonProperty("temperature_2m_mean")
  public Optional<Double> getTemperature2MMean() {
    return temperature2MMean;
  }

  /**
   * @return Daily maximum air temperature at 2 meters (°C)
   */
  @JsonProperty("temperature_2m_max")
  public Optional<Double> getTemperature2MMax() {
    return temperature2MMax;
  }

  /**
   * @return Daily minimum air temperature at 2 meters (°C)
   */
  @JsonProperty("temperature_2m_min")
  public Optional<Double> getTemperature2MMin() {
    return temperature2MMin;
  }

  /**
   * @return Daily mean perceived temperature (°C)
   */
  @JsonProperty("apparent_temperature_mean")
  public Optional<Double> getApparentTemperatureMean() {
    return apparentTemperatureMean;
  }

  /**
   * @return Daily maximum perceived temperature (°C)
   */
  @JsonProperty("apparent_temperature_max")
  public Optional<Double> getApparentTemperatureMax() {
    return apparentTemperatureMax;
  }

  /**
   * @return Daily minimum perceived temperature (°C)
   */
  @JsonProperty("apparent_temperature_min")
  public Optional<Double> getApparentTemperatureMin() {
    return apparentTemperatureMin;
  }

  /**
   * @return Total precipitation (mm)
   */
  @JsonProperty("precipitation_sum")
  public Optional<Double> getPrecipitationSum() {
    return precipitationSum;
  }

  /**
   * @return Total rainfall (mm)
   */
  @JsonProperty("rain_sum")
  public Optional<Double> getRainSum() {
    return rainSum;
  }

  /**
   * @return Total snowfall (cm)
   */
  @JsonProperty("snowfall_sum")
  public Optional<Double> getSnowfallSum() {
    return snowfallSum;
  }

  /**
   * @return Maximum wind speed at 10 meters (km/h)
   */
  @JsonProperty("wind_speed_10m_max")
  public Optional<Double> getWindSpeed10MMax() {
    return windSpeed10MMax;
  }

  /**
   * @return Maximum wind gusts at 10 meters (km/h)
   */
  @JsonProperty("wind_gusts_10m_max")
  public Optional<Double> getWindGusts10MMax() {
    return windGusts10MMax;
  }

  /**
   * @return Daily mean wind speed at 10 meters (km/h)
   */
  @JsonProperty("wind_speed_10m_mean")
  public Optional<Double> getWindSpeed10MMean() {
    return windSpeed10MMean;
  }

  /**
   * @return Minimum wind speed at 10 meters (km/h)
   */
  @JsonProperty("wind_speed_10m_min")
  public Optional<Double> getWindSpeed10MMin() {
    return windSpeed10MMin;
  }

  /**
   * @return Minimum wind gusts at 10 meters (km/h)
   */
  @JsonProperty("wind_gusts_10m_min")
  public Optional<Double> getWindGusts10MMin() {
    return windGusts10MMin;
  }

  /**
   * @return Daily mean wind gusts at 10 meters (km/h)
   */
  @JsonProperty("wind_gusts_10m_mean")
  public Optional<Double> getWindGusts10MMean() {
    return windGusts10MMean;
  }

  /**
   * @return Dominant wind direction at 10 meters (°)
   */
  @JsonProperty("wind_direction_10m_dominant")
  public Optional<Integer> getWindDirection10MDominant() {
    return windDirection10MDominant;
  }

  /**
   * @return Daily sum of shortwave solar radiation (MJ/m²)
   */
  @JsonProperty("shortwave_radiation_sum")
  public Optional<Double> getShortwaveRadiationSum() {
    return shortwaveRadiationSum;
  }

  /**
   * @return Daily sum of reference evapotranspiration (mm)
   */
  @JsonProperty("et0_fao_evapotranspiration_sum")
  public Optional<Double> getEt0FaoEvapotranspirationSum() {
    return et0FaoEvapotranspirationSum;
  }

  /**
   * @return Daily mean cloud cover percentage (%)
   */
  @JsonProperty("cloud_cover_mean")
  public Optional<Double> getCloudCoverMean() {
    return cloudCoverMean;
  }

  /**
   * @return Daily mean dew point temperature at 2 meters (°C)
   */
  @JsonProperty("dew_point_2m_mean")
  public Optional<Double> getDewPoint2MMean() {
    return dewPoint2MMean;
  }

  /**
   * @return Daily maximum dew point temperature at 2 meters (°C)
   */
  @JsonProperty("dew_point_2m_max")
  public Optional<Double> getDewPoint2MMax() {
    return dewPoint2MMax;
  }

  /**
   * @return Daily minimum dew point temperature at 2 meters (°C)
   */
  @JsonProperty("dew_point_2m_min")
  public Optional<Double> getDewPoint2MMin() {
    return dewPoint2MMin;
  }

  /**
   * @return Daily mean relative humidity at 2 meters (%)
   */
  @JsonProperty("relative_humidity_2m_mean")
  public Optional<Double> getRelativeHumidity2MMean() {
    return relativeHumidity2MMean;
  }

  /**
   * @return Daily maximum relative humidity at 2 meters (%)
   */
  @JsonProperty("relative_humidity_2m_max")
  public Optional<Integer> getRelativeHumidity2MMax() {
    return relativeHumidity2MMax;
  }

  /**
   * @return Daily minimum relative humidity at 2 meters (%)
   */
  @JsonProperty("relative_humidity_2m_min")
  public Optional<Integer> getRelativeHumidity2MMin() {
    return relativeHumidity2MMin;
  }

  /**
   * @return Daily mean atmospheric pressure at mean sea level (hPa)
   */
  @JsonProperty("pressure_msl_mean")
  public Optional<Double> getPressureMslMean() {
    return pressureMslMean;
  }

  /**
   * @return Daily mean surface pressure at ground level (hPa)
   */
  @JsonProperty("surface_pressure_mean")
  public Optional<Double> getSurfacePressureMean() {
    return surfacePressureMean;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WeatherTimeSeriesResponseHistoricalValueDaily && equalTo((WeatherTimeSeriesResponseHistoricalValueDaily) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WeatherTimeSeriesResponseHistoricalValueDaily other) {
    return timestamp.equals(other.timestamp) && weatherCode.equals(other.weatherCode) && temperature2MMean.equals(other.temperature2MMean) && temperature2MMax.equals(other.temperature2MMax) && temperature2MMin.equals(other.temperature2MMin) && apparentTemperatureMean.equals(other.apparentTemperatureMean) && apparentTemperatureMax.equals(other.apparentTemperatureMax) && apparentTemperatureMin.equals(other.apparentTemperatureMin) && precipitationSum.equals(other.precipitationSum) && rainSum.equals(other.rainSum) && snowfallSum.equals(other.snowfallSum) && windSpeed10MMax.equals(other.windSpeed10MMax) && windGusts10MMax.equals(other.windGusts10MMax) && windSpeed10MMean.equals(other.windSpeed10MMean) && windSpeed10MMin.equals(other.windSpeed10MMin) && windGusts10MMin.equals(other.windGusts10MMin) && windGusts10MMean.equals(other.windGusts10MMean) && windDirection10MDominant.equals(other.windDirection10MDominant) && shortwaveRadiationSum.equals(other.shortwaveRadiationSum) && et0FaoEvapotranspirationSum.equals(other.et0FaoEvapotranspirationSum) && cloudCoverMean.equals(other.cloudCoverMean) && dewPoint2MMean.equals(other.dewPoint2MMean) && dewPoint2MMax.equals(other.dewPoint2MMax) && dewPoint2MMin.equals(other.dewPoint2MMin) && relativeHumidity2MMean.equals(other.relativeHumidity2MMean) && relativeHumidity2MMax.equals(other.relativeHumidity2MMax) && relativeHumidity2MMin.equals(other.relativeHumidity2MMin) && pressureMslMean.equals(other.pressureMslMean) && surfacePressureMean.equals(other.surfacePressureMean);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.timestamp, this.weatherCode, this.temperature2MMean, this.temperature2MMax, this.temperature2MMin, this.apparentTemperatureMean, this.apparentTemperatureMax, this.apparentTemperatureMin, this.precipitationSum, this.rainSum, this.snowfallSum, this.windSpeed10MMax, this.windGusts10MMax, this.windSpeed10MMean, this.windSpeed10MMin, this.windGusts10MMin, this.windGusts10MMean, this.windDirection10MDominant, this.shortwaveRadiationSum, this.et0FaoEvapotranspirationSum, this.cloudCoverMean, this.dewPoint2MMean, this.dewPoint2MMax, this.dewPoint2MMin, this.relativeHumidity2MMean, this.relativeHumidity2MMax, this.relativeHumidity2MMin, this.pressureMslMean, this.surfacePressureMean);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<OffsetDateTime> timestamp = Optional.empty();

    private Optional<Integer> weatherCode = Optional.empty();

    private Optional<Double> temperature2MMean = Optional.empty();

    private Optional<Double> temperature2MMax = Optional.empty();

    private Optional<Double> temperature2MMin = Optional.empty();

    private Optional<Double> apparentTemperatureMean = Optional.empty();

    private Optional<Double> apparentTemperatureMax = Optional.empty();

    private Optional<Double> apparentTemperatureMin = Optional.empty();

    private Optional<Double> precipitationSum = Optional.empty();

    private Optional<Double> rainSum = Optional.empty();

    private Optional<Double> snowfallSum = Optional.empty();

    private Optional<Double> windSpeed10MMax = Optional.empty();

    private Optional<Double> windGusts10MMax = Optional.empty();

    private Optional<Double> windSpeed10MMean = Optional.empty();

    private Optional<Double> windSpeed10MMin = Optional.empty();

    private Optional<Double> windGusts10MMin = Optional.empty();

    private Optional<Double> windGusts10MMean = Optional.empty();

    private Optional<Integer> windDirection10MDominant = Optional.empty();

    private Optional<Double> shortwaveRadiationSum = Optional.empty();

    private Optional<Double> et0FaoEvapotranspirationSum = Optional.empty();

    private Optional<Double> cloudCoverMean = Optional.empty();

    private Optional<Double> dewPoint2MMean = Optional.empty();

    private Optional<Double> dewPoint2MMax = Optional.empty();

    private Optional<Double> dewPoint2MMin = Optional.empty();

    private Optional<Double> relativeHumidity2MMean = Optional.empty();

    private Optional<Integer> relativeHumidity2MMax = Optional.empty();

    private Optional<Integer> relativeHumidity2MMin = Optional.empty();

    private Optional<Double> pressureMslMean = Optional.empty();

    private Optional<Double> surfacePressureMean = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WeatherTimeSeriesResponseHistoricalValueDaily other) {
      timestamp(other.getTimestamp());
      weatherCode(other.getWeatherCode());
      temperature2MMean(other.getTemperature2MMean());
      temperature2MMax(other.getTemperature2MMax());
      temperature2MMin(other.getTemperature2MMin());
      apparentTemperatureMean(other.getApparentTemperatureMean());
      apparentTemperatureMax(other.getApparentTemperatureMax());
      apparentTemperatureMin(other.getApparentTemperatureMin());
      precipitationSum(other.getPrecipitationSum());
      rainSum(other.getRainSum());
      snowfallSum(other.getSnowfallSum());
      windSpeed10MMax(other.getWindSpeed10MMax());
      windGusts10MMax(other.getWindGusts10MMax());
      windSpeed10MMean(other.getWindSpeed10MMean());
      windSpeed10MMin(other.getWindSpeed10MMin());
      windGusts10MMin(other.getWindGusts10MMin());
      windGusts10MMean(other.getWindGusts10MMean());
      windDirection10MDominant(other.getWindDirection10MDominant());
      shortwaveRadiationSum(other.getShortwaveRadiationSum());
      et0FaoEvapotranspirationSum(other.getEt0FaoEvapotranspirationSum());
      cloudCoverMean(other.getCloudCoverMean());
      dewPoint2MMean(other.getDewPoint2MMean());
      dewPoint2MMax(other.getDewPoint2MMax());
      dewPoint2MMin(other.getDewPoint2MMin());
      relativeHumidity2MMean(other.getRelativeHumidity2MMean());
      relativeHumidity2MMax(other.getRelativeHumidity2MMax());
      relativeHumidity2MMin(other.getRelativeHumidity2MMin());
      pressureMslMean(other.getPressureMslMean());
      surfacePressureMean(other.getSurfacePressureMean());
      return this;
    }

    /**
     * <p>ISO 8601 formatted timestamp</p>
     */
    @JsonSetter(
        value = "timestamp",
        nulls = Nulls.SKIP
    )
    public Builder timestamp(Optional<OffsetDateTime> timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    public Builder timestamp(OffsetDateTime timestamp) {
      this.timestamp = Optional.ofNullable(timestamp);
      return this;
    }

    /**
     * <p>Weather condition code</p>
     */
    @JsonSetter(
        value = "weather_code",
        nulls = Nulls.SKIP
    )
    public Builder weatherCode(Optional<Integer> weatherCode) {
      this.weatherCode = weatherCode;
      return this;
    }

    public Builder weatherCode(Integer weatherCode) {
      this.weatherCode = Optional.ofNullable(weatherCode);
      return this;
    }

    /**
     * <p>Daily mean air temperature at 2 meters (°C)</p>
     */
    @JsonSetter(
        value = "temperature_2m_mean",
        nulls = Nulls.SKIP
    )
    public Builder temperature2MMean(Optional<Double> temperature2MMean) {
      this.temperature2MMean = temperature2MMean;
      return this;
    }

    public Builder temperature2MMean(Double temperature2MMean) {
      this.temperature2MMean = Optional.ofNullable(temperature2MMean);
      return this;
    }

    /**
     * <p>Daily maximum air temperature at 2 meters (°C)</p>
     */
    @JsonSetter(
        value = "temperature_2m_max",
        nulls = Nulls.SKIP
    )
    public Builder temperature2MMax(Optional<Double> temperature2MMax) {
      this.temperature2MMax = temperature2MMax;
      return this;
    }

    public Builder temperature2MMax(Double temperature2MMax) {
      this.temperature2MMax = Optional.ofNullable(temperature2MMax);
      return this;
    }

    /**
     * <p>Daily minimum air temperature at 2 meters (°C)</p>
     */
    @JsonSetter(
        value = "temperature_2m_min",
        nulls = Nulls.SKIP
    )
    public Builder temperature2MMin(Optional<Double> temperature2MMin) {
      this.temperature2MMin = temperature2MMin;
      return this;
    }

    public Builder temperature2MMin(Double temperature2MMin) {
      this.temperature2MMin = Optional.ofNullable(temperature2MMin);
      return this;
    }

    /**
     * <p>Daily mean perceived temperature (°C)</p>
     */
    @JsonSetter(
        value = "apparent_temperature_mean",
        nulls = Nulls.SKIP
    )
    public Builder apparentTemperatureMean(Optional<Double> apparentTemperatureMean) {
      this.apparentTemperatureMean = apparentTemperatureMean;
      return this;
    }

    public Builder apparentTemperatureMean(Double apparentTemperatureMean) {
      this.apparentTemperatureMean = Optional.ofNullable(apparentTemperatureMean);
      return this;
    }

    /**
     * <p>Daily maximum perceived temperature (°C)</p>
     */
    @JsonSetter(
        value = "apparent_temperature_max",
        nulls = Nulls.SKIP
    )
    public Builder apparentTemperatureMax(Optional<Double> apparentTemperatureMax) {
      this.apparentTemperatureMax = apparentTemperatureMax;
      return this;
    }

    public Builder apparentTemperatureMax(Double apparentTemperatureMax) {
      this.apparentTemperatureMax = Optional.ofNullable(apparentTemperatureMax);
      return this;
    }

    /**
     * <p>Daily minimum perceived temperature (°C)</p>
     */
    @JsonSetter(
        value = "apparent_temperature_min",
        nulls = Nulls.SKIP
    )
    public Builder apparentTemperatureMin(Optional<Double> apparentTemperatureMin) {
      this.apparentTemperatureMin = apparentTemperatureMin;
      return this;
    }

    public Builder apparentTemperatureMin(Double apparentTemperatureMin) {
      this.apparentTemperatureMin = Optional.ofNullable(apparentTemperatureMin);
      return this;
    }

    /**
     * <p>Total precipitation (mm)</p>
     */
    @JsonSetter(
        value = "precipitation_sum",
        nulls = Nulls.SKIP
    )
    public Builder precipitationSum(Optional<Double> precipitationSum) {
      this.precipitationSum = precipitationSum;
      return this;
    }

    public Builder precipitationSum(Double precipitationSum) {
      this.precipitationSum = Optional.ofNullable(precipitationSum);
      return this;
    }

    /**
     * <p>Total rainfall (mm)</p>
     */
    @JsonSetter(
        value = "rain_sum",
        nulls = Nulls.SKIP
    )
    public Builder rainSum(Optional<Double> rainSum) {
      this.rainSum = rainSum;
      return this;
    }

    public Builder rainSum(Double rainSum) {
      this.rainSum = Optional.ofNullable(rainSum);
      return this;
    }

    /**
     * <p>Total snowfall (cm)</p>
     */
    @JsonSetter(
        value = "snowfall_sum",
        nulls = Nulls.SKIP
    )
    public Builder snowfallSum(Optional<Double> snowfallSum) {
      this.snowfallSum = snowfallSum;
      return this;
    }

    public Builder snowfallSum(Double snowfallSum) {
      this.snowfallSum = Optional.ofNullable(snowfallSum);
      return this;
    }

    /**
     * <p>Maximum wind speed at 10 meters (km/h)</p>
     */
    @JsonSetter(
        value = "wind_speed_10m_max",
        nulls = Nulls.SKIP
    )
    public Builder windSpeed10MMax(Optional<Double> windSpeed10MMax) {
      this.windSpeed10MMax = windSpeed10MMax;
      return this;
    }

    public Builder windSpeed10MMax(Double windSpeed10MMax) {
      this.windSpeed10MMax = Optional.ofNullable(windSpeed10MMax);
      return this;
    }

    /**
     * <p>Maximum wind gusts at 10 meters (km/h)</p>
     */
    @JsonSetter(
        value = "wind_gusts_10m_max",
        nulls = Nulls.SKIP
    )
    public Builder windGusts10MMax(Optional<Double> windGusts10MMax) {
      this.windGusts10MMax = windGusts10MMax;
      return this;
    }

    public Builder windGusts10MMax(Double windGusts10MMax) {
      this.windGusts10MMax = Optional.ofNullable(windGusts10MMax);
      return this;
    }

    /**
     * <p>Daily mean wind speed at 10 meters (km/h)</p>
     */
    @JsonSetter(
        value = "wind_speed_10m_mean",
        nulls = Nulls.SKIP
    )
    public Builder windSpeed10MMean(Optional<Double> windSpeed10MMean) {
      this.windSpeed10MMean = windSpeed10MMean;
      return this;
    }

    public Builder windSpeed10MMean(Double windSpeed10MMean) {
      this.windSpeed10MMean = Optional.ofNullable(windSpeed10MMean);
      return this;
    }

    /**
     * <p>Minimum wind speed at 10 meters (km/h)</p>
     */
    @JsonSetter(
        value = "wind_speed_10m_min",
        nulls = Nulls.SKIP
    )
    public Builder windSpeed10MMin(Optional<Double> windSpeed10MMin) {
      this.windSpeed10MMin = windSpeed10MMin;
      return this;
    }

    public Builder windSpeed10MMin(Double windSpeed10MMin) {
      this.windSpeed10MMin = Optional.ofNullable(windSpeed10MMin);
      return this;
    }

    /**
     * <p>Minimum wind gusts at 10 meters (km/h)</p>
     */
    @JsonSetter(
        value = "wind_gusts_10m_min",
        nulls = Nulls.SKIP
    )
    public Builder windGusts10MMin(Optional<Double> windGusts10MMin) {
      this.windGusts10MMin = windGusts10MMin;
      return this;
    }

    public Builder windGusts10MMin(Double windGusts10MMin) {
      this.windGusts10MMin = Optional.ofNullable(windGusts10MMin);
      return this;
    }

    /**
     * <p>Daily mean wind gusts at 10 meters (km/h)</p>
     */
    @JsonSetter(
        value = "wind_gusts_10m_mean",
        nulls = Nulls.SKIP
    )
    public Builder windGusts10MMean(Optional<Double> windGusts10MMean) {
      this.windGusts10MMean = windGusts10MMean;
      return this;
    }

    public Builder windGusts10MMean(Double windGusts10MMean) {
      this.windGusts10MMean = Optional.ofNullable(windGusts10MMean);
      return this;
    }

    /**
     * <p>Dominant wind direction at 10 meters (°)</p>
     */
    @JsonSetter(
        value = "wind_direction_10m_dominant",
        nulls = Nulls.SKIP
    )
    public Builder windDirection10MDominant(Optional<Integer> windDirection10MDominant) {
      this.windDirection10MDominant = windDirection10MDominant;
      return this;
    }

    public Builder windDirection10MDominant(Integer windDirection10MDominant) {
      this.windDirection10MDominant = Optional.ofNullable(windDirection10MDominant);
      return this;
    }

    /**
     * <p>Daily sum of shortwave solar radiation (MJ/m²)</p>
     */
    @JsonSetter(
        value = "shortwave_radiation_sum",
        nulls = Nulls.SKIP
    )
    public Builder shortwaveRadiationSum(Optional<Double> shortwaveRadiationSum) {
      this.shortwaveRadiationSum = shortwaveRadiationSum;
      return this;
    }

    public Builder shortwaveRadiationSum(Double shortwaveRadiationSum) {
      this.shortwaveRadiationSum = Optional.ofNullable(shortwaveRadiationSum);
      return this;
    }

    /**
     * <p>Daily sum of reference evapotranspiration (mm)</p>
     */
    @JsonSetter(
        value = "et0_fao_evapotranspiration_sum",
        nulls = Nulls.SKIP
    )
    public Builder et0FaoEvapotranspirationSum(Optional<Double> et0FaoEvapotranspirationSum) {
      this.et0FaoEvapotranspirationSum = et0FaoEvapotranspirationSum;
      return this;
    }

    public Builder et0FaoEvapotranspirationSum(Double et0FaoEvapotranspirationSum) {
      this.et0FaoEvapotranspirationSum = Optional.ofNullable(et0FaoEvapotranspirationSum);
      return this;
    }

    /**
     * <p>Daily mean cloud cover percentage (%)</p>
     */
    @JsonSetter(
        value = "cloud_cover_mean",
        nulls = Nulls.SKIP
    )
    public Builder cloudCoverMean(Optional<Double> cloudCoverMean) {
      this.cloudCoverMean = cloudCoverMean;
      return this;
    }

    public Builder cloudCoverMean(Double cloudCoverMean) {
      this.cloudCoverMean = Optional.ofNullable(cloudCoverMean);
      return this;
    }

    /**
     * <p>Daily mean dew point temperature at 2 meters (°C)</p>
     */
    @JsonSetter(
        value = "dew_point_2m_mean",
        nulls = Nulls.SKIP
    )
    public Builder dewPoint2MMean(Optional<Double> dewPoint2MMean) {
      this.dewPoint2MMean = dewPoint2MMean;
      return this;
    }

    public Builder dewPoint2MMean(Double dewPoint2MMean) {
      this.dewPoint2MMean = Optional.ofNullable(dewPoint2MMean);
      return this;
    }

    /**
     * <p>Daily maximum dew point temperature at 2 meters (°C)</p>
     */
    @JsonSetter(
        value = "dew_point_2m_max",
        nulls = Nulls.SKIP
    )
    public Builder dewPoint2MMax(Optional<Double> dewPoint2MMax) {
      this.dewPoint2MMax = dewPoint2MMax;
      return this;
    }

    public Builder dewPoint2MMax(Double dewPoint2MMax) {
      this.dewPoint2MMax = Optional.ofNullable(dewPoint2MMax);
      return this;
    }

    /**
     * <p>Daily minimum dew point temperature at 2 meters (°C)</p>
     */
    @JsonSetter(
        value = "dew_point_2m_min",
        nulls = Nulls.SKIP
    )
    public Builder dewPoint2MMin(Optional<Double> dewPoint2MMin) {
      this.dewPoint2MMin = dewPoint2MMin;
      return this;
    }

    public Builder dewPoint2MMin(Double dewPoint2MMin) {
      this.dewPoint2MMin = Optional.ofNullable(dewPoint2MMin);
      return this;
    }

    /**
     * <p>Daily mean relative humidity at 2 meters (%)</p>
     */
    @JsonSetter(
        value = "relative_humidity_2m_mean",
        nulls = Nulls.SKIP
    )
    public Builder relativeHumidity2MMean(Optional<Double> relativeHumidity2MMean) {
      this.relativeHumidity2MMean = relativeHumidity2MMean;
      return this;
    }

    public Builder relativeHumidity2MMean(Double relativeHumidity2MMean) {
      this.relativeHumidity2MMean = Optional.ofNullable(relativeHumidity2MMean);
      return this;
    }

    /**
     * <p>Daily maximum relative humidity at 2 meters (%)</p>
     */
    @JsonSetter(
        value = "relative_humidity_2m_max",
        nulls = Nulls.SKIP
    )
    public Builder relativeHumidity2MMax(Optional<Integer> relativeHumidity2MMax) {
      this.relativeHumidity2MMax = relativeHumidity2MMax;
      return this;
    }

    public Builder relativeHumidity2MMax(Integer relativeHumidity2MMax) {
      this.relativeHumidity2MMax = Optional.ofNullable(relativeHumidity2MMax);
      return this;
    }

    /**
     * <p>Daily minimum relative humidity at 2 meters (%)</p>
     */
    @JsonSetter(
        value = "relative_humidity_2m_min",
        nulls = Nulls.SKIP
    )
    public Builder relativeHumidity2MMin(Optional<Integer> relativeHumidity2MMin) {
      this.relativeHumidity2MMin = relativeHumidity2MMin;
      return this;
    }

    public Builder relativeHumidity2MMin(Integer relativeHumidity2MMin) {
      this.relativeHumidity2MMin = Optional.ofNullable(relativeHumidity2MMin);
      return this;
    }

    /**
     * <p>Daily mean atmospheric pressure at mean sea level (hPa)</p>
     */
    @JsonSetter(
        value = "pressure_msl_mean",
        nulls = Nulls.SKIP
    )
    public Builder pressureMslMean(Optional<Double> pressureMslMean) {
      this.pressureMslMean = pressureMslMean;
      return this;
    }

    public Builder pressureMslMean(Double pressureMslMean) {
      this.pressureMslMean = Optional.ofNullable(pressureMslMean);
      return this;
    }

    /**
     * <p>Daily mean surface pressure at ground level (hPa)</p>
     */
    @JsonSetter(
        value = "surface_pressure_mean",
        nulls = Nulls.SKIP
    )
    public Builder surfacePressureMean(Optional<Double> surfacePressureMean) {
      this.surfacePressureMean = surfacePressureMean;
      return this;
    }

    public Builder surfacePressureMean(Double surfacePressureMean) {
      this.surfacePressureMean = Optional.ofNullable(surfacePressureMean);
      return this;
    }

    public WeatherTimeSeriesResponseHistoricalValueDaily build() {
      return new WeatherTimeSeriesResponseHistoricalValueDaily(timestamp, weatherCode, temperature2MMean, temperature2MMax, temperature2MMin, apparentTemperatureMean, apparentTemperatureMax, apparentTemperatureMin, precipitationSum, rainSum, snowfallSum, windSpeed10MMax, windGusts10MMax, windSpeed10MMean, windSpeed10MMin, windGusts10MMin, windGusts10MMean, windDirection10MDominant, shortwaveRadiationSum, et0FaoEvapotranspirationSum, cloudCoverMean, dewPoint2MMean, dewPoint2MMax, dewPoint2MMin, relativeHumidity2MMean, relativeHumidity2MMax, relativeHumidity2MMin, pressureMslMean, surfacePressureMean, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
