/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebScrapeRequestBodyOneInstructionsItemGetForm.Builder.class
)
public final class WebScrapeRequestBodyOneInstructionsItemGetForm {
  private final Optional<WebScrapeRequestBodyOneInstructionsItemGetFormGetForm> getForm;

  private final Map<String, Object> additionalProperties;

  private WebScrapeRequestBodyOneInstructionsItemGetForm(
      Optional<WebScrapeRequestBodyOneInstructionsItemGetFormGetForm> getForm,
      Map<String, Object> additionalProperties) {
    this.getForm = getForm;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Submits a form using GET method. Provide the form's XPath/CSS selector and input values.
   */
  @JsonProperty("getForm")
  public Optional<WebScrapeRequestBodyOneInstructionsItemGetFormGetForm> getGetForm() {
    return getForm;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebScrapeRequestBodyOneInstructionsItemGetForm && equalTo((WebScrapeRequestBodyOneInstructionsItemGetForm) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebScrapeRequestBodyOneInstructionsItemGetForm other) {
    return getForm.equals(other.getForm);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.getForm);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<WebScrapeRequestBodyOneInstructionsItemGetFormGetForm> getForm = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WebScrapeRequestBodyOneInstructionsItemGetForm other) {
      getForm(other.getGetForm());
      return this;
    }

    /**
     * <p>Submits a form using GET method. Provide the form's XPath/CSS selector and input values.</p>
     */
    @JsonSetter(
        value = "getForm",
        nulls = Nulls.SKIP
    )
    public Builder getForm(
        Optional<WebScrapeRequestBodyOneInstructionsItemGetFormGetForm> getForm) {
      this.getForm = getForm;
      return this;
    }

    public Builder getForm(WebScrapeRequestBodyOneInstructionsItemGetFormGetForm getForm) {
      this.getForm = Optional.ofNullable(getForm);
      return this;
    }

    public WebScrapeRequestBodyOneInstructionsItemGetForm build() {
      return new WebScrapeRequestBodyOneInstructionsItemGetForm(getForm, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
