/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement.Builder.class
)
public final class WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement {
  private final Optional<List<String>> blockElement;

  private final Map<String, Object> additionalProperties;

  private WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement(
      Optional<List<String>> blockElement, Map<String, Object> additionalProperties) {
    this.blockElement = blockElement;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return List of CSS selectors or XPaths for elements to block or hide on the page.
   */
  @JsonProperty("blockElement")
  public Optional<List<String>> getBlockElement() {
    return blockElement;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement && equalTo((WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement other) {
    return blockElement.equals(other.blockElement);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.blockElement);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<List<String>> blockElement = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement other) {
      blockElement(other.getBlockElement());
      return this;
    }

    /**
     * <p>List of CSS selectors or XPaths for elements to block or hide on the page.</p>
     */
    @JsonSetter(
        value = "blockElement",
        nulls = Nulls.SKIP
    )
    public Builder blockElement(Optional<List<String>> blockElement) {
      this.blockElement = blockElement;
      return this;
    }

    public Builder blockElement(List<String> blockElement) {
      this.blockElement = Optional.ofNullable(blockElement);
      return this;
    }

    public WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement build() {
      return new WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement(blockElement, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
